# Traitement des données et analyse statistique avec dplyr

![](https://www.icem7.fr/wp-content/uploads/2020/11/tidyverse-1024x512.jpg)


## qu'est ce que c'est dplyr

`dplyr` est une grammaire de manipulation de données, fournissant un ensemble cohérent de verbes qui vous aident à résoudre les défis de manipulation de données les plus courants:

![](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1_6A3mVMg-owflkFlQ6tpcWdo8-5vXl9EcAnHMbvLp220c69jT1_ACJBcvz5AjvTtac4&usqp=CAU)

In [9]:
suppressPackageStartupMessages({
library(readxl)
library(dplyr)
library(tidyr)

})
options(scipen = 999)

In [10]:
fao_fbs=as.data.frame(read.csv("data/FAO_FBS_Senegal.csv"))

In [11]:
str(fao_fbs)

'data.frame':	2240 obs. of  14 variables:
 $ ï..Domain.Code  : Factor w/ 1 level "FBS": 1 1 1 1 1 1 1 1 1 1 ...
 $ Domain          : Factor w/ 1 level "New Food Balances": 1 1 1 1 1 1 1 1 1 1 ...
 $ Area.Code       : int  195 195 195 195 195 195 195 195 195 195 ...
 $ Area            : Factor w/ 1 level "Senegal": 1 1 1 1 1 1 1 1 1 1 ...
 $ Element.Code    : int  5511 5511 5511 5511 5511 5611 5611 5611 5611 5611 ...
 $ Element         : Factor w/ 5 levels "Export Quantity",..: 4 4 4 4 4 3 3 3 3 3 ...
 $ Item.Code       : int  2511 2511 2511 2511 2511 2511 2511 2511 2511 2511 ...
 $ Item            : Factor w/ 97 levels "Alcohol, Non-Food",..: 95 95 95 95 95 95 95 95 95 95 ...
 $ Year.Code       : int  2014 2015 2016 2017 2018 2014 2015 2016 2017 2018 ...
 $ Year            : int  2014 2015 2016 2017 2018 2014 2015 2016 2017 2018 ...
 $ Unit            : Factor w/ 1 level "1000 tonnes": 1 1 1 1 1 1 1 1 1 1 ...
 $ Value           : num  0 0 0 0 0 589 624 640 683 679 ...
 $ Flag            : Factor w/ 1 level "Im": 1 1 1 1 1 1 1 1 1 1 ...
 $ Flag.Description: Factor w/ 1 level "FAO data based on imputation methodology": 1 1 1 1 1 1 1 1 1 1 ...

In [12]:
names(fao_fbs)

 [1] "ï..Domain.Code"   "Domain"           "Area.Code"        "Area"
 [5] "Element.Code"     "Element"          "Item.Code"        "Item"
 [9] "Year.Code"        "Year"             "Unit"             "Value"
[13] "Flag"             "Flag.Description"

In [16]:
head(fao_fbs)

  ï..Domain.Code Domain            Area.Code Area    Element.Code
1 FBS            New Food Balances 195       Senegal 5511
2 FBS            New Food Balances 195       Senegal 5511
3 FBS            New Food Balances 195       Senegal 5511
4 FBS            New Food Balances 195       Senegal 5511
5 FBS            New Food Balances 195       Senegal 5511
6 FBS            New Food Balances 195       Senegal 5611
  Element         Item.Code Item               Year.Code Year Unit        Value
1 Production      2511      Wheat and products 2014      2014 1000 tonnes   0
2 Production      2511      Wheat and products 2015      2015 1000 tonnes   0
3 Production      2511      Wheat and products 2016      2016 1000 tonnes   0
4 Production      2511      Wheat and products 2017      2017 1000 tonnes   0
5 Production      2511      Wheat and products 2018      2018 1000 tonnes   0
6 Import Quantity 2511      Wheat and products 2014      2014 1000 tonnes 589
  Flag Flag.Description
1 Im   FAO data based on imputation methodology
2 Im   FAO data based on imputation methodology
3 Im   FAO data based on imputation methodology
4 Im   FAO data based on imputation methodology
5 Im   FAO data based on imputation methodology
6 Im   FAO data based on imputation methodology

In [18]:
unique(fao_fbs$Element)
unique(fao_fbs$Item)

[1] Production      Import Quantity Stock Variation Export Quantity
[5] Food
Levels: Export Quantity Food Import Quantity Production Stock Variation

 [1] Wheat and products              Rice and products
 [3] Barley and products             Maize and products
 [5] Rye and products                Oats
 [7] Millet and products             Sorghum and products
 [9] Cereals, Other                  Cassava and products
[11] Potatoes and products           Sweet potatoes
[13] Yams                            Roots, Other
[15] Sugar cane                      Sugar beet
[17] Sugar non-centrifugal           Sugar (Raw Equivalent)
[19] Sweeteners, Other               Honey
[21] Beans                           Peas
[23] Pulses, Other and products      Nuts and products
[25] Soyabeans                       Groundnuts (Shelled Eq)
[27] Sunflower seed                  Rape and Mustardseed
[29] Cottonseed                      Coconuts - Incl Copra
[31] Sesame seed                     Palm kernels
[33] Olives (including preserved)    Oilcrops, Other
[35] Soyabean Oil                    Groundnut Oil
[37] Sunflowerseed Oil               Rape and Mustard Oil
[39] Cottonseed Oil                  Palmkernel Oil
[41] Palm Oil                        Coconut Oil
[43] Sesameseed Oil                  Olive Oil
[45] Ricebran Oil                    Maize Germ Oil
[47] Oilcrops Oil, Other             Tomatoes and products
[49] Onions                          Vegetables, Other
[51] Oranges, Mandarines             Lemons, Limes and products
[53] Grapefruit and products         Citrus, Other
[55] Bananas                         Plantains
[57] Apples and products             Pineapples and products
[59] Dates                           Grapes and products (excl wine)
[61] Fruits, Other                   Coffee and products
[63] Cocoa Beans and products        Tea (including mate)
[65] Pepper                          Pimento
[67] Cloves                          Spices, Other
[69] Wine                            Beer
[71] Beverages, Fermented            Beverages, Alcoholic
[73] Alcohol, Non-Food               Bovine Meat
[75] Mutton & Goat Meat              Pigmeat
[77] Poultry Meat                    Meat, Other
[79] Offals, Edible                  Butter, Ghee
[81] Cream                           Fats, Animals, Raw
[83] Fish, Body Oil                  Fish, Liver Oil
[85] Eggs                            Milk - Excluding Butter
[87] Freshwater Fish                 Demersal Fish
[89] Pelagic Fish                    Marine Fish, Other
[91] Crustaceans                     Cephalopods
[93] Molluscs, Other                 Aquatic Animals, Others
[95] Aquatic Plants                  Infant food
[97] Miscellaneous
97 Levels: Alcohol, Non-Food Apples and products ... Yams

In [20]:
fao_cdu=as.data.frame(read.csv("data/FAO_CDU_Senegal.csv"))
str(fao_cdu)
head(fao_cdu)

'data.frame':	2687 obs. of  14 variables:
 $ ï..Domain.Code  : Factor w/ 1 level "SC": 1 1 1 1 1 1 1 1 1 1 ...
 $ Domain          : Factor w/ 1 level "Crops": 1 1 1 1 1 1 1 1 1 1 ...
 $ Area.Code       : int  195 195 195 195 195 195 195 195 195 195 ...
 $ Area            : Factor w/ 1 level "Senegal": 1 1 1 1 1 1 1 1 1 1 ...
 $ Element.Code    : int  5610 5610 5610 5610 5610 5071 5071 5071 5071 5071 ...
 $ Element         : Factor w/ 11 levels "Export Quantity",..: 4 4 4 4 4 11 11 11 11 11 ...
 $ Item.Code       : num  1371 1371 1371 1371 1371 ...
 $ Item            : Factor w/ 115 levels "Almonds, with shell",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ Year.Code       : int  2014 2015 2016 2017 2018 2014 2015 2016 2017 2018 ...
 $ Year            : int  2014 2015 2016 2017 2018 2014 2015 2016 2017 2018 ...
 $ Unit            : Factor w/ 1 level "tonnes": 1 1 1 1 1 1 1 1 1 1 ...
 $ Value           : int  7 2 5 6 7 6 0 3 3 1 ...
 $ Flag            : Factor w/ 5 levels "","*","F","Im",..: 1 1 1 1 1 4 4 4 4 4 ...
 $ Flag.Description: Factor w/ 5 levels "Data not available",..: 4 4 4 4 4 2 2 2 2 2 ...

  ï..Domain.Code Domain Area.Code Area    Element.Code Element
1 SC             Crops  195       Senegal 5610         Import Quantity
2 SC             Crops  195       Senegal 5610         Import Quantity
3 SC             Crops  195       Senegal 5610         Import Quantity
4 SC             Crops  195       Senegal 5610         Import Quantity
5 SC             Crops  195       Senegal 5610         Import Quantity
6 SC             Crops  195       Senegal 5071         Stock Variation
  Item.Code Item                Year.Code Year Unit   Value Flag
1 1371      Almonds, with shell 2014      2014 tonnes 7
2 1371      Almonds, with shell 2015      2015 tonnes 2
3 1371      Almonds, with shell 2016      2016 tonnes 5
4 1371      Almonds, with shell 2017      2017 tonnes 6
5 1371      Almonds, with shell 2018      2018 tonnes 7
6 1371      Almonds, with shell 2014      2014 tonnes 6     Im
  Flag.Description
1 Official data
2 Official data
3 Official data
4 Official data
5 Official data
6 FAO data based on imputation methodology

In [21]:
unique(fao_cdu$Item)

  [1] Almonds, with shell
  [2] Anise, badian, fennel, coriander
  [3] Apples
  [4] Apricots
  [5] Areca nuts
  [6] Artichokes
  [7] Asparagus
  [8] Avocados
  [9] Bambara beans
 [10] Bananas
 [11] Barley
 [12] Beans, dry
 [13] Beans, green
 [14] Berries nes
 [15] Brazil nuts, with shell
 [16] Broad beans, horse beans, dry
 [17] Cabbages and other brassicas
 [18] Canary seed
 [19] Carrots and turnips
 [20] Cashew nuts, with shell
 [21] Cassava
 [22] Cauliflowers and broccoli
 [23] Cereals nes
 [24] Cherries
 [25] Cherries, sour
 [26] Chestnut
 [27] Chick peas
 [28] Chillies and peppers, dry
 [29] Chillies and peppers, green
 [30] Cinnamon (cannella)
 [31] Cloves
 [32] Cocoa, beans
 [33] Coconuts
 [34] Coffee, green
 [35] Cow peas, dry
 [36] Cucumbers and gherkins
 [37] Currants
 [38] Dates
 [39] Eggplants (aubergines)
 [40] Figs
 [41] Fonio
 [42] Fruit, citrus nes
 [43] Fruit, fresh nes
 [44] Fruit, tropical fresh nes
 [45] Garlic
 [46] Ginger
 [47] Grapefruit (inc. pomelos)
 [48] Grapes
 [49] Groundnuts, with shell
 [50] Hazelnuts, with shell
 [51] Kiwi fruit
 [52] Kola nuts
 [53] Leeks, other alliaceous vegetables
 [54] Lemons and limes
 [55] Lentils
 [56] Lettuce and chicory
 [57] Linseed
 [58] Maize
 [59] Mangoes, mangosteens, guavas
 [60] MatÃ©
 [61] Melons, other (inc.cantaloupes)
 [62] Melonseed
 [63] Millet
 [64] Mushrooms and truffles
 [65] Mustard seed
 [66] Nutmeg, mace and cardamoms
 [67] Nuts nes
 [68] Oats
 [69] Oil palm fruit
 [70] Oilseeds nes
 [71] Okra
 [72] Olives
 [73] Onions, dry
 [74] Oranges
 [75] Papayas
 [76] Peaches and nectarines
 [77] Pears
 [78] Peas, dry
 [79] Peas, green
 [80] Pepper (piper spp.)
 [81] Persimmons
 [82] Pigeon peas
 [83] Pineapples
 [84] Pistachios
 [85] Plantains and others
 [86] Plums and sloes
 [87] Poppy seed
 [88] Potatoes
 [89] Pulses nes
 [90] Pumpkins, squash and gourds
 [91] Quinces
 [92] Quinoa
 [93] Rapeseed
 [94] Rice, paddy
 [95] Sesame seed
 [96] Sorghum
 [97] Soybeans
 [98] Spices nes
 [99] Spinach
[100] Strawberries
[101] Sugar beet
[102] Sugar cane
[103] Sunflower seed
[104] Sweet corn frozen
[105] Sweet corn prep or preserved
[106] Sweet potatoes
[107] Tangerines, mandarins, clementines, satsumas
[108] Tea
[109] Tomatoes
[110] Vanilla
[111] Vegetables, fresh nes
[112] Walnuts, with shell
[113] Watermelons
[114] Wheat
[115] Yams
115 Levels: Almonds, with shell Anise, badian, fennel, coriander ... Yams

In [22]:
path_mb="data/indicateur_BM_Senegal.xls"
excel_sheets(path_mb)

[1] "Data"                  "Metadata - Countries"  "Metadata - Indicators"

In [143]:
donnee_bm=as.data.frame(read_excel(path_mb,sheet = "Data",skip = 3))
str(donnee_bm)
head(donnee_bm)

'data.frame':	1440 obs. of  65 variables:
 $ Country Name  : chr  "Sénégal" "Sénégal" "Sénégal" "Sénégal" ...
 $ Country Code  : chr  "SEN" "SEN" "SEN" "SEN" ...
 $ Indicator Name: chr  "Internally displaced persons, total displaced by conflict and violence (number of people)" "Exportations de marchandises vers les pays en développement du Moyen-Orient et d’Afrique du Nord (% des exporta"| __truncated__ "Indice du volume des exportations (2000=100)" "Importations de marchandises des pays en développement d’Asie de l’Est et du Pacifique (% des importations tota"| __truncated__ ...
 $ Indicator Code: chr  "VC.IDP.TOCV" "TX.VAL.MRCH.R4.ZS" "TX.QTY.MRCH.XD.WD" "TM.VAL.MRCH.R1.ZS" ...
 $ 1960          : num  NA 5.2 NA 5.57 NA ...
 $ 1961          : num  NA 5.22 NA 7.38 NA ...
 $ 1962          : num  NA 2.43 NA 5.76 NA ...
 $ 1963          : num  NA 0.635 NA 8.368 NA ...
 $ 1964          : num  NA 0.578 NA 10.52 NA ...
 $ 1965          : num  NA 0.235 NA 11.538 NA ...
 $ 1966          : num  NA 0.47 NA 8.39 NA ...
 $ 1967          : num  NA 0.516 NA 13.693 NA ...
 $ 1968          : num  NA 0.399 NA 8.533 NA ...
 $ 1969          : num  NA 0.0441 NA 5.5404 NA ...
 $ 1970          : num  NA 0.281 NA 4.749 NA ...
 $ 1971          : num  NA 0.547 NA 3.984 NA ...
 $ 1972          : num  NA 0.731 NA 6.427 NA ...
 $ 1973          : num  NA 0.588 NA 8.971 NA ...
 $ 1974          : num  NA 1.55 NA 6.75 NA ...
 $ 1975          : num  NA 0.388 NA 1.488 NA ...
 $ 1976          : num  NA 0.0563 NA 2.3002 NA ...
 $ 1977          : num  NA 0.271 NA 4.238 NA ...
 $ 1978          : num  NA 0.441 NA 3.008 NA ...
 $ 1979          : num  NA 0.0211 NA 7.5482 NA ...
 $ 1980          : num  NA 0.666 32.407 8.095 NA ...
 $ 1981          : num  NA 0.532 35.301 9.069 NA ...
 $ 1982          : num  NA 0.555 46.534 10.486 NA ...
 $ 1983          : num  NA NA 57.9 11.2 NA ...
 $ 1984          : num  NA 0.311 56.035 9.781 NA ...
 $ 1985          : num  NA 0.529 48.491 5.359 NA ...
 $ 1986          : num  NA 0.125 47.546 5.931 NA ...
 $ 1987          : num  NA 0.326 40.695 3.149 NA ...
 $ 1988          : num  NA 0.681 40.169 5.005 NA ...
 $ 1989          : num  NA 0.636 45.666 5.526 NA ...
 $ 1990          : num  NA 2.32 44.52 5.94 NA ...
 $ 1991          : num  NA 1.62 42.33 6.52 NA ...
 $ 1992          : num  NA 3.46 39.32 7.14 NA ...
 $ 1993          : num  NA 4.2 45.21 8.68 NA ...
 $ 1994          : num  NA 3.76 57.71 7.15 NA ...
 $ 1995          : num  NA 1.96 61.71 7.77 NA ...
 $ 1996          : num  NA 1.7 65.49 7.51 NA ...
 $ 1997          : num  NA 0.888 81.955 8.531 NA ...
 $ 1998          : num  NA 1.74 87.67 8.82 NA ...
 $ 1999          : num  NA 0.712 96.263 10.718 NA ...
 $ 2000          : num  NA 0.762 100 11.848 NA ...
 $ 2001          : num  NA 0.751 114.54 12.883 11.78 ...
 $ 2002          : num  NA 0.76 123.23 11.99 11.78 ...
 $ 2003          : num  NA 0.667 131.686 11.695 11.79 ...
 $ 2004          : num  NA 0.905 140.757 12.108 11.83 ...
 $ 2005          : num  NA 0.999 131.973 10.714 11.82 ...
 $ 2006          : num  NA 2.23 121.76 11.29 11.82 ...
 $ 2007          : num  NA 0.812 114.643 12.62 11.98 ...
 $ 2008          : num  NA 0.464 120.976 14.107 11.97 ...
 $ 2009          : num  24000 1.83 131.33 17.46 11.98 ...
 $ 2010          : num  24000 2.57 123.67 14.59 11.98 ...
 $ 2011          : num  24000 2.78 113.86 13.67 11.97 ...
 $ 2012          : num  22000 0.56 112.39 9.16 11.97 ...
 $ 2013          : num  24000 0.903 121.154 11.201 11.98 ...
 $ 2014          : num  24000 1.19 127.69 11.34 11.98 ...
 $ 2015          : num  24000 1.34 142.33 13.04 13.28 ...
 $ 2016          : num  24000 1.1 148.2 13.3 13.3 ...
 $ 2017          : num  22000 1 157.1 13.9 13.3 ...
 $ 2018          : num  18000 0.944 174.138 15.155 13.26 ...
 $ 2019          : num  8400 NA NA NA NA ...
 $ 2020          : num  NA NA NA NA NA NA NA NA NA NA ...

  Country Name Country Code
1 Sénégal      SEN
2 Sénégal      SEN
3 Sénégal      SEN
4 Sénégal      SEN
5 Sénégal      SEN
6 Sénégal      SEN
  Indicator Name
1 Internally displaced persons, total displaced by conflict and violence (number of people)
2 Exportations de marchandises vers les pays en développement du Moyen-Orient et d’Afrique du Nord (% des exportations totales de marchandises)
3 Indice du volume des exportations (2000=100)
4 Importations de marchandises des pays en développement d’Asie de l’Est et du Pacifique (% des importations totales de marchandises)
5 Taux des droits de douane, nation la plus favorisée, moyenne simple, produits de base (%)
6 Taux des droits de douane, nation la plus favorisée, moyenne simple, produits manufacturés (%)
  Indicator Code       1960     1961     1962     1963      1964
1 VC.IDP.TOCV                NA       NA       NA        NA         NA
2 TX.VAL.MRCH.R4.ZS    5.197133 5.220884 2.429150 0.6352087  0.5775578
3 TX.QTY.MRCH.XD.WD          NA       NA       NA        NA         NA
4 TM.VAL.MRCH.R1.ZS    5.568445 7.377049 5.764249 8.3679525 10.5201636
5 TM.TAX.TCOM.SM.FN.ZS       NA       NA       NA        NA         NA
6 TM.TAX.MANF.SM.FN.ZS       NA       NA       NA        NA         NA
  1965       ... 2011        2012          2013         2014
1         NA ... 24000.00000 22000.0000000 24000.000000 24000.000000
2  0.2354788 ...     2.77710     0.5600395     0.903348     1.187657
3         NA ...   113.86423   112.3854860   121.153762   127.691437
4 11.5384615 ...    13.67211     9.1627080    11.201373    11.339275
5         NA ...    11.97000    11.9700000    11.980000    11.980000
6         NA ...    11.87000    11.8700000    11.870000    11.870000
  2015         2016         2017         2018          2019 2020
1 24000.000000 24000.000000 22000.000000 18000.0000000 8400 NA
2     1.337134     1.098842     1.003992     0.9438729   NA NA
3   142.326747   148.185242   157.055589   174.1382185   NA NA
4    13.036677    13.309373    13.883524    15.1549097   NA NA
5    13.280000    13.280000    13.260000    13.2600000   NA NA
6    11.770000    11.770000    11.790000    11.7900000   NA NA

In [24]:
path_fmi="data/FMI_PIB_et_composantes.xlsx"
excel_sheets(path_fmi)
donnee_fmi=as.data.frame(read_excel(path_fmi,sheet = "Annual",skip = 6))
str(donnee_fmi)
head(donnee_fmi)

[1] "Annual"    "Quarterly"

New names:
* `` -> ...2

'data.frame':	24 obs. of  20 variables:
 $ Indicator: chr  "National Accounts, Current Prices, Non-Seasonally Adjusted" "Gross Domestic Product, Nominal, Domestic Currency" "Household Consumption Expenditure, incl. NPISHs, Nominal, Domestic Currency" "Government Consumption Expenditure, Nominal, Domestic Currency" ...
 $ ...2     : chr  NA "NGDP_XDC" "NCP_XDC" "NCGG_XDC" ...
 $ Base Year: chr  NA NA NA NA ...
 $ Scale    : chr  NA "Millions" "Millions" "Millions" ...
 $ 2004     : chr  "..." "5371304.9866449004" "4296873.47909535" "700281.035233467" ...
 $ 2005     : chr  "..." "5814186.7828154294" "4655870.8980412995" "748841.04489883804" ...
 $ 2006     : chr  "..." "6195122.5431449804" "5056156.2170517305" "819324.04056452203" ...
 $ 2007     : chr  "..." "6846791.1675585397" "5577325.6226699203" "940701.82" ...
 $ 2008     : chr  "..." "7590205.5561305303" "6346712.1025944808" "926099.47882518102" ...
 $ 2009     : chr  "..." "7672183.5083290003" "6220093.37878762" "988796.95377736806" ...
 $ 2010     : chr  "..." "8030950.8556799805" "6395224.2118312502" "1088039.12540696" ...
 $ 2011     : chr  "..." "8436390.2785922997" "6766064.0747498795" "1208729.8396906399" ...
 $ 2012     : chr  "..." "9100358.9320069104" "7081869.4851756599" "1275312.45350631" ...
 $ 2013     : chr  "..." "9367088.498763321" "7268246.3849652503" "1314685.3116335301" ...
 $ 2014     : chr  "..." "9775039" "7259973" "1440315" ...
 $ 2015     : chr  "..." "10508650" "7631735" "1502661" ...
 $ 2016     : chr  "..." "11283396" "8078178" "1583205" ...
 $ 2017     : chr  "..." "12191796" "8582484" "1662226" ...
 $ 2018     : chr  "..." "12907359" "8920535" "1774264" ...
 $ 2019     : chr  "..." "13814658.804999199" "9464066.4151200801" "1883282.9159144" ...

  Indicator
1 National Accounts, Current Prices, Non-Seasonally Adjusted
2 Gross Domestic Product, Nominal, Domestic Currency
3 Household Consumption Expenditure, incl. NPISHs, Nominal, Domestic Currency
4 Government Consumption Expenditure, Nominal, Domestic Currency
5 Gross Fixed Capital Formation, Nominal, Domestic Currency
6 Change in Inventories, Nominal, Domestic Currency
  ...2     Base Year Scale    2004                2005
1 NA       NA        NA       ...                 ...
2 NGDP_XDC NA        Millions 5371304.9866449004  5814186.7828154294
3 NCP_XDC  NA        Millions 4296873.47909535    4655870.8980412995
4 NCGG_XDC NA        Millions 700281.035233467    748841.04489883804
5 NFI_XDC  NA        Millions 955809.39618684398  1086931.4170581501
6 NINV_XDC NA        Millions -45988.329670753701 30079.027875780401
  2006               2007               2008               2009
1 ...                ...                ...                ...
2 6195122.5431449804 6846791.1675585397 7590205.5561305303 7672183.5083290003
3 5056156.2170517305 5577325.6226699203 6346712.1025944808 6220093.37878762
4 819324.04056452203 940701.82          926099.47882518102 988796.95377736806
5 1291907.0623588301 1426925.4088176899 1713922.2067138401 1527203.3157945802
6 -117307.816830104  112602.89530358299 180091.76799702601 -45416.140030571099
  2010               2011                2012               2013
1 ...                ...                 ...                ...
2 8030950.8556799805 8436390.2785922997  9100358.9320069104 9367088.498763321
3 6395224.2118312502 6766064.0747498795  7081869.4851756599 7268246.3849652503
4 1088039.12540696   1208729.8396906399  1275312.45350631   1314685.3116335301
5 1494587.8675903999 1783351.8737647601  1886387.6884058202 2092144.7136075401
6 38272.650851368897 -79719.314991865598 385502.98387311702 225501.28744322501
  2014             2015     2016             2017     2018
1 ...              ...      ...              ...      ...
2 9775039          10508650 11283396         12191796 12907359
3 7259973          7631735  8078178          8582484  8920535
4 1440315          1502661  1583205          1662226  1774264
5 2316171          2440321  2722111          3172840  3385323
6 218602.978293422 276911   137466.312647999 462644   767873
  2019
1 ...
2 13814658.804999199
3 9464066.4151200801
4 1883282.9159144
5 3989720.4407436801
6 386895.04192137404

## dplyr::select

![](https://uw-madison-datascience.github.io/2019-09-11-uwmadison-dc/slides/dplyr/dplyr-2.png)

Sélectionner (et renommer éventuellement) des variables dans un data.frame, en utilisant un mini-langage concis qui facilite la référence aux variables en fonction de leur nom (par exemple, sélectionner toutes les colonnes de a à gauche à f à droite). 
Vous pouvez également utiliser des fonctions de **prédicat** comme **is.numeric** pour sélectionner des variables en fonction de leurs propriétés.


Les sélections de dplyr implémentent un dialecte de R où les opérateurs facilitent la sélection
variables:

* `:` pour sélectionner une plage de variables consécutives.

* `!` pour prendre le complément d'un ensemble de variables.

* `&` et `|` pour sélectionner l'intersection ou l'union de deux ensembles de variables.

* `c()` pour combiner des sélections.

De plus, vous pouvez utiliser des aides à la sélection. 
Certains assistants(helpers) sélectionnent des colonnes spécifiques:

* `everything()`: correspond à toutes les variables.

* `last_col()`: Sélectionnez la dernière variable

Ces assistants sélectionnent des variables en faisant correspondre des modèles dans leurs noms:

* `starts_with()`: commence par un pre x.

* `ends_with()`: se termine par un su x.

* `contains()`: contient une chaîne littérale.
 
* `matches()`: correspond à une expression régulière.

* `num_range()`: correspond à une plage numérique telle que x01, x02, x03.

Ces assistants sélectionnent des variables à partir d'un vecteur de caractères:

* `all_of()`: correspond aux noms de variables dans un vecteur de caractères. Tous les noms doivent être présents, sinon, une erreur hors limites est émise.

* `all_of()`: Identique à tout (), sauf qu'aucune erreur n'est renvoyée pour les noms qui ne
exister.

Cet assistant sélectionne les variables avec une fonction:

* `where()`: applique une fonction à toutes les variables et sélectionne celles pour lesquelles la fonction
renvoie TRUE.

In [100]:
names(fao_cdu)
select(fao_cdu,Element,Item,Year,Unit,Flag,Flag.Description) %>% head()

 [1] "ï..Domain.Code"   "Domain"           "Area.Code"        "Area"
 [5] "Element.Code"     "Element"          "Item.Code"        "Item"
 [9] "Year.Code"        "Year"             "Unit"             "Value"
[13] "Flag"             "Flag.Description"

  Element         Item                Year Unit   Flag
1 Import Quantity Almonds, with shell 2014 tonnes
2 Import Quantity Almonds, with shell 2015 tonnes
3 Import Quantity Almonds, with shell 2016 tonnes
4 Import Quantity Almonds, with shell 2017 tonnes
5 Import Quantity Almonds, with shell 2018 tonnes
6 Stock Variation Almonds, with shell 2014 tonnes Im
  Flag.Description
1 Official data
2 Official data
3 Official data
4 Official data
5 Official data
6 FAO data based on imputation methodology

f(x,y)=> x %>% f(y)

In [101]:
fao_cdu %>% select(Element,Item,Year,Unit,Flag,Flag.Description) %>% head()

  Element         Item                Year Unit   Flag
1 Import Quantity Almonds, with shell 2014 tonnes
2 Import Quantity Almonds, with shell 2015 tonnes
3 Import Quantity Almonds, with shell 2016 tonnes
4 Import Quantity Almonds, with shell 2017 tonnes
5 Import Quantity Almonds, with shell 2018 tonnes
6 Stock Variation Almonds, with shell 2014 tonnes Im
  Flag.Description
1 Official data
2 Official data
3 Official data
4 Official data
5 Official data
6 FAO data based on imputation methodology

In [102]:
names(fao_cdu)
fao_cdu %>% select(contains("Code")) %>% head()

 [1] "ï..Domain.Code"   "Domain"           "Area.Code"        "Area"
 [5] "Element.Code"     "Element"          "Item.Code"        "Item"
 [9] "Year.Code"        "Year"             "Unit"             "Value"
[13] "Flag"             "Flag.Description"

  ï..Domain.Code Area.Code Element.Code Item.Code Year.Code
1 SC             195       5610         1371      2014
2 SC             195       5610         1371      2015
3 SC             195       5610         1371      2016
4 SC             195       5610         1371      2017
5 SC             195       5610         1371      2018
6 SC             195       5071         1371      2014

In [103]:
fao_cdu %>% select(!contains("Code")) %>% head()

  Domain Area    Element         Item                Year Unit   Value Flag
1 Crops  Senegal Import Quantity Almonds, with shell 2014 tonnes 7
2 Crops  Senegal Import Quantity Almonds, with shell 2015 tonnes 2
3 Crops  Senegal Import Quantity Almonds, with shell 2016 tonnes 5
4 Crops  Senegal Import Quantity Almonds, with shell 2017 tonnes 6
5 Crops  Senegal Import Quantity Almonds, with shell 2018 tonnes 7
6 Crops  Senegal Stock Variation Almonds, with shell 2014 tonnes 6     Im
  Flag.Description
1 Official data
2 Official data
3 Official data
4 Official data
5 Official data
6 FAO data based on imputation methodology

In [31]:
fao_cdu %>% select(ends_with("Code")) %>% head()

  ï..Domain.Code Area.Code Element.Code Item.Code Year.Code
1 SC             195       5610         1371      2014
2 SC             195       5610         1371      2015
3 SC             195       5610         1371      2016
4 SC             195       5610         1371      2017
5 SC             195       5610         1371      2018
6 SC             195       5071         1371      2014

In [32]:
fao_cdu %>% select(where(is.numeric)) %>% head()

  Area.Code Element.Code Item.Code Year.Code Year Value
1 195       5610         1371      2014      2014 7
2 195       5610         1371      2015      2015 2
3 195       5610         1371      2016      2016 5
4 195       5610         1371      2017      2017 6
5 195       5610         1371      2018      2018 7
6 195       5071         1371      2014      2014 6

In [33]:
fao_cdu %>% select(is.numeric)

Warning message:
"Predicate functions must be wrapped in `where()`.

  # Bad
  data %>% select(is.numeric)

  # Good
  data %>% select(where(is.numeric))

i Please update your code.
This message is displayed once per session."

     Area.Code Element.Code Item.Code Year.Code Year Value
1    195       5610         1371      2014      2014  7
2    195       5610         1371      2015      2015  2
3    195       5610         1371      2016      2016  5
4    195       5610         1371      2017      2017  6
5    195       5610         1371      2018      2018  7
6    195       5071         1371      2014      2014  6
7    195       5071         1371      2015      2015  0
8    195       5071         1371      2016      2016  3
9    195       5071         1371      2017      2017  3
10   195       5071         1371      2018      2018  1
11   195       5166         1371      2014      2014  0
12   195       5166         1371      2015      2015  0
13   195       5166         1371      2016      2016  0
14   195       5166         1371      2017      2017  0
15   195       5166         1371      2018      2018  0
16   195       5141         1371      2014      2014  1
17   195       5141         1371      2015      2015  2
18   195       5141         1371      2016      2016  2
19   195       5141         1371      2017      2017  3
20   195       5141         1371      2018      2018  6
21   195       5610         1654      2014      2014  4
22   195       5610         1654      2015      2015  2
23   195       5610         1654      2016      2016  9
24   195       5610         1654      2017      2017  2
25   195       5610         1654      2018      2018 15
26   195       5071         1654      2014      2014  0
27   195       5071         1654      2015      2015  0
28   195       5071         1654      2016      2016  0
29   195       5071         1654      2017      2017  0
30   195       5071         1654      2018      2018  0
...  ...       ...          ...       ...       ...  ...
2658 195       5166          111      2018      2018     0
2659 195       5510         1540      2014      2014 28350
2660 195       5510         1540      2015      2015 35000
2661 195       5510         1540      2016      2016 70000
2662 195       5510         1540      2017      2017 72000
2663 195       5510         1540      2018      2018 70000
2664 195       5610         1540      2014      2014    89
2665 195       5610         1540      2015      2015   109
2666 195       5610         1540      2016      2016   114
2667 195       5610         1540      2017      2017   109
2668 195       5610         1540      2018      2018    86
2669 195       5071         1540      2014      2014    56
2670 195       5071         1540      2015      2015   109
2671 195       5071         1540      2016      2016   102
2672 195       5071         1540      2017      2017   109
2673 195       5071         1540      2018      2018    86
2674 195       5910         1540      2014      2014   383
2675 195       5910         1540      2015      2015     1
2676 195       5910         1540      2016      2016    12
2677 195       5910         1540      2017      2017     0
2678 195       5166         1540      2014      2014     0
2679 195       5166         1540      2015      2015     0
2680 195       5166         1540      2016      2016     0
2681 195       5166         1540      2017      2017     0
2682 195       5166         1540      2018      2018     0
2683 195       5141         1540      2014      2014 28000
2684 195       5141         1540      2015      2015 35000
2685 195       5141         1540      2016      2016 70000
2686 195       5141         1540      2017      2017 72000
2687 195       5141         1540      2018      2018 70000

In [38]:
names(fao_cdu)
fao_cdu %>% select(!is.numeric & !contains("Domain")) %>% head()

 [1] "ï..Domain.Code"   "Domain"           "Area.Code"        "Area"
 [5] "Element.Code"     "Element"          "Item.Code"        "Item"
 [9] "Year.Code"        "Year"             "Unit"             "Value"
[13] "Flag"             "Flag.Description"

  Area    Element         Item                Unit   Flag
1 Senegal Import Quantity Almonds, with shell tonnes
2 Senegal Import Quantity Almonds, with shell tonnes
3 Senegal Import Quantity Almonds, with shell tonnes
4 Senegal Import Quantity Almonds, with shell tonnes
5 Senegal Import Quantity Almonds, with shell tonnes
6 Senegal Stock Variation Almonds, with shell tonnes Im
  Flag.Description
1 Official data
2 Official data
3 Official data
4 Official data
5 Official data
6 FAO data based on imputation methodology

In [40]:
fao_fbs %>% select(DC=`ï..Domain.Code`, D=Domain,Valeur=Value) %>% head()

  DC  D                 Valeur
1 FBS New Food Balances   0
2 FBS New Food Balances   0
3 FBS New Food Balances   0
4 FBS New Food Balances   0
5 FBS New Food Balances   0
6 FBS New Food Balances 589

In [43]:
annee=as.character(2000:2020)
annee2=as.character(2010:2035)
annee
annee2

 [1] "2000" "2001" "2002" "2003" "2004" "2005" "2006" "2007" "2008" "2009"
[11] "2010" "2011" "2012" "2013" "2014" "2015" "2016" "2017" "2018" "2019"
[21] "2020"

 [1] "2010" "2011" "2012" "2013" "2014" "2015" "2016" "2017" "2018" "2019"
[11] "2020" "2021" "2022" "2023" "2024" "2025" "2026" "2027" "2028" "2029"
[21] "2030" "2031" "2032" "2033" "2034" "2035"

In [105]:
donnee_bm %>% select(all_of(annee)) %>% head()
# donnee_bm %>% select(all_of(annee2)) # erreur
donnee_bm %>% select(any_of(annee2)) %>% head()

  2000        2001        2002        2003        2004        2005
1          NA          NA          NA          NA          NA          NA
2   0.7624651   0.7513871   0.7597229   0.6669112   0.9052898   0.9985082
3 100.0000000 114.5403671 123.2301588 131.6855818 140.7571798 131.9730691
4  11.8475493  12.8830937  11.9949521  11.6949326  12.1084776  10.7138357
5          NA  11.7800000  11.7800000  11.7900000  11.8300000  11.8200000
6          NA  12.0400000  12.0000000  12.0100000  12.0100000  12.0200000
  2006       2007        2008        2009         ... 2011        2012
1         NA          NA          NA 24000.000000 ... 24000.00000 22000.0000000
2   2.231633   0.8123906   0.4644018     1.834659 ...     2.77710     0.5600395
3 121.764641 114.6426950 120.9763335   131.331898 ...   113.86423   112.3854860
4  11.288805  12.6196376  14.1073699    17.459932 ...    13.67211     9.1627080
5  11.820000  11.9800000  11.9700000    11.980000 ...    11.97000    11.9700000
6  12.020000  11.9000000  11.9000000    11.900000 ...    11.87000    11.8700000
  2013         2014         2015         2016         2017
1 24000.000000 24000.000000 24000.000000 24000.000000 22000.000000
2     0.903348     1.187657     1.337134     1.098842     1.003992
3   121.153762   127.691437   142.326747   148.185242   157.055589
4    11.201373    11.339275    13.036677    13.309373    13.883524
5    11.980000    11.980000    13.280000    13.280000    13.260000
6    11.870000    11.870000    11.770000    11.770000    11.790000
  2018          2019 2020
1 18000.0000000 8400 NA
2     0.9438729   NA NA
3   174.1382185   NA NA
4    15.1549097   NA NA
5    13.2600000   NA NA
6    11.7900000   NA NA

  2010        2011        2012          2013         2014         2015
1 24000.00000 24000.00000 22000.0000000 24000.000000 24000.000000 24000.000000
2     2.57239     2.77710     0.5600395     0.903348     1.187657     1.337134
3   123.67173   113.86423   112.3854860   121.153762   127.691437   142.326747
4    14.59087    13.67211     9.1627080    11.201373    11.339275    13.036677
5    11.98000    11.97000    11.9700000    11.980000    11.980000    13.280000
6    11.90000    11.87000    11.8700000    11.870000    11.870000    11.770000
  2016         2017         2018          2019 2020
1 24000.000000 22000.000000 18000.0000000 8400 NA
2     1.098842     1.003992     0.9438729   NA NA
3   148.185242   157.055589   174.1382185   NA NA
4    13.309373    13.883524    15.1549097   NA NA
5    13.280000    13.260000    13.2600000   NA NA
6    11.770000    11.790000    11.7900000   NA NA

In [55]:
donnee_fmi %>% dplyr::select(is.character) %>% head()

  Indicator
1 National Accounts, Current Prices, Non-Seasonally Adjusted
2 Gross Domestic Product, Nominal, Domestic Currency
3 Household Consumption Expenditure, incl. NPISHs, Nominal, Domestic Currency
4 Government Consumption Expenditure, Nominal, Domestic Currency
5 Gross Fixed Capital Formation, Nominal, Domestic Currency
6 Change in Inventories, Nominal, Domestic Currency
  ...2     Base Year Scale    2004                2005
1 NA       NA        NA       ...                 ...
2 NGDP_XDC NA        Millions 5371304.9866449004  5814186.7828154294
3 NCP_XDC  NA        Millions 4296873.47909535    4655870.8980412995
4 NCGG_XDC NA        Millions 700281.035233467    748841.04489883804
5 NFI_XDC  NA        Millions 955809.39618684398  1086931.4170581501
6 NINV_XDC NA        Millions -45988.329670753701 30079.027875780401
  2006               2007               2008               2009
1 ...                ...                ...                ...
2 6195122.5431449804 6846791.1675585397 7590205.5561305303 7672183.5083290003
3 5056156.2170517305 5577325.6226699203 6346712.1025944808 6220093.37878762
4 819324.04056452203 940701.82          926099.47882518102 988796.95377736806
5 1291907.0623588301 1426925.4088176899 1713922.2067138401 1527203.3157945802
6 -117307.816830104  112602.89530358299 180091.76799702601 -45416.140030571099
  2010               2011                2012               2013
1 ...                ...                 ...                ...
2 8030950.8556799805 8436390.2785922997  9100358.9320069104 9367088.498763321
3 6395224.2118312502 6766064.0747498795  7081869.4851756599 7268246.3849652503
4 1088039.12540696   1208729.8396906399  1275312.45350631   1314685.3116335301
5 1494587.8675903999 1783351.8737647601  1886387.6884058202 2092144.7136075401
6 38272.650851368897 -79719.314991865598 385502.98387311702 225501.28744322501
  2014             2015     2016             2017     2018
1 ...              ...      ...              ...      ...
2 9775039          10508650 11283396         12191796 12907359
3 7259973          7631735  8078178          8582484  8920535
4 1440315          1502661  1583205          1662226  1774264
5 2316171          2440321  2722111          3172840  3385323
6 218602.978293422 276911   137466.312647999 462644   767873
  2019
1 ...
2 13814658.804999199
3 9464066.4151200801
4 1883282.9159144
5 3989720.4407436801
6 386895.04192137404

## dplyr::filter

![](http://ohi-science.org/data-science-training/img/rstudio-cheatsheet-filter.png)
La fonction filter () est utilisée pour sous-ensemble un bloc de données, en conservant toutes les lignes qui satisfont votre conditions. Pour être conservée, la ligne doit produire une valeur TRUE pour toutes les conditions. Remarque que lorsqu'une condition est évaluée à NA, la ligne sera supprimée, contrairement au sous-ensemble de base avec
[.

Fonctions de filtre utiles
Il existe de nombreuses fonctions et opérateurs utiles lors de la construction des expressions
utilisé pour filtrer les données:

 * ==, >, >= etc
 
 * &, |, !, xor()
 
 * is.na()
 
 * between(), near()

In [59]:
unique(fao_fbs$Element)

fao_fbs %>% filter(Element=="Production")

[1] Production      Import Quantity Stock Variation Export Quantity
[5] Food
Levels: Export Quantity Food Import Quantity Production Stock Variation

    ï..Domain.Code Domain            Area.Code Area    Element.Code Element
1   FBS            New Food Balances 195       Senegal 5511         Production
2   FBS            New Food Balances 195       Senegal 5511         Production
3   FBS            New Food Balances 195       Senegal 5511         Production
4   FBS            New Food Balances 195       Senegal 5511         Production
5   FBS            New Food Balances 195       Senegal 5511         Production
6   FBS            New Food Balances 195       Senegal 5511         Production
7   FBS            New Food Balances 195       Senegal 5511         Production
8   FBS            New Food Balances 195       Senegal 5511         Production
9   FBS            New Food Balances 195       Senegal 5511         Production
10  FBS            New Food Balances 195       Senegal 5511         Production
11  FBS            New Food Balances 195       Senegal 5511         Production
12  FBS            New Food Balances 195       Senegal 5511         Production
13  FBS            New Food Balances 195       Senegal 5511         Production
14  FBS            New Food Balances 195       Senegal 5511         Production
15  FBS            New Food Balances 195       Senegal 5511         Production
16  FBS            New Food Balances 195       Senegal 5511         Production
17  FBS            New Food Balances 195       Senegal 5511         Production
18  FBS            New Food Balances 195       Senegal 5511         Production
19  FBS            New Food Balances 195       Senegal 5511         Production
20  FBS            New Food Balances 195       Senegal 5511         Production
21  FBS            New Food Balances 195       Senegal 5511         Production
22  FBS            New Food Balances 195       Senegal 5511         Production
23  FBS            New Food Balances 195       Senegal 5511         Production
24  FBS            New Food Balances 195       Senegal 5511         Production
25  FBS            New Food Balances 195       Senegal 5511         Production
26  FBS            New Food Balances 195       Senegal 5511         Production
27  FBS            New Food Balances 195       Senegal 5511         Production
28  FBS            New Food Balances 195       Senegal 5511         Production
29  FBS            New Food Balances 195       Senegal 5511         Production
30  FBS            New Food Balances 195       Senegal 5511         Production
... ...            ...               ...       ...     ...          ...
405 FBS            New Food Balances 195       Senegal 5511         Production
406 FBS            New Food Balances 195       Senegal 5511         Production
407 FBS            New Food Balances 195       Senegal 5511         Production
408 FBS            New Food Balances 195       Senegal 5511         Production
409 FBS            New Food Balances 195       Senegal 5511         Production
410 FBS            New Food Balances 195       Senegal 5511         Production
411 FBS            New Food Balances 195       Senegal 5511         Production
412 FBS            New Food Balances 195       Senegal 5511         Production
413 FBS            New Food Balances 195       Senegal 5511         Production
414 FBS            New Food Balances 195       Senegal 5511         Production
415 FBS            New Food Balances 195       Senegal 5511         Production
416 FBS            New Food Balances 195       Senegal 5511         Production
417 FBS            New Food Balances 195       Senegal 5511         Production
418 FBS            New Food Balances 195       Senegal 5511         Production
419 FBS            New Food Balances 195       Senegal 5511         Production
420 FBS            New Food Balances 195       Senegal 5511         Production
421 FBS            New Food Balances 195       Senegal 5511         Production
422 FBS            New Food Balances 195       Senegal 5511         Production
423 FBS            New Food Balances 195       Senegal 5511         Production
424 FBS            New Food Balances 195       Senegal 5511         Production
425 FBS            New Food Balances 195       Senegal 5511         Production
426 FBS            New Food Balances 195       Senegal 5511         Production
427 FBS            New Food Balances 195       Senegal 5511         Production
428 FBS            New Food Balances 195       Senegal 5511         Production
429 FBS            New Food Balances 195       Senegal 5511         Production
430 FBS            New Food Balances 195       Senegal 5511         Production
431 FBS            New Food Balances 195       Senegal 5511         Production
432 FBS            New Food Balances 195       Senegal 5511         Production
433 FBS            New Food Balances 195       Senegal 5511         Production
434 FBS            New Food Balances 195       Senegal 5511         Production
    Item.Code Item                Year.Code Year Unit        Value  Flag
1   2511      Wheat and products  2014      2014 1000 tonnes   0    Im
2   2511      Wheat and products  2015      2015 1000 tonnes   0    Im
3   2511      Wheat and products  2016      2016 1000 tonnes   0    Im
4   2511      Wheat and products  2017      2017 1000 tonnes   0    Im
5   2511      Wheat and products  2018      2018 1000 tonnes   0    Im
6   2805      Rice and products   2014      2014 1000 tonnes 559    Im
7   2805      Rice and products   2015      2015 1000 tonnes 906    Im
8   2805      Rice and products   2016      2016 1000 tonnes 634    Im
9   2805      Rice and products   2017      2017 1000 tonnes 711    Im
10  2805      Rice and products   2018      2018 1000 tonnes 763    Im
11  2513      Barley and products 2014      2014 1000 tonnes   0    Im
12  2513      Barley and products 2015      2015 1000 tonnes   0    Im
13  2513      Barley and products 2016      2016 1000 tonnes   0    Im
14  2513      Barley and products 2017      2017 1000 tonnes   0    Im
15  2513      Barley and products 2018      2018 1000 tonnes   0    Im
16  2514      Maize and products  2014      2014 1000 tonnes 179    Im
17  2514      Maize and products  2015      2015 1000 tonnes 304    Im
18  2514      Maize and products  2016      2016 1000 tonnes 309    Im
19  2514      Maize and products  2017      2017 1000 tonnes 266    Im
20  2514      Maize and products  2018      2018 1000 tonnes 264    Im
21  2515      Rye and products    2014      2014 1000 tonnes   0    Im
22  2515      Rye and products    2015      2015 1000 tonnes   0    Im
23  2515      Rye and products    2016      2016 1000 tonnes   0    Im
24  2515      Rye and products    2017      2017 1000 tonnes   0    Im
25  2515      Rye and products    2018      2018 1000 tonnes   0    Im
26  2516      Oats                2014      2014 1000 tonnes   0    Im
27  2516      Oats                2015      2015 1000 tonnes   0    Im
28  2516      Oats                2016      2016 1000 tonnes   0    Im
29  2516      Oats                2017      2017 1000 tonnes   0    Im
30  2516      Oats                2018      2018 1000 tonnes   0    Im
... ...       ...                 ...       ...  ...         ...    ...
405 2763      Pelagic Fish        2014      2014 1000 tonnes 278.47 Im
406 2763      Pelagic Fish        2015      2015 1000 tonnes 304.60 Im
407 2763      Pelagic Fish        2016      2016 1000 tonnes 339.94 Im
408 2763      Pelagic Fish        2017      2017 1000 tonnes 346.63 Im
409 2763      Pelagic Fish        2018      2018 1000 tonnes 346.63 Im
410 2764      Marine Fish, Other  2014      2014 1000 tonnes  21.37 Im
411 2764      Marine Fish, Other  2015      2015 1000 tonnes   0.00 Im
412 2764      Marine Fish, Other  2016      2016 1000 tonnes   0.00 Im
413 2764      Marine Fish, Other  2017      2017 1000 tonnes   0.00 Im
414 2764      Marine Fish, Other  2018      2018 1000 tonnes   0.00 Im
415 2765      Crustaceans         2014      2014 1000 tonnes   7.56 Im
416 2765      Crustaceans         2015      2015 1000 tonnes   3.96 Im
417 2765      Crustaceans         2016      2016 1000 tonnes   6.71 Im
418 2765      Crustaceans         2017      2017 1000 tonnes   8.03 Im
419 2765      Crustaceans         2018      2018 1000 tonnes   8.03 Im
420 2766      Cephalopods         2014      2014 1000 tonnes   8.24 Im
421 2766      Cephalopods         2015      2015 1000 tonnes   8.57 Im
422 2766      Cephalopods         2016      2016 1000 tonnes  11.17 Im
423 2766      Cephalopods         2017      2017 1000 tonnes  15.88 Im
424 2766      Cephalopods         2018      2018 1000 tonnes  15.88 Im
425 2767      Molluscs, Other     2014      2014 1000 tonnes   9.45 Im
426 2767      Molluscs, Other     2015      2015 1000 tonnes  12.61 Im
427 2767      Molluscs, Other     2016      2016 1000 tonnes  11.00 Im
428 2767      Molluscs, Other     2017      2017 1000 tonnes  10.69 Im
429 2767      Molluscs, Other     2018      2018 1000 tonnes  10.69 Im
430 2775      Aquatic Plants      2014      2014 1000 tonnes   0.07 Im
431 2775      Aquatic Plants      2015      2015 1000 tonnes   0.01 Im
432 2775      Aquatic Plants      2016      2016 1000 tonnes   0.03 Im
433 2775      Aquatic Plants      2017      2017 1000 tonnes   0.03 Im
434 2775      Aquatic Plants      2018      2018 1000 tonnes   0.03 Im
    Flag.Description
1   FAO data based on imputation methodology
2   FAO data based on imputation methodology
3   FAO data based on imputation methodology
4   FAO data based on imputation methodology
5   FAO data based on imputation methodology
6   FAO data based on imputation methodology
7   FAO data based on imputation methodology
8   FAO data based on imputation methodology
9   FAO data based on imputation methodology
10  FAO data based on imputation methodology
11  FAO data based on imputation methodology
12  FAO data based on imputation methodology
13  FAO data based on imputation methodology
14  FAO data based on imputation methodology
15  FAO data based on imputation methodology
16  FAO data based on imputation methodology
17  FAO data based on imputation methodology
18  FAO data based on imputation methodology
19  FAO data based on imputation methodology
20  FAO data based on imputation methodology
21  FAO data based on imputation methodology
22  FAO data based on imputation methodology
23  FAO data based on imputation methodology
24  FAO data based on imputation methodology
25  FAO data based on imputation methodology
26  FAO data based on imputation methodology
27  FAO data based on imputation methodology
28  FAO data based on imputation methodology
29  FAO data based on imputation methodology
30  FAO data based on imputation methodology
... ...
405 FAO data based on imputation methodology
406 FAO data based on imputation methodology
407 FAO data based on imputation methodology
408 FAO data based on imputation methodology
409 FAO data based on imputation methodology
410 FAO data based on imputation methodology
411 FAO data based on imputation methodology
412 FAO data based on imputation methodology
413 FAO data based on imputation methodology
414 FAO data based on imputation methodology
415 FAO data based on imputation methodology
416 FAO data based on imputation methodology
417 FAO data based on imputation methodology
418 FAO data based on imputation methodology
419 FAO data based on imputation methodology
420 FAO data based on imputation methodology
421 FAO data based on imputation methodology
422 FAO data based on imputation methodology
423 FAO data based on imputation methodology
424 FAO data based on imputation methodology
425 FAO data based on imputation methodology
426 FAO data based on imputation methodology
427 FAO data based on imputation methodology
428 FAO data based on imputation methodology
429 FAO data based on imputation methodology
430 FAO data based on imputation methodology
431 FAO data based on imputation methodology
432 FAO data based on imputation methodology
433 FAO data based on imputation methodology
434 FAO data based on imputation methodology

In [60]:
fao_fbs %>% filter(Element %in% c("Production","Import Quantity"))

    ï..Domain.Code Domain            Area.Code Area    Element.Code
1   FBS            New Food Balances 195       Senegal 5511
2   FBS            New Food Balances 195       Senegal 5511
3   FBS            New Food Balances 195       Senegal 5511
4   FBS            New Food Balances 195       Senegal 5511
5   FBS            New Food Balances 195       Senegal 5511
6   FBS            New Food Balances 195       Senegal 5611
7   FBS            New Food Balances 195       Senegal 5611
8   FBS            New Food Balances 195       Senegal 5611
9   FBS            New Food Balances 195       Senegal 5611
10  FBS            New Food Balances 195       Senegal 5611
11  FBS            New Food Balances 195       Senegal 5511
12  FBS            New Food Balances 195       Senegal 5511
13  FBS            New Food Balances 195       Senegal 5511
14  FBS            New Food Balances 195       Senegal 5511
15  FBS            New Food Balances 195       Senegal 5511
16  FBS            New Food Balances 195       Senegal 5611
17  FBS            New Food Balances 195       Senegal 5611
18  FBS            New Food Balances 195       Senegal 5611
19  FBS            New Food Balances 195       Senegal 5611
20  FBS            New Food Balances 195       Senegal 5611
21  FBS            New Food Balances 195       Senegal 5511
22  FBS            New Food Balances 195       Senegal 5511
23  FBS            New Food Balances 195       Senegal 5511
24  FBS            New Food Balances 195       Senegal 5511
25  FBS            New Food Balances 195       Senegal 5511
26  FBS            New Food Balances 195       Senegal 5611
27  FBS            New Food Balances 195       Senegal 5611
28  FBS            New Food Balances 195       Senegal 5611
29  FBS            New Food Balances 195       Senegal 5611
30  FBS            New Food Balances 195       Senegal 5611
... ...            ...               ...       ...     ...
872 FBS            New Food Balances 195       Senegal 5611
873 FBS            New Food Balances 195       Senegal 5611
874 FBS            New Food Balances 195       Senegal 5611
875 FBS            New Food Balances 195       Senegal 5611
876 FBS            New Food Balances 195       Senegal 5611
877 FBS            New Food Balances 195       Senegal 5611
878 FBS            New Food Balances 195       Senegal 5611
879 FBS            New Food Balances 195       Senegal 5611
880 FBS            New Food Balances 195       Senegal 5611
881 FBS            New Food Balances 195       Senegal 5611
882 FBS            New Food Balances 195       Senegal 5511
883 FBS            New Food Balances 195       Senegal 5511
884 FBS            New Food Balances 195       Senegal 5511
885 FBS            New Food Balances 195       Senegal 5511
886 FBS            New Food Balances 195       Senegal 5511
887 FBS            New Food Balances 195       Senegal 5611
888 FBS            New Food Balances 195       Senegal 5611
889 FBS            New Food Balances 195       Senegal 5611
890 FBS            New Food Balances 195       Senegal 5611
891 FBS            New Food Balances 195       Senegal 5611
892 FBS            New Food Balances 195       Senegal 5611
893 FBS            New Food Balances 195       Senegal 5611
894 FBS            New Food Balances 195       Senegal 5611
895 FBS            New Food Balances 195       Senegal 5611
896 FBS            New Food Balances 195       Senegal 5611
897 FBS            New Food Balances 195       Senegal 5611
898 FBS            New Food Balances 195       Senegal 5611
899 FBS            New Food Balances 195       Senegal 5611
900 FBS            New Food Balances 195       Senegal 5611
901 FBS            New Food Balances 195       Senegal 5611
    Element         Item.Code Item                    Year.Code Year
1   Production      2511      Wheat and products      2014      2014
2   Production      2511      Wheat and products      2015      2015
3   Production      2511      Wheat and products      2016      2016
4   Production      2511      Wheat and products      2017      2017
5   Production      2511      Wheat and products      2018      2018
6   Import Quantity 2511      Wheat and products      2014      2014
7   Import Quantity 2511      Wheat and products      2015      2015
8   Import Quantity 2511      Wheat and products      2016      2016
9   Import Quantity 2511      Wheat and products      2017      2017
10  Import Quantity 2511      Wheat and products      2018      2018
11  Production      2805      Rice and products       2014      2014
12  Production      2805      Rice and products       2015      2015
13  Production      2805      Rice and products       2016      2016
14  Production      2805      Rice and products       2017      2017
15  Production      2805      Rice and products       2018      2018
16  Import Quantity 2805      Rice and products       2014      2014
17  Import Quantity 2805      Rice and products       2015      2015
18  Import Quantity 2805      Rice and products       2016      2016
19  Import Quantity 2805      Rice and products       2017      2017
20  Import Quantity 2805      Rice and products       2018      2018
21  Production      2513      Barley and products     2014      2014
22  Production      2513      Barley and products     2015      2015
23  Production      2513      Barley and products     2016      2016
24  Production      2513      Barley and products     2017      2017
25  Production      2513      Barley and products     2018      2018
26  Import Quantity 2513      Barley and products     2014      2014
27  Import Quantity 2513      Barley and products     2015      2015
28  Import Quantity 2513      Barley and products     2016      2016
29  Import Quantity 2513      Barley and products     2017      2017
30  Import Quantity 2513      Barley and products     2018      2018
... ...             ...       ...                     ...       ...
872 Import Quantity 2767      Molluscs, Other         2014      2014
873 Import Quantity 2767      Molluscs, Other         2015      2015
874 Import Quantity 2767      Molluscs, Other         2016      2016
875 Import Quantity 2767      Molluscs, Other         2017      2017
876 Import Quantity 2767      Molluscs, Other         2018      2018
877 Import Quantity 2769      Aquatic Animals, Others 2014      2014
878 Import Quantity 2769      Aquatic Animals, Others 2015      2015
879 Import Quantity 2769      Aquatic Animals, Others 2016      2016
880 Import Quantity 2769      Aquatic Animals, Others 2017      2017
881 Import Quantity 2769      Aquatic Animals, Others 2018      2018
882 Production      2775      Aquatic Plants          2014      2014
883 Production      2775      Aquatic Plants          2015      2015
884 Production      2775      Aquatic Plants          2016      2016
885 Production      2775      Aquatic Plants          2017      2017
886 Production      2775      Aquatic Plants          2018      2018
887 Import Quantity 2775      Aquatic Plants          2014      2014
888 Import Quantity 2775      Aquatic Plants          2015      2015
889 Import Quantity 2775      Aquatic Plants          2016      2016
890 Import Quantity 2775      Aquatic Plants          2017      2017
891 Import Quantity 2775      Aquatic Plants          2018      2018
892 Import Quantity 2680      Infant food             2014      2014
893 Import Quantity 2680      Infant food             2015      2015
894 Import Quantity 2680      Infant food             2016      2016
895 Import Quantity 2680      Infant food             2017      2017
896 Import Quantity 2680      Infant food             2018      2018
897 Import Quantity 2899      Miscellaneous           2014      2014
898 Import Quantity 2899      Miscellaneous           2015      2015
899 Import Quantity 2899      Miscellaneous           2016      2016
900 Import Quantity 2899      Miscellaneous           2017      2017
901 Import Quantity 2899      Miscellaneous           2018      2018
    Unit        Value Flag Flag.Description
1   1000 tonnes    0  Im   FAO data based on imputation methodology
2   1000 tonnes    0  Im   FAO data based on imputation methodology
3   1000 tonnes    0  Im   FAO data based on imputation methodology
4   1000 tonnes    0  Im   FAO data based on imputation methodology
5   1000 tonnes    0  Im   FAO data based on imputation methodology
6   1000 tonnes  589  Im   FAO data based on imputation methodology
7   1000 tonnes  624  Im   FAO data based on imputation methodology
8   1000 tonnes  640  Im   FAO data based on imputation methodology
9   1000 tonnes  683  Im   FAO data based on imputation methodology
10  1000 tonnes  679  Im   FAO data based on imputation methodology
11  1000 tonnes  559  Im   FAO data based on imputation methodology
12  1000 tonnes  906  Im   FAO data based on imputation methodology
13  1000 tonnes  634  Im   FAO data based on imputation methodology
14  1000 tonnes  711  Im   FAO data based on imputation methodology
15  1000 tonnes  763  Im   FAO data based on imputation methodology
16  1000 tonnes 1662  Im   FAO data based on imputation methodology
17  1000 tonnes 1739  Im   FAO data based on imputation methodology
18  1000 tonnes 1459  Im   FAO data based on imputation methodology
19  1000 tonnes 1764  Im   FAO data based on imputation methodology
20  1000 tonnes 1919  Im   FAO data based on imputation methodology
21  1000 tonnes    0  Im   FAO data based on imputation methodology
22  1000 tonnes    0  Im   FAO data based on imputation methodology
23  1000 tonnes    0  Im   FAO data based on imputation methodology
24  1000 tonnes    0  Im   FAO data based on imputation methodology
25  1000 tonnes    0  Im   FAO data based on imputation methodology
26  1000 tonnes    0  Im   FAO data based on imputation methodology
27  1000 tonnes   65  Im   FAO data based on imputation methodology
28  1000 tonnes    0  Im   FAO data based on imputation methodology
29  1000 tonnes  112  Im   FAO data based on imputation methodology
30  1000 tonnes  124  Im   FAO data based on imputation methodology
... ...         ...   ...  ...
872 1000 tonnes  0.07 Im   FAO data based on imputation methodology
873 1000 tonnes  0.17 Im   FAO data based on imputation methodology
874 1000 tonnes  0.12 Im   FAO data based on imputation methodology
875 1000 tonnes  0.11 Im   FAO data based on imputation methodology
876 1000 tonnes  0.11 Im   FAO data based on imputation methodology
877 1000 tonnes  0.00 Im   FAO data based on imputation methodology
878 1000 tonnes  0.01 Im   FAO data based on imputation methodology
879 1000 tonnes  0.00 Im   FAO data based on imputation methodology
880 1000 tonnes  0.03 Im   FAO data based on imputation methodology
881 1000 tonnes  0.03 Im   FAO data based on imputation methodology
882 1000 tonnes  0.07 Im   FAO data based on imputation methodology
883 1000 tonnes  0.01 Im   FAO data based on imputation methodology
884 1000 tonnes  0.03 Im   FAO data based on imputation methodology
885 1000 tonnes  0.03 Im   FAO data based on imputation methodology
886 1000 tonnes  0.03 Im   FAO data based on imputation methodology
887 1000 tonnes  0.00 Im   FAO data based on imputation methodology
888 1000 tonnes  0.00 Im   FAO data based on imputation methodology
889 1000 tonnes  0.00 Im   FAO data based on imputation methodology
890 1000 tonnes  0.00 Im   FAO data based on imputation methodology
891 1000 tonnes  0.00 Im   FAO data based on imputation methodology
892 1000 tonnes  2.00 Im   FAO data based on imputation methodology
893 1000 tonnes  2.00 Im   FAO data based on imputation methodology
894 1000 tonnes  2.00 Im   FAO data based on imputation methodology
895 1000 tonnes  2.00 Im   FAO data based on imputation methodology
896 1000 tonnes  2.00 Im   FAO data based on imputation methodology
897 1000 tonnes 33.00 Im   FAO data based on imputation methodology
898 1000 tonnes 38.00 Im   FAO data based on imputation methodology
899 1000 tonnes 48.00 Im   FAO data based on imputation methodology
900 1000 tonnes 46.00 Im   FAO data based on imputation methodology
901 1000 tonnes 46.00 Im   FAO data based on imputation methodology

In [62]:
fao_fbs %>% filter(Element=="Production" & Value>100)

    ï..Domain.Code Domain            Area.Code Area    Element.Code Element
1   FBS            New Food Balances 195       Senegal 5511         Production
2   FBS            New Food Balances 195       Senegal 5511         Production
3   FBS            New Food Balances 195       Senegal 5511         Production
4   FBS            New Food Balances 195       Senegal 5511         Production
5   FBS            New Food Balances 195       Senegal 5511         Production
6   FBS            New Food Balances 195       Senegal 5511         Production
7   FBS            New Food Balances 195       Senegal 5511         Production
8   FBS            New Food Balances 195       Senegal 5511         Production
9   FBS            New Food Balances 195       Senegal 5511         Production
10  FBS            New Food Balances 195       Senegal 5511         Production
11  FBS            New Food Balances 195       Senegal 5511         Production
12  FBS            New Food Balances 195       Senegal 5511         Production
13  FBS            New Food Balances 195       Senegal 5511         Production
14  FBS            New Food Balances 195       Senegal 5511         Production
15  FBS            New Food Balances 195       Senegal 5511         Production
16  FBS            New Food Balances 195       Senegal 5511         Production
17  FBS            New Food Balances 195       Senegal 5511         Production
18  FBS            New Food Balances 195       Senegal 5511         Production
19  FBS            New Food Balances 195       Senegal 5511         Production
20  FBS            New Food Balances 195       Senegal 5511         Production
21  FBS            New Food Balances 195       Senegal 5511         Production
22  FBS            New Food Balances 195       Senegal 5511         Production
23  FBS            New Food Balances 195       Senegal 5511         Production
24  FBS            New Food Balances 195       Senegal 5511         Production
25  FBS            New Food Balances 195       Senegal 5511         Production
26  FBS            New Food Balances 195       Senegal 5511         Production
27  FBS            New Food Balances 195       Senegal 5511         Production
28  FBS            New Food Balances 195       Senegal 5511         Production
29  FBS            New Food Balances 195       Senegal 5511         Production
30  FBS            New Food Balances 195       Senegal 5511         Production
... ...            ...               ...       ...     ...          ...
52  FBS            New Food Balances 195       Senegal 5511         Production
53  FBS            New Food Balances 195       Senegal 5511         Production
54  FBS            New Food Balances 195       Senegal 5511         Production
55  FBS            New Food Balances 195       Senegal 5511         Production
56  FBS            New Food Balances 195       Senegal 5511         Production
57  FBS            New Food Balances 195       Senegal 5511         Production
58  FBS            New Food Balances 195       Senegal 5511         Production
59  FBS            New Food Balances 195       Senegal 5511         Production
60  FBS            New Food Balances 195       Senegal 5511         Production
61  FBS            New Food Balances 195       Senegal 5511         Production
62  FBS            New Food Balances 195       Senegal 5511         Production
63  FBS            New Food Balances 195       Senegal 5511         Production
64  FBS            New Food Balances 195       Senegal 5511         Production
65  FBS            New Food Balances 195       Senegal 5511         Production
66  FBS            New Food Balances 195       Senegal 5511         Production
67  FBS            New Food Balances 195       Senegal 5511         Production
68  FBS            New Food Balances 195       Senegal 5511         Production
69  FBS            New Food Balances 195       Senegal 5511         Production
70  FBS            New Food Balances 195       Senegal 5511         Production
71  FBS            New Food Balances 195       Senegal 5511         Production
72  FBS            New Food Balances 195       Senegal 5511         Production
73  FBS            New Food Balances 195       Senegal 5511         Production
74  FBS            New Food Balances 195       Senegal 5511         Production
75  FBS            New Food Balances 195       Senegal 5511         Production
76  FBS            New Food Balances 195       Senegal 5511         Production
77  FBS            New Food Balances 195       Senegal 5511         Production
78  FBS            New Food Balances 195       Senegal 5511         Production
79  FBS            New Food Balances 195       Senegal 5511         Production
80  FBS            New Food Balances 195       Senegal 5511         Production
81  FBS            New Food Balances 195       Senegal 5511         Production
    Item.Code Item                    Year.Code Year Unit        Value  Flag
1   2805      Rice and products       2014      2014 1000 tonnes  559   Im
2   2805      Rice and products       2015      2015 1000 tonnes  906   Im
3   2805      Rice and products       2016      2016 1000 tonnes  634   Im
4   2805      Rice and products       2017      2017 1000 tonnes  711   Im
5   2805      Rice and products       2018      2018 1000 tonnes  763   Im
6   2514      Maize and products      2014      2014 1000 tonnes  179   Im
7   2514      Maize and products      2015      2015 1000 tonnes  304   Im
8   2514      Maize and products      2016      2016 1000 tonnes  309   Im
9   2514      Maize and products      2017      2017 1000 tonnes  266   Im
10  2514      Maize and products      2018      2018 1000 tonnes  264   Im
11  2517      Millet and products     2014      2014 1000 tonnes  409   Im
12  2517      Millet and products     2015      2015 1000 tonnes  750   Im
13  2517      Millet and products     2016      2016 1000 tonnes  608   Im
14  2517      Millet and products     2017      2017 1000 tonnes  569   Im
15  2517      Millet and products     2018      2018 1000 tonnes  574   Im
16  2518      Sorghum and products    2014      2014 1000 tonnes  102   Im
17  2518      Sorghum and products    2015      2015 1000 tonnes  189   Im
18  2518      Sorghum and products    2016      2016 1000 tonnes  154   Im
19  2518      Sorghum and products    2017      2017 1000 tonnes  143   Im
20  2518      Sorghum and products    2018      2018 1000 tonnes  143   Im
21  2532      Cassava and products    2014      2014 1000 tonnes  257   Im
22  2532      Cassava and products    2015      2015 1000 tonnes  440   Im
23  2532      Cassava and products    2016      2016 1000 tonnes  275   Im
24  2532      Cassava and products    2017      2017 1000 tonnes  338   Im
25  2532      Cassava and products    2018      2018 1000 tonnes  314   Im
26  2531      Potatoes and products   2017      2017 1000 tonnes  119   Im
27  2536      Sugar cane              2014      2014 1000 tonnes  955   Im
28  2536      Sugar cane              2015      2015 1000 tonnes  996   Im
29  2536      Sugar cane              2016      2016 1000 tonnes 1078   Im
30  2536      Sugar cane              2017      2017 1000 tonnes 1078   Im
... ...       ...                     ...       ...  ...         ...    ...
52  2601      Tomatoes and products   2015      2015 1000 tonnes 140.00 Im
53  2601      Tomatoes and products   2016      2016 1000 tonnes 102.00 Im
54  2601      Tomatoes and products   2017      2017 1000 tonnes 138.00 Im
55  2601      Tomatoes and products   2018      2018 1000 tonnes 153.00 Im
56  2602      Onions                  2014      2014 1000 tonnes 245.00 Im
57  2602      Onions                  2015      2015 1000 tonnes 368.00 Im
58  2602      Onions                  2016      2016 1000 tonnes 393.00 Im
59  2602      Onions                  2017      2017 1000 tonnes 400.00 Im
60  2602      Onions                  2018      2018 1000 tonnes 387.00 Im
61  2605      Vegetables, Other       2014      2014 1000 tonnes 413.00 Im
62  2605      Vegetables, Other       2015      2015 1000 tonnes 444.00 Im
63  2605      Vegetables, Other       2016      2016 1000 tonnes 432.00 Im
64  2605      Vegetables, Other       2017      2017 1000 tonnes 451.00 Im
65  2605      Vegetables, Other       2018      2018 1000 tonnes 431.00 Im
66  2625      Fruits, Other           2014      2014 1000 tonnes 182.00 Im
67  2625      Fruits, Other           2015      2015 1000 tonnes 173.00 Im
68  2625      Fruits, Other           2016      2016 1000 tonnes 179.00 Im
69  2625      Fruits, Other           2017      2017 1000 tonnes 181.00 Im
70  2625      Fruits, Other           2018      2018 1000 tonnes 182.00 Im
71  2848      Milk - Excluding Butter 2014      2014 1000 tonnes 145.00 Im
72  2848      Milk - Excluding Butter 2015      2015 1000 tonnes 146.00 Im
73  2848      Milk - Excluding Butter 2016      2016 1000 tonnes 147.00 Im
74  2848      Milk - Excluding Butter 2017      2017 1000 tonnes 148.00 Im
75  2848      Milk - Excluding Butter 2018      2018 1000 tonnes 150.00 Im
76  2762      Demersal Fish           2014      2014 1000 tonnes 102.92 Im
77  2763      Pelagic Fish            2014      2014 1000 tonnes 278.47 Im
78  2763      Pelagic Fish            2015      2015 1000 tonnes 304.60 Im
79  2763      Pelagic Fish            2016      2016 1000 tonnes 339.94 Im
80  2763      Pelagic Fish            2017      2017 1000 tonnes 346.63 Im
81  2763      Pelagic Fish            2018      2018 1000 tonnes 346.63 Im
    Flag.Description
1   FAO data based on imputation methodology
2   FAO data based on imputation methodology
3   FAO data based on imputation methodology
4   FAO data based on imputation methodology
5   FAO data based on imputation methodology
6   FAO data based on imputation methodology
7   FAO data based on imputation methodology
8   FAO data based on imputation methodology
9   FAO data based on imputation methodology
10  FAO data based on imputation methodology
11  FAO data based on imputation methodology
12  FAO data based on imputation methodology
13  FAO data based on imputation methodology
14  FAO data based on imputation methodology
15  FAO data based on imputation methodology
16  FAO data based on imputation methodology
17  FAO data based on imputation methodology
18  FAO data based on imputation methodology
19  FAO data based on imputation methodology
20  FAO data based on imputation methodology
21  FAO data based on imputation methodology
22  FAO data based on imputation methodology
23  FAO data based on imputation methodology
24  FAO data based on imputation methodology
25  FAO data based on imputation methodology
26  FAO data based on imputation methodology
27  FAO data based on imputation methodology
28  FAO data based on imputation methodology
29  FAO data based on imputation methodology
30  FAO data based on imputation methodology
... ...
52  FAO data based on imputation methodology
53  FAO data based on imputation methodology
54  FAO data based on imputation methodology
55  FAO data based on imputation methodology
56  FAO data based on imputation methodology
57  FAO data based on imputation methodology
58  FAO data based on imputation methodology
59  FAO data based on imputation methodology
60  FAO data based on imputation methodology
61  FAO data based on imputation methodology
62  FAO data based on imputation methodology
63  FAO data based on imputation methodology
64  FAO data based on imputation methodology
65  FAO data based on imputation methodology
66  FAO data based on imputation methodology
67  FAO data based on imputation methodology
68  FAO data based on imputation methodology
69  FAO data based on imputation methodology
70  FAO data based on imputation methodology
71  FAO data based on imputation methodology
72  FAO data based on imputation methodology
73  FAO data based on imputation methodology
74  FAO data based on imputation methodology
75  FAO data based on imputation methodology
76  FAO data based on imputation methodology
77  FAO data based on imputation methodology
78  FAO data based on imputation methodology
79  FAO data based on imputation methodology
80  FAO data based on imputation methodology
81  FAO data based on imputation methodology

In [66]:
unique(fao_fbs$Element.Code)
fao_fbs %>% filter(Value>100 & Element.Code==5511)

[1] 5511 5611 5072 5911 5142

    ï..Domain.Code Domain            Area.Code Area    Element.Code Element
1   FBS            New Food Balances 195       Senegal 5511         Production
2   FBS            New Food Balances 195       Senegal 5511         Production
3   FBS            New Food Balances 195       Senegal 5511         Production
4   FBS            New Food Balances 195       Senegal 5511         Production
5   FBS            New Food Balances 195       Senegal 5511         Production
6   FBS            New Food Balances 195       Senegal 5511         Production
7   FBS            New Food Balances 195       Senegal 5511         Production
8   FBS            New Food Balances 195       Senegal 5511         Production
9   FBS            New Food Balances 195       Senegal 5511         Production
10  FBS            New Food Balances 195       Senegal 5511         Production
11  FBS            New Food Balances 195       Senegal 5511         Production
12  FBS            New Food Balances 195       Senegal 5511         Production
13  FBS            New Food Balances 195       Senegal 5511         Production
14  FBS            New Food Balances 195       Senegal 5511         Production
15  FBS            New Food Balances 195       Senegal 5511         Production
16  FBS            New Food Balances 195       Senegal 5511         Production
17  FBS            New Food Balances 195       Senegal 5511         Production
18  FBS            New Food Balances 195       Senegal 5511         Production
19  FBS            New Food Balances 195       Senegal 5511         Production
20  FBS            New Food Balances 195       Senegal 5511         Production
21  FBS            New Food Balances 195       Senegal 5511         Production
22  FBS            New Food Balances 195       Senegal 5511         Production
23  FBS            New Food Balances 195       Senegal 5511         Production
24  FBS            New Food Balances 195       Senegal 5511         Production
25  FBS            New Food Balances 195       Senegal 5511         Production
26  FBS            New Food Balances 195       Senegal 5511         Production
27  FBS            New Food Balances 195       Senegal 5511         Production
28  FBS            New Food Balances 195       Senegal 5511         Production
29  FBS            New Food Balances 195       Senegal 5511         Production
30  FBS            New Food Balances 195       Senegal 5511         Production
... ...            ...               ...       ...     ...          ...
52  FBS            New Food Balances 195       Senegal 5511         Production
53  FBS            New Food Balances 195       Senegal 5511         Production
54  FBS            New Food Balances 195       Senegal 5511         Production
55  FBS            New Food Balances 195       Senegal 5511         Production
56  FBS            New Food Balances 195       Senegal 5511         Production
57  FBS            New Food Balances 195       Senegal 5511         Production
58  FBS            New Food Balances 195       Senegal 5511         Production
59  FBS            New Food Balances 195       Senegal 5511         Production
60  FBS            New Food Balances 195       Senegal 5511         Production
61  FBS            New Food Balances 195       Senegal 5511         Production
62  FBS            New Food Balances 195       Senegal 5511         Production
63  FBS            New Food Balances 195       Senegal 5511         Production
64  FBS            New Food Balances 195       Senegal 5511         Production
65  FBS            New Food Balances 195       Senegal 5511         Production
66  FBS            New Food Balances 195       Senegal 5511         Production
67  FBS            New Food Balances 195       Senegal 5511         Production
68  FBS            New Food Balances 195       Senegal 5511         Production
69  FBS            New Food Balances 195       Senegal 5511         Production
70  FBS            New Food Balances 195       Senegal 5511         Production
71  FBS            New Food Balances 195       Senegal 5511         Production
72  FBS            New Food Balances 195       Senegal 5511         Production
73  FBS            New Food Balances 195       Senegal 5511         Production
74  FBS            New Food Balances 195       Senegal 5511         Production
75  FBS            New Food Balances 195       Senegal 5511         Production
76  FBS            New Food Balances 195       Senegal 5511         Production
77  FBS            New Food Balances 195       Senegal 5511         Production
78  FBS            New Food Balances 195       Senegal 5511         Production
79  FBS            New Food Balances 195       Senegal 5511         Production
80  FBS            New Food Balances 195       Senegal 5511         Production
81  FBS            New Food Balances 195       Senegal 5511         Production
    Item.Code Item                    Year.Code Year Unit        Value  Flag
1   2805      Rice and products       2014      2014 1000 tonnes  559   Im
2   2805      Rice and products       2015      2015 1000 tonnes  906   Im
3   2805      Rice and products       2016      2016 1000 tonnes  634   Im
4   2805      Rice and products       2017      2017 1000 tonnes  711   Im
5   2805      Rice and products       2018      2018 1000 tonnes  763   Im
6   2514      Maize and products      2014      2014 1000 tonnes  179   Im
7   2514      Maize and products      2015      2015 1000 tonnes  304   Im
8   2514      Maize and products      2016      2016 1000 tonnes  309   Im
9   2514      Maize and products      2017      2017 1000 tonnes  266   Im
10  2514      Maize and products      2018      2018 1000 tonnes  264   Im
11  2517      Millet and products     2014      2014 1000 tonnes  409   Im
12  2517      Millet and products     2015      2015 1000 tonnes  750   Im
13  2517      Millet and products     2016      2016 1000 tonnes  608   Im
14  2517      Millet and products     2017      2017 1000 tonnes  569   Im
15  2517      Millet and products     2018      2018 1000 tonnes  574   Im
16  2518      Sorghum and products    2014      2014 1000 tonnes  102   Im
17  2518      Sorghum and products    2015      2015 1000 tonnes  189   Im
18  2518      Sorghum and products    2016      2016 1000 tonnes  154   Im
19  2518      Sorghum and products    2017      2017 1000 tonnes  143   Im
20  2518      Sorghum and products    2018      2018 1000 tonnes  143   Im
21  2532      Cassava and products    2014      2014 1000 tonnes  257   Im
22  2532      Cassava and products    2015      2015 1000 tonnes  440   Im
23  2532      Cassava and products    2016      2016 1000 tonnes  275   Im
24  2532      Cassava and products    2017      2017 1000 tonnes  338   Im
25  2532      Cassava and products    2018      2018 1000 tonnes  314   Im
26  2531      Potatoes and products   2017      2017 1000 tonnes  119   Im
27  2536      Sugar cane              2014      2014 1000 tonnes  955   Im
28  2536      Sugar cane              2015      2015 1000 tonnes  996   Im
29  2536      Sugar cane              2016      2016 1000 tonnes 1078   Im
30  2536      Sugar cane              2017      2017 1000 tonnes 1078   Im
... ...       ...                     ...       ...  ...         ...    ...
52  2601      Tomatoes and products   2015      2015 1000 tonnes 140.00 Im
53  2601      Tomatoes and products   2016      2016 1000 tonnes 102.00 Im
54  2601      Tomatoes and products   2017      2017 1000 tonnes 138.00 Im
55  2601      Tomatoes and products   2018      2018 1000 tonnes 153.00 Im
56  2602      Onions                  2014      2014 1000 tonnes 245.00 Im
57  2602      Onions                  2015      2015 1000 tonnes 368.00 Im
58  2602      Onions                  2016      2016 1000 tonnes 393.00 Im
59  2602      Onions                  2017      2017 1000 tonnes 400.00 Im
60  2602      Onions                  2018      2018 1000 tonnes 387.00 Im
61  2605      Vegetables, Other       2014      2014 1000 tonnes 413.00 Im
62  2605      Vegetables, Other       2015      2015 1000 tonnes 444.00 Im
63  2605      Vegetables, Other       2016      2016 1000 tonnes 432.00 Im
64  2605      Vegetables, Other       2017      2017 1000 tonnes 451.00 Im
65  2605      Vegetables, Other       2018      2018 1000 tonnes 431.00 Im
66  2625      Fruits, Other           2014      2014 1000 tonnes 182.00 Im
67  2625      Fruits, Other           2015      2015 1000 tonnes 173.00 Im
68  2625      Fruits, Other           2016      2016 1000 tonnes 179.00 Im
69  2625      Fruits, Other           2017      2017 1000 tonnes 181.00 Im
70  2625      Fruits, Other           2018      2018 1000 tonnes 182.00 Im
71  2848      Milk - Excluding Butter 2014      2014 1000 tonnes 145.00 Im
72  2848      Milk - Excluding Butter 2015      2015 1000 tonnes 146.00 Im
73  2848      Milk - Excluding Butter 2016      2016 1000 tonnes 147.00 Im
74  2848      Milk - Excluding Butter 2017      2017 1000 tonnes 148.00 Im
75  2848      Milk - Excluding Butter 2018      2018 1000 tonnes 150.00 Im
76  2762      Demersal Fish           2014      2014 1000 tonnes 102.92 Im
77  2763      Pelagic Fish            2014      2014 1000 tonnes 278.47 Im
78  2763      Pelagic Fish            2015      2015 1000 tonnes 304.60 Im
79  2763      Pelagic Fish            2016      2016 1000 tonnes 339.94 Im
80  2763      Pelagic Fish            2017      2017 1000 tonnes 346.63 Im
81  2763      Pelagic Fish            2018      2018 1000 tonnes 346.63 Im
    Flag.Description
1   FAO data based on imputation methodology
2   FAO data based on imputation methodology
3   FAO data based on imputation methodology
4   FAO data based on imputation methodology
5   FAO data based on imputation methodology
6   FAO data based on imputation methodology
7   FAO data based on imputation methodology
8   FAO data based on imputation methodology
9   FAO data based on imputation methodology
10  FAO data based on imputation methodology
11  FAO data based on imputation methodology
12  FAO data based on imputation methodology
13  FAO data based on imputation methodology
14  FAO data based on imputation methodology
15  FAO data based on imputation methodology
16  FAO data based on imputation methodology
17  FAO data based on imputation methodology
18  FAO data based on imputation methodology
19  FAO data based on imputation methodology
20  FAO data based on imputation methodology
21  FAO data based on imputation methodology
22  FAO data based on imputation methodology
23  FAO data based on imputation methodology
24  FAO data based on imputation methodology
25  FAO data based on imputation methodology
26  FAO data based on imputation methodology
27  FAO data based on imputation methodology
28  FAO data based on imputation methodology
29  FAO data based on imputation methodology
30  FAO data based on imputation methodology
... ...
52  FAO data based on imputation methodology
53  FAO data based on imputation methodology
54  FAO data based on imputation methodology
55  FAO data based on imputation methodology
56  FAO data based on imputation methodology
57  FAO data based on imputation methodology
58  FAO data based on imputation methodology
59  FAO data based on imputation methodology
60  FAO data based on imputation methodology
61  FAO data based on imputation methodology
62  FAO data based on imputation methodology
63  FAO data based on imputation methodology
64  FAO data based on imputation methodology
65  FAO data based on imputation methodology
66  FAO data based on imputation methodology
67  FAO data based on imputation methodology
68  FAO data based on imputation methodology
69  FAO data based on imputation methodology
70  FAO data based on imputation methodology
71  FAO data based on imputation methodology
72  FAO data based on imputation methodology
73  FAO data based on imputation methodology
74  FAO data based on imputation methodology
75  FAO data based on imputation methodology
76  FAO data based on imputation methodology
77  FAO data based on imputation methodology
78  FAO data based on imputation methodology
79  FAO data based on imputation methodology
80  FAO data based on imputation methodology
81  FAO data based on imputation methodology

In [69]:
donnee_bm %>% filter(!is.na(`2020`))

   Country Name Country Code
1  Sénégal      SEN
2  Sénégal      SEN
3  Sénégal      SEN
4  Sénégal      SEN
5  Sénégal      SEN
6  Sénégal      SEN
7  Sénégal      SEN
8  Sénégal      SEN
9  Sénégal      SEN
10 Sénégal      SEN
11 Sénégal      SEN
12 Sénégal      SEN
13 Sénégal      SEN
14 Sénégal      SEN
15 Sénégal      SEN
16 Sénégal      SEN
17 Sénégal      SEN
18 Sénégal      SEN
19 Sénégal      SEN
20 Sénégal      SEN
21 Sénégal      SEN
22 Sénégal      SEN
23 Sénégal      SEN
24 Sénégal      SEN
25 Sénégal      SEN
26 Sénégal      SEN
27 Sénégal      SEN
28 Sénégal      SEN
29 Sénégal      SEN
30 Sénégal      SEN
31 Sénégal      SEN
32 Sénégal      SEN
33 Sénégal      SEN
34 Sénégal      SEN
35 Sénégal      SEN
36 Sénégal      SEN
37 Sénégal      SEN
38 Sénégal      SEN
39 Sénégal      SEN
40 Sénégal      SEN
41 Sénégal      SEN
42 Sénégal      SEN
43 Sénégal      SEN
44 Sénégal      SEN
45 Sénégal      SEN
46 Sénégal      SEN
47 Sénégal      SEN
48 Sénégal      SEN
49 Sénégal      SEN
50 Sénégal      SEN
51 Sénégal      SEN
52 Sénégal      SEN
53 Sénégal      SEN
54 Sénégal      SEN
55 Sénégal      SEN
   Indicator Name
1  Chômage, total (% de la population) (estimation modélisée OIT)
2  Taux de participation à la population active, total (% du total de la population âgée de 15 ans et plus) (estimation modélisée OIT)
3  Taux de participation à la population active, femmes (% de la population féminine de 15 à 64 ans) (estimation modélisée OIT)
4  Travailleurs salariés, hommes (% de la population masculine en emploi)
5  Chefs d’entreprise, hommes (% de la population masculine en emploi)
6  Risque de de dépenses appauvrissantes en cas de recours nécessaire à la chirurgie (% de la pop. à risque)
7  Proportion de sièges occupés par des femmes dans les parlements nationaux (%)
8  Chômage, hommes (% de la population active masculine) (estimation modélisée OIT)
9  Chômage, total des jeunes (% de la population active âgée de 15 à 24 ans) (estimation modélisée OIT)
10 Taux de participation à la population active, hommes (% de la population masculine âgée de 15 ans et plus) (estimation modélisée OIT)
11 Emplois vulnérables, total (% des emplois)
12 Ratio emplois/population de personnes âgées de 15 à 24 ans, total (%) (estimation modélisée OIT)
13 Éducation secondaire, durée (années)
14 Population active, femmes (% de la population active)
15 Travailleurs familiaux (% de l’emploi total)
16 Ratio emploi-population, personnes âgées de 15 ans et plus, femmes (%) (estimation modélisée OIT)
17 Employés, agriculture, hommes (% d’emploi des hommes)
18 Taux de participation à la population active, total (% de la population totale de 15 à 64 ans) (estimation modélisée OIT)
19 Travailleurs indépendants, femmes (% de la population féminine en emploi)
20 Travailleurs familiaux, hommes (% de l’emploi masculin)
21 Employées, agriculture, femmes (% d’emploi des femmes)
22 Éducation primaire, durée (années)
23 Taux de participation à la population active, hommes (% de la population masculine de 15 à 24 ans) (estimation modélisée OIT)
24 Emplois vulnérables, hommes (% des emplois chez les hommes)
25 Chômage, femmes (% de la population active féminine) (estimation modélisée OIT)
26 Chômage, jeunes hommes (% de la population active masculine de 15 à 24 ans) (estimation modélisée OIT)
27 Rapport femmes/hommes dans le taux de participation à la population active (%) (estimation modélisée OIT)
28 Emplois vulnérables, femmes (% des emplois chez les femmes)
29 Ratio emplois/population d’hommes âgés de 15 à 24 ans (%) (estimation modélisée OIT)
30 Population active, total
31 Employées, services, femmes (% d’emploi des femmes)
32 Emplois dans l’agriculture (% du total des emplois)
33 Taux de participation à la population active, femmes (% de la population féminine de 15 à 24 ans) (estimation modélisée OIT)
34 Emplois dans l’industrie (% du total des emplois)
35 Ratio emploi-population, personnes âgées de 15 ans et plus, total (%) (estimation modélisée OIT)
36 Travailleurs indépendants, hommes (% de la population masculine en emploi)
37 Taux de participation à la population active des 15-24 ans, total (%) (estimation modélisée OIT)
38 Travailleurs salariés, femmes (% de la population féminine en emploi)
39 Chefs d’entreprise, femmes (% de la population féminine en emploi)
40 Risque de de dépenses catastrophiques en cas de recours nécessaire à la chirurgie (% de la pop. à risque)
41 Âge de début de l’école primaire (années)
42 Travailleurs indépendants (% de la population en emploi)
43 Employés, services, hommes (% d’emploi des hommes)
44 Employées, industrie, femmes (% d’emploi des femmes)
45 Ratio emploi-population, personnes âgées de 15 ans et plus, hommes (%) (estimation modélisée OIT)
46 Taux de participation à la population active, hommes (% de la population masculine de 15 à 64 ans) (estimation modélisée OIT)
47 Travailleurs salariés (% de la population en emploi)
48 Chefs d’entreprise (% de la population en emploi)
49 Âge de début de l’école secondaire (années)
50 Chômage, jeunes femmes (% de la population active féminine de 15 à 24 ans) (estimation modélisée OIT)
51 Taux de participation à la population active, femmes (% de la population féminine âgée de 15 ans et plus) (estimation modélisée OIT)
52 Emplois dans les services (% du total des emplois)
53 Employés, industrie, hommes (% d’emploi des hommes)
54 Ratio emplois/population de femmes âgées de 15 à 24 ans (%) (estimation modélisée OIT)
55 Travailleurs familiaux, femmes (% de l’emploi féminin)
   Indicator Code         1960 1961 1962 1963 1964 1965 ... 2011
1  SL.UEM.TOTL.ZS         NA   NA   NA   NA   NA   NA   ...      10.36000
2  SL.TLF.CACT.ZS         NA   NA   NA   NA   NA   NA   ...      47.95900
3  SL.TLF.ACTI.FE.ZS      NA   NA   NA   NA   NA   NA   ...      35.63100
4  SL.EMP.WORK.MA.ZS      NA   NA   NA   NA   NA   NA   ...      33.86700
5  SL.EMP.MPYR.MA.ZS      NA   NA   NA   NA   NA   NA   ...       1.06400
6  SH.SGR.IRSK.ZS         NA   NA   NA   NA   NA   NA   ...      32.90000
7  SG.GEN.PARL.ZS         NA   NA   NA   NA   NA   NA   ...      22.66667
8  SL.UEM.TOTL.MA.ZS      NA   NA   NA   NA   NA   NA   ...       8.20600
9  SL.UEM.1524.ZS         NA   NA   NA   NA   NA   NA   ...      12.70200
10 SL.TLF.CACT.MA.ZS      NA   NA   NA   NA   NA   NA   ...      63.15300
11 SL.EMP.VULN.ZS         NA   NA   NA   NA   NA   NA   ...      69.55700
12 SL.EMP.1524.SP.ZS      NA   NA   NA   NA   NA   NA   ...      29.43600
13 SE.SEC.DURS            NA   NA   NA   NA   NA   NA   ...       7.00000
14 SL.TLF.TOTL.FE.ZS      NA   NA   NA   NA   NA   NA   ...      37.86203
15 SL.FAM.WORK.ZS         NA   NA   NA   NA   NA   NA   ...      24.30100
16 SL.EMP.TOTL.SP.FE.ZS   NA   NA   NA   NA   NA   NA   ...      29.60600
17 SL.AGR.EMPL.MA.ZS      NA   NA   NA   NA   NA   NA   ...      39.58800
18 SL.TLF.ACTI.ZS         NA   NA   NA   NA   NA   NA   ...      49.55000
19 SL.EMP.SELF.FE.ZS      NA   NA   NA   NA   NA   NA   ...      77.73200
20 SL.FAM.WORK.MA.ZS      NA   NA   NA   NA   NA   NA   ...      22.11400
21 SL.AGR.EMPL.FE.ZS      NA   NA   NA   NA   NA   NA   ...      33.63700
22 SE.PRM.DURS            NA   NA   NA   NA   NA   NA   ...       6.00000
23 SL.TLF.ACTI.1524.MA.ZS NA   NA   NA   NA   NA   NA   ...      43.36900
24 SL.EMP.VULN.MA.ZS      NA   NA   NA   NA   NA   NA   ...      65.06800
25 SL.UEM.TOTL.FE.ZS      NA   NA   NA   NA   NA   NA   ...      13.89500
26 SL.UEM.1524.MA.ZS      NA   NA   NA   NA   NA   NA   ...       8.72000
27 SL.TLF.CACT.FM.ZS      NA   NA   NA   NA   NA   NA   ...      54.44397
28 SL.EMP.VULN.FE.ZS      NA   NA   NA   NA   NA   NA   ...      77.41100
29 SL.EMP.1524.SP.MA.ZS   NA   NA   NA   NA   NA   NA   ...      39.58700
30 SL.TLF.TOTL.IN         NA   NA   NA   NA   NA   NA   ... 3529008.00000
31 SL.SRV.EMPL.FE.ZS      NA   NA   NA   NA   NA   NA   ...      60.13800
32 SL.AGR.EMPL.ZS         NA   NA   NA   NA   NA   NA   ...      37.42300
33 SL.TLF.ACTI.1524.FE.ZS NA   NA   NA   NA   NA   NA   ...      24.15200
34 SL.IND.EMPL.ZS         NA   NA   NA   NA   NA   NA   ...      12.72900
35 SL.EMP.TOTL.SP.ZS      NA   NA   NA   NA   NA   NA   ...      42.99100
36 SL.EMP.SELF.MA.ZS      NA   NA   NA   NA   NA   NA   ...      66.13300
37 SL.TLF.ACTI.1524.ZS    NA   NA   NA   NA   NA   NA   ...      33.71900
38 SL.EMP.WORK.FE.ZS      NA   NA   NA   NA   NA   NA   ...      22.26800
39 SL.EMP.MPYR.FE.ZS      NA   NA   NA   NA   NA   NA   ...       0.32100
40 SH.SGR.CRSK.ZS         NA   NA   NA   NA   NA   NA   ...      42.60000
41 SE.PRM.AGES            NA   NA   NA   NA   NA   NA   ...       6.00000
42 SL.EMP.SELF.ZS         NA   NA   NA   NA   NA   NA   ...      70.35100
43 SL.SRV.EMPL.MA.ZS      NA   NA   NA   NA   NA   NA   ...      43.96600
44 SL.IND.EMPL.FE.ZS      NA   NA   NA   NA   NA   NA   ...       6.22500
45 SL.EMP.TOTL.SP.MA.ZS   NA   NA   NA   NA   NA   NA   ...      57.97100
46 SL.TLF.ACTI.MA.ZS      NA   NA   NA   NA   NA   NA   ...      65.00400
47 SL.EMP.WORK.ZS         NA   NA   NA   NA   NA   NA   ...      29.64900
48 SL.EMP.MPYR.ZS         NA   NA   NA   NA   NA   NA   ...       0.79400
49 SE.SEC.AGES            NA   NA   NA   NA   NA   NA   ...      12.00000
50 SL.UEM.1524.FE.ZS      NA   NA   NA   NA   NA   NA   ...      19.79100
51 SL.TLF.CACT.FE.ZS      NA   NA   NA   NA   NA   NA   ...      34.38300
52 SL.SRV.EMPL.ZS         NA   NA   NA   NA   NA   NA   ...      49.84800
53 SL.IND.EMPL.MA.ZS      NA   NA   NA   NA   NA   NA   ...      16.44600
54 SL.EMP.1524.SP.FE.ZS   NA   NA   NA   NA   NA   NA   ...      19.37200
55 SL.FAM.WORK.FE.ZS      NA   NA   NA   NA   NA   NA   ...      28.12700
   2012          2013          2014          2015          2016
1        9.42700       8.54200       7.61100       6.75700       6.70600
2       47.39500      46.82800      46.24900      45.66400      45.67800
3       35.71300      35.79400      35.87500      35.95700      36.04500
4       34.94300      35.93000      37.07300      38.20100      38.46600
5        1.08100       1.09100       1.10500       1.11800       1.12200
6       31.70000      32.60000      32.90000      31.00000      30.80000
7       42.66667      42.66667      43.33333      42.66667      42.66667
8        7.78200       7.42500       6.87500       6.39000       6.33800
9       11.45200      10.37600       9.11200       8.02200       7.95900
10      61.89000      60.61500      59.30900      57.98600      57.90400
11      68.62600      67.76300      66.74900      65.72500      65.47200
12      28.75800      28.00700      27.30300      26.54000      26.44900
13       7.00000       7.00000       7.00000       7.00000       7.00000
14      38.43182      39.01105      39.60186      40.19988      40.24051
15      24.23000      24.24200      24.09100      23.93200      23.57200
16      30.30600      30.98900      31.59700      32.16200      32.25300
17      38.79800      38.15300      37.18400      36.43300      35.64700
18      48.94700      48.33600      47.72300      47.10700      47.13000
19      76.78500      75.85100      74.81700      73.73500      73.49300
20      21.76700      21.58200      21.16400      20.80800      20.51200
21      32.37700      31.27200      29.89300      28.67500      27.63800
22       6.00000       6.00000       6.00000       6.00000       6.00000
23      41.15300      38.95500      36.78600      34.65700      34.49000
24      63.97600      62.98000      61.82200      60.68100      60.41200
25      12.06400      10.28900       8.73400       7.30400       7.25100
26       8.44700       8.27300       7.78500       7.36900       7.30900
27      55.68590      56.98919      58.37394      59.83685      60.05457
28      76.43800      75.48000      74.41600      73.30400      73.06100
29      37.67700      35.73200      33.92200      32.10300      31.96900
30 3585357.00000 3643629.00000 3702672.00000 3763014.00000 3877928.00000
31      61.49700      62.74700      64.21700      65.57400      66.67900
32      36.40200      35.52000      34.33100      33.33300      32.44300
33      23.88400      23.61700      23.35100      23.08800      23.00000
34      12.79900      12.77700      12.95400      12.99200      13.11300
35      42.92700      42.82800      42.72900      42.57900      42.61500
36      65.05700      64.07000      62.92700      61.79900      61.53400
37      32.47700      31.24900      30.04100      28.85500      28.73700
38      23.21500      24.14900      25.18300      26.26500      26.50700
39       0.34700       0.37100       0.40100       0.43100       0.43300
40      42.00000      46.00000      41.20000      40.90000      39.80000
41       6.00000       6.00000       6.00000       6.00000       6.00000
42      69.43300      68.57800      67.57800      66.56900      66.31800
43      44.43200      44.85800      45.32300      45.75400      46.28500
44       6.12600       5.98100       5.89000       5.75100       5.68300
45      57.07400      56.11400      55.23200      54.28100      54.23400
46      63.65600      62.28800      60.90400      59.50600      59.42700
47      30.56700      31.42200      32.42200      33.43100      33.68200
48       0.80700       0.81500       0.83000       0.84400       0.84600
49      12.00000      12.00000      12.00000      12.00000      12.00000
50      16.58000      13.81300      11.18600       8.99800       8.93000
51      34.46400      34.54400      34.62100      34.69700      34.77400
52      50.79900      51.70300      52.71400      53.67500      54.44400
53      16.77000      16.98900      17.49400      17.81300      18.06700
54      19.92400      20.35400      20.73900      21.01000      20.94600
55      28.36700      28.53400      28.64600      28.62600      28.16200
   2017          2018          2019          2020
1        6.61500       6.52700       6.60400       6.67600
2       45.67100      45.65700      45.68400      45.69900
3       36.15400      36.28400      36.36100      36.42600
4       38.77500      39.08200      39.33100      39.62400
5        1.12700       1.13300       1.13700       1.14300
6       30.60000      29.00000      28.80000      27.70000
7       41.81818      41.81818      41.81818      43.03030
8        6.23000       6.15800       6.03400       5.93100
9        7.82400       7.73100       8.20800       8.61400
10      57.75300      57.56200      57.51400      57.45000
11      65.18000      64.88900      64.62800      64.32900
12      26.32200      26.12900      25.79800      25.48200
13       7.00000       7.00000       7.00000       7.00000
14      40.31017      40.40130      40.39732      40.39662
15      23.16900      22.76800      22.40500      21.99900
16      32.36400      32.50900      32.43800      32.37400
17      34.84200      34.07000      33.45500      32.85900
18      47.13500      47.13400      47.16800      47.18600
19      73.21800      72.93100      72.70100      72.44300
20      20.16600      19.83900      19.56000      19.22100
21      26.60900      25.69300      24.94000      24.26100
22       6.00000       6.00000       6.00000       6.00000
23      34.23900      33.91000      33.61900      33.31600
24      60.09900      59.78600      59.53300      59.23300
25       7.18500       7.07200       7.44600       7.77400
26       7.17100       7.09200       7.13300       7.23000
27      60.37609      60.77447      60.93821      61.10183
28      72.78300      72.49300      72.26100      72.00000
29      31.78400      31.50500      31.22100      30.90700
30 3997403.00000 4122004.00000 4255475.00000 4392588.00000
31      67.76900      68.73100      69.54100      70.26100
32      31.54300      30.70500      30.04600      29.42700
33      22.87100      22.70700      22.55600      22.40100
34      13.25300      13.40200      13.50400      13.62800
35      42.65000      42.67600      42.66700      42.64800
36      61.22500      60.91800      60.66900      60.37600
37      28.55600      28.31800      28.10500      27.88400
38      26.78200      27.06900      27.29900      27.55700
39       0.43600       0.43900       0.44100       0.44400
40      41.70000      39.60000      37.70000      37.40000
41       6.00000       6.00000       6.00000       6.00000
42      66.03000      65.74300      65.48600      65.19300
43      46.80500      47.27400      47.71000      48.09800
44       5.62300       5.57500       5.51900       5.47800
45      54.15500      54.01800      54.04400      54.04300
46      59.28100      59.09300      59.03900      58.96400
47      33.97000      34.25700      34.51400      34.80700
48       0.85000       0.85400       0.85800       0.86400
49      12.00000      12.00000      12.00000      12.00000
50       8.80300       8.68800       9.82100      10.69300
51      34.86900      34.98300      35.04800      35.10300
52      55.20400      55.89200      56.45000      56.94500
53      18.35300      18.65700      18.83500      19.04300
54      20.85800      20.73500      20.34100      20.00600
55      27.66200      27.13200      26.66800      26.18100

In [70]:
donnee_bm %>% select(`Indicator Name`,`Indicator Code`,`2020`) %>% filter(!is.na(`2020`))

   Indicator Name
1  Chômage, total (% de la population) (estimation modélisée OIT)
2  Taux de participation à la population active, total (% du total de la population âgée de 15 ans et plus) (estimation modélisée OIT)
3  Taux de participation à la population active, femmes (% de la population féminine de 15 à 64 ans) (estimation modélisée OIT)
4  Travailleurs salariés, hommes (% de la population masculine en emploi)
5  Chefs d’entreprise, hommes (% de la population masculine en emploi)
6  Risque de de dépenses appauvrissantes en cas de recours nécessaire à la chirurgie (% de la pop. à risque)
7  Proportion de sièges occupés par des femmes dans les parlements nationaux (%)
8  Chômage, hommes (% de la population active masculine) (estimation modélisée OIT)
9  Chômage, total des jeunes (% de la population active âgée de 15 à 24 ans) (estimation modélisée OIT)
10 Taux de participation à la population active, hommes (% de la population masculine âgée de 15 ans et plus) (estimation modélisée OIT)
11 Emplois vulnérables, total (% des emplois)
12 Ratio emplois/population de personnes âgées de 15 à 24 ans, total (%) (estimation modélisée OIT)
13 Éducation secondaire, durée (années)
14 Population active, femmes (% de la population active)
15 Travailleurs familiaux (% de l’emploi total)
16 Ratio emploi-population, personnes âgées de 15 ans et plus, femmes (%) (estimation modélisée OIT)
17 Employés, agriculture, hommes (% d’emploi des hommes)
18 Taux de participation à la population active, total (% de la population totale de 15 à 64 ans) (estimation modélisée OIT)
19 Travailleurs indépendants, femmes (% de la population féminine en emploi)
20 Travailleurs familiaux, hommes (% de l’emploi masculin)
21 Employées, agriculture, femmes (% d’emploi des femmes)
22 Éducation primaire, durée (années)
23 Taux de participation à la population active, hommes (% de la population masculine de 15 à 24 ans) (estimation modélisée OIT)
24 Emplois vulnérables, hommes (% des emplois chez les hommes)
25 Chômage, femmes (% de la population active féminine) (estimation modélisée OIT)
26 Chômage, jeunes hommes (% de la population active masculine de 15 à 24 ans) (estimation modélisée OIT)
27 Rapport femmes/hommes dans le taux de participation à la population active (%) (estimation modélisée OIT)
28 Emplois vulnérables, femmes (% des emplois chez les femmes)
29 Ratio emplois/population d’hommes âgés de 15 à 24 ans (%) (estimation modélisée OIT)
30 Population active, total
31 Employées, services, femmes (% d’emploi des femmes)
32 Emplois dans l’agriculture (% du total des emplois)
33 Taux de participation à la population active, femmes (% de la population féminine de 15 à 24 ans) (estimation modélisée OIT)
34 Emplois dans l’industrie (% du total des emplois)
35 Ratio emploi-population, personnes âgées de 15 ans et plus, total (%) (estimation modélisée OIT)
36 Travailleurs indépendants, hommes (% de la population masculine en emploi)
37 Taux de participation à la population active des 15-24 ans, total (%) (estimation modélisée OIT)
38 Travailleurs salariés, femmes (% de la population féminine en emploi)
39 Chefs d’entreprise, femmes (% de la population féminine en emploi)
40 Risque de de dépenses catastrophiques en cas de recours nécessaire à la chirurgie (% de la pop. à risque)
41 Âge de début de l’école primaire (années)
42 Travailleurs indépendants (% de la population en emploi)
43 Employés, services, hommes (% d’emploi des hommes)
44 Employées, industrie, femmes (% d’emploi des femmes)
45 Ratio emploi-population, personnes âgées de 15 ans et plus, hommes (%) (estimation modélisée OIT)
46 Taux de participation à la population active, hommes (% de la population masculine de 15 à 64 ans) (estimation modélisée OIT)
47 Travailleurs salariés (% de la population en emploi)
48 Chefs d’entreprise (% de la population en emploi)
49 Âge de début de l’école secondaire (années)
50 Chômage, jeunes femmes (% de la population active féminine de 15 à 24 ans) (estimation modélisée OIT)
51 Taux de participation à la population active, femmes (% de la population féminine âgée de 15 ans et plus) (estimation modélisée OIT)
52 Emplois dans les services (% du total des emplois)
53 Employés, industrie, hommes (% d’emploi des hommes)
54 Ratio emplois/population de femmes âgées de 15 à 24 ans (%) (estimation modélisée OIT)
55 Travailleurs familiaux, femmes (% de l’emploi féminin)
   Indicator Code         2020
1  SL.UEM.TOTL.ZS               6.67600
2  SL.TLF.CACT.ZS              45.69900
3  SL.TLF.ACTI.FE.ZS           36.42600
4  SL.EMP.WORK.MA.ZS           39.62400
5  SL.EMP.MPYR.MA.ZS            1.14300
6  SH.SGR.IRSK.ZS              27.70000
7  SG.GEN.PARL.ZS              43.03030
8  SL.UEM.TOTL.MA.ZS            5.93100
9  SL.UEM.1524.ZS               8.61400
10 SL.TLF.CACT.MA.ZS           57.45000
11 SL.EMP.VULN.ZS              64.32900
12 SL.EMP.1524.SP.ZS           25.48200
13 SE.SEC.DURS                  7.00000
14 SL.TLF.TOTL.FE.ZS           40.39662
15 SL.FAM.WORK.ZS              21.99900
16 SL.EMP.TOTL.SP.FE.ZS        32.37400
17 SL.AGR.EMPL.MA.ZS           32.85900
18 SL.TLF.ACTI.ZS              47.18600
19 SL.EMP.SELF.FE.ZS           72.44300
20 SL.FAM.WORK.MA.ZS           19.22100
21 SL.AGR.EMPL.FE.ZS           24.26100
22 SE.PRM.DURS                  6.00000
23 SL.TLF.ACTI.1524.MA.ZS      33.31600
24 SL.EMP.VULN.MA.ZS           59.23300
25 SL.UEM.TOTL.FE.ZS            7.77400
26 SL.UEM.1524.MA.ZS            7.23000
27 SL.TLF.CACT.FM.ZS           61.10183
28 SL.EMP.VULN.FE.ZS           72.00000
29 SL.EMP.1524.SP.MA.ZS        30.90700
30 SL.TLF.TOTL.IN         4392588.00000
31 SL.SRV.EMPL.FE.ZS           70.26100
32 SL.AGR.EMPL.ZS              29.42700
33 SL.TLF.ACTI.1524.FE.ZS      22.40100
34 SL.IND.EMPL.ZS              13.62800
35 SL.EMP.TOTL.SP.ZS           42.64800
36 SL.EMP.SELF.MA.ZS           60.37600
37 SL.TLF.ACTI.1524.ZS         27.88400
38 SL.EMP.WORK.FE.ZS           27.55700
39 SL.EMP.MPYR.FE.ZS            0.44400
40 SH.SGR.CRSK.ZS              37.40000
41 SE.PRM.AGES                  6.00000
42 SL.EMP.SELF.ZS              65.19300
43 SL.SRV.EMPL.MA.ZS           48.09800
44 SL.IND.EMPL.FE.ZS            5.47800
45 SL.EMP.TOTL.SP.MA.ZS        54.04300
46 SL.TLF.ACTI.MA.ZS           58.96400
47 SL.EMP.WORK.ZS              34.80700
48 SL.EMP.MPYR.ZS               0.86400
49 SE.SEC.AGES                 12.00000
50 SL.UEM.1524.FE.ZS           10.69300
51 SL.TLF.CACT.FE.ZS           35.10300
52 SL.SRV.EMPL.ZS              56.94500
53 SL.IND.EMPL.MA.ZS           19.04300
54 SL.EMP.1524.SP.FE.ZS        20.00600
55 SL.FAM.WORK.FE.ZS           26.18100

## dplyr::mutate

![](http://ohi-science.org/data-science-training/img/rstudio-cheatsheet-mutate.png)
mutate () ajoute de nouvelles variables et préserve celles existantes; transmute () ajoute de nouvelles variables
et supprime ceux existants. Les nouvelles variables écrasent les variables existantes du même nom.
Les variables peuvent être supprimées en définissant leur valeur sur NULL.

Useful mutate functions
 `+`, `-`, `log()`, etc., for their usual mathematical meanings
` lead()`, `lag()`
 `dense_ank()`, `min_ank()`, `percent_rank()`, `row_number()`, `cume_dist()`, `ntile()`
 `cumsum()`, `cummean()`, `cummin()`, `cummax()`, `cumany()`, `cumall()`
 naif(), `coalesce()`
 `ifelse()`, `recode()`, `case_when()`

In [110]:
fao_cdu %>% select(Item,Element,Year,Value) %>% 
mutate(log_value=log(Value)) %>% filter(!is.nan(log_value) | is.finite(log_value) |log_value)

ERROR: Error in parse(text = x, srcfile = src): <text>:2:95: '=' inattendu(e)
1: fao_cdu %>% select(Item,Element,Year,Value) %>%
2: mutate(log_value=log(Value)) %>% filter(!is.nan(log_value) | is.finite(log_value) | log_value =
                                                                                                 ^

In [77]:
fao_cdu %>% filter(Item.Code=="111" & Element=="Import Quantity") %>%  
  select(!contains(c("code","Flag"))) %>% 
  mutate(Q1=quantile(Value,0.25,na.rm=TRUE),
         moyenne=mean(Value,na.rm=TRUE))

  Domain Area    Element         Item  Year Unit   Value  Q1     moyenne
1 Crops  Senegal Import Quantity Wheat 2014 tonnes 545226 584362 595267.8
2 Crops  Senegal Import Quantity Wheat 2015 tonnes 584362 584362 595267.8
3 Crops  Senegal Import Quantity Wheat 2016 tonnes 592159 584362 595267.8
4 Crops  Senegal Import Quantity Wheat 2017 tonnes 646073 584362 595267.8
5 Crops  Senegal Import Quantity Wheat 2018 tonnes 608519 584362 595267.8

In [78]:
donnee_bm %>% mutate_if(is.numeric,round,1)

     Country Name Country Code
1    Sénégal      SEN
2    Sénégal      SEN
3    Sénégal      SEN
4    Sénégal      SEN
5    Sénégal      SEN
6    Sénégal      SEN
7    Sénégal      SEN
8    Sénégal      SEN
9    Sénégal      SEN
10   Sénégal      SEN
11   Sénégal      SEN
12   Sénégal      SEN
13   Sénégal      SEN
14   Sénégal      SEN
15   Sénégal      SEN
16   Sénégal      SEN
17   Sénégal      SEN
18   Sénégal      SEN
19   Sénégal      SEN
20   Sénégal      SEN
21   Sénégal      SEN
22   Sénégal      SEN
23   Sénégal      SEN
24   Sénégal      SEN
25   Sénégal      SEN
26   Sénégal      SEN
27   Sénégal      SEN
28   Sénégal      SEN
29   Sénégal      SEN
30   Sénégal      SEN
...  ...          ...
1411 Sénégal      SEN
1412 Sénégal      SEN
1413 Sénégal      SEN
1414 Sénégal      SEN
1415 Sénégal      SEN
1416 Sénégal      SEN
1417 Sénégal      SEN
1418 Sénégal      SEN
1419 Sénégal      SEN
1420 Sénégal      SEN
1421 Sénégal      SEN
1422 Sénégal      SEN
1423 Sénégal      SEN
1424 Sénégal      SEN
1425 Sénégal      SEN
1426 Sénégal      SEN
1427 Sénégal      SEN
1428 Sénégal      SEN
1429 Sénégal      SEN
1430 Sénégal      SEN
1431 Sénégal      SEN
1432 Sénégal      SEN
1433 Sénégal      SEN
1434 Sénégal      SEN
1435 Sénégal      SEN
1436 Sénégal      SEN
1437 Sénégal      SEN
1438 Sénégal      SEN
1439 Sénégal      SEN
1440 Sénégal      SEN
     Indicator Name
1    Internally displaced persons, total displaced by conflict and violence (number of people)
2    Exportations de marchandises vers les pays en développement du Moyen-Orient et d’Afrique du Nord (% des exportations totales de marchandises)
3    Indice du volume des exportations (2000=100)
4    Importations de marchandises des pays en développement d’Asie de l’Est et du Pacifique (% des importations totales de marchandises)
5    Taux des droits de douane, nation la plus favorisée, moyenne simple, produits de base (%)
6    Taux des droits de douane, nation la plus favorisée, moyenne simple, produits manufacturés (%)
7    Tourisme international, nombre d’arrivées
8    Population, femmes (% du total)
9    Population âgée de 65 et plus (% du total)
10   Population âgée de 40 à 44 ans, hommes (% de la population masculine)
11   Population âgée de 15 à 19 ans, garçons (% de la population masculine)
12   Women who were first married by age 15 (% of women ages 20-24)
13   Taux de mortalité, adultes, hommes (pour 1 000 hommes adultes)
14   Chômage, total (% de la population) (estimation modélisée OIT)
15   Chômage dans la population avec un niveau d’études supérieur, hommes (% de la population active masculine dans cette catégorie)
16   Taux de participation à la population active, total (% du total de la population âgée de 15 ans et plus) (estimation modélisée OIT)
17   Taux de participation à la population active, femmes (% de la population féminine de 15 à 64 ans) (estimation modélisée OIT)
18   Enfants actifs économiquement, qui étudient et travaillent, garçons (% de tous les garçons économiquement actifs de 7 à 14 ans)
19   Emploi d’enfants dans le secteur manufacturier, garçons (% des garçons économiquement actifs de 7 à 14 ans travaillant dans ce secteur)
20   Travailleurs salariés, hommes (% de la population masculine en emploi)
21   Chefs d’entreprise, hommes (% de la population masculine en emploi)
22   Taux de croissance moyen annualisé du niveau de vie par habitant, 40 % les plus pauvres de la population (%)
23   Poverty headcount ratio at $3.20 a day (2011 PPP) (% of population)
24   Out-of-pocket expenditure per capita (current US$)
25   Number of people spending more than 25% of household consumption or income on out-of-pocket health care expenditure
26   Prévalence de l’émaciation sévère, rapport poids/taille, filles (% des enfants de moins de 5 ans)
27   Mortality rate attributed to unintentional poisoning, female (per 100,000 female population)
28   People with basic handwashing facilities including soap and water, urban (% of urban population)
29   Risque de de dépenses appauvrissantes en cas de recours nécessaire à la chirurgie (% de la pop. à risque)
30   Lits d’hôpital (pour 1 000 personnes)
...  ...
1411 Proportion de femmes à des postes d’encadrement intermédiaire et supérieur (%)
1412 Emploi des enfants dans l’agriculture (% d’enfants économiquement actifs de 7 à 14 ans travaillant dans ce secteur)
1413 Multidimensional poverty headcount ratio, female (% of female population)
1414 Part des revenus détenus par le deuxième quartile de 20 %
1415 Current health expenditure per capita (current US$)
1416 Incidence de la tuberculose (pour 100 000 personnes)
1417 Prévalence de la malnutrition, taille selon l’âge, filles (% des enfants de mois de 5 ans)
1418 Ratio de décès maternel (estimation par modèle, pour 100 000 naissances vivantes)
1419 Femmes enceintes recevant des soins prénataux (%)
1420 Incidence du paludisme (pour 1 000 personnes à risque)
1421 Nouveaux cas d’infection par le VIH chez les adultes (15 ans et plus)
1422 Taux de mortalité infantile, moins de 5 ans, garçons (pour 1 000)
1423 Number of deaths ages 15-19 years
1424 Part des femmes qui estiment qu’un homme a le droit de frapper son épouse si celle-ci se dispute avec lui (%)
1425 Dépenses courantes consacrées à l’éducation, total (% du total des dépenses dans l’enseignement public)
1426 Niveau d éducation, doctorat ou diplôme équivalent, hommes de 25 ans et plus (%)
1427 Enseignants qualifiés dans le 1er cycle du secondaire (% de la population enseignante totale)
1428 Ratio élèves/enseignant, deuxième cycle du secondaire
1429 Niveau d éducation, achèvement du premier cycle des études secondaires au minimum, femmes de 25 ans et plus (%)
1430 Enseignants formés dans l’éducation primaire (% du total des enseignants)
1431 Taux d’inscription net en CP (% de la population officielle en âge d’aller à l’école)
1432 Niveau d’éducation, achèvement du cycle primaire au minimum, population de 25 ans et plus (%)
1433 Ratio filles/garçons des inscriptions au secondaire (%)
1434 Couverture des programmes d’assurance sociale dans le quintile le plus pauvre (% de la population)
1435 Couverture des allocations chômage et des programmes actifs du marché du travail dans le quintile le plus pauvre (% de la population)
1436 Taxes nettes sur les produits (unités de devises locales constantes)
1437 RNB par habitant, méthode Atlas ($ US courants)
1438 PIB par habitant, ($ PPA internationaux constants de 2011)
1439 Bénéfices tirés des minéraux (% du PIB)
1440 Épargne nette rajustée, en incluant les dommages causés par les émissions de particules (% du RNB)
     Indicator Code          1960  1961  1962  1963  1964  1965           ...
1    VC.IDP.TOCV                NA    NA    NA    NA    NA    NA          ...
2    TX.VAL.MRCH.R4.ZS         5.2   5.2   2.4   0.6   0.6   0.2          ...
3    TX.QTY.MRCH.XD.WD          NA    NA    NA    NA    NA    NA          ...
4    TM.VAL.MRCH.R1.ZS         5.6   7.4   5.8   8.4  10.5  11.5          ...
5    TM.TAX.TCOM.SM.FN.ZS       NA    NA    NA    NA    NA    NA          ...
6    TM.TAX.MANF.SM.FN.ZS       NA    NA    NA    NA    NA    NA          ...
7    ST.INT.ARVL                NA    NA    NA    NA    NA    NA          ...
8    SP.POP.TOTL.FE.ZS        50.3  50.3  50.2  50.1  50.1  50.0          ...
9    SP.POP.65UP.TO.ZS         2.6   2.6   2.6   2.6   2.6   2.5          ...
10   SP.POP.4044.MA.5Y         4.6   4.6   4.6   4.6   4.6   4.6          ...
11   SP.POP.1519.MA.5Y         9.6   9.5   9.4   9.3   9.2   9.3          ...
12   SP.M15.2024.FE.ZS          NA    NA    NA    NA    NA    NA          ...
13   SP.DYN.AMRT.MA          495.0 491.5 488.1 487.8 487.6 487.3          ...
14   SL.UEM.TOTL.ZS             NA    NA    NA    NA    NA    NA          ...
15   SL.UEM.ADVN.MA.ZS          NA    NA    NA    NA    NA    NA          ...
16   SL.TLF.CACT.ZS             NA    NA    NA    NA    NA    NA          ...
17   SL.TLF.ACTI.FE.ZS          NA    NA    NA    NA    NA    NA          ...
18   SL.TLF.0714.SW.MA.ZS       NA    NA    NA    NA    NA    NA          ...
19   SL.MNF.0714.MA.ZS          NA    NA    NA    NA    NA    NA          ...
20   SL.EMP.WORK.MA.ZS          NA    NA    NA    NA    NA    NA          ...
21   SL.EMP.MPYR.MA.ZS          NA    NA    NA    NA    NA    NA          ...
22   SI.SPR.PC40.ZG             NA    NA    NA    NA    NA    NA          ...
23   SI.POV.LMIC                NA    NA    NA    NA    NA    NA          ...
24   SH.XPD.OOPC.PC.CD          NA    NA    NA    NA    NA    NA          ...
25   SH.UHC.OOPC.25.TO          NA    NA    NA    NA    NA    NA          ...
26   SH.SVR.WAST.FE.ZS          NA    NA    NA    NA    NA    NA          ...
27   SH.STA.POIS.P5.FE          NA    NA    NA    NA    NA    NA          ...
28   SH.STA.HYGN.UR.ZS          NA    NA    NA    NA    NA    NA          ...
29   SH.SGR.IRSK.ZS             NA    NA    NA    NA    NA    NA          ...
30   SH.MED.BEDS.ZS            1.3    NA    NA    NA    NA    NA          ...
...  ...                     ...   ...   ...   ...   ...   ...
1411 SL.EMP.SMGT.FE.ZS          NA    NA    NA    NA    NA             NA ...
1412 SL.AGR.0714.ZS             NA    NA    NA    NA    NA             NA ...
1413 SI.POV.MDIM.FE             NA    NA    NA    NA    NA             NA ...
1414 SI.DST.02ND.20             NA    NA    NA    NA    NA             NA ...
1415 SH.XPD.CHEX.PC.CD          NA    NA    NA    NA    NA             NA ...
1416 SH.TBS.INCD                NA    NA    NA    NA    NA             NA ...
1417 SH.STA.STNT.FE.ZS          NA    NA    NA    NA    NA             NA ...
1418 SH.STA.MMRT                NA    NA    NA    NA    NA             NA ...
1419 SH.STA.ANVC.ZS             NA    NA    NA    NA    NA             NA ...
1420 SH.MLR.INCD.P3             NA    NA    NA    NA    NA             NA ...
1421 SH.HIV.INCD                NA    NA    NA    NA    NA             NA ...
1422 SH.DYN.MORT.MA          301.8 301.5 301.8 302.3 302.9          303.2 ...
1423 SH.DTH.1519                NA    NA    NA    NA    NA             NA ...
1424 SG.VAW.ARGU.ZS             NA    NA    NA    NA    NA             NA ...
1425 SE.XPD.CTOT.ZS             NA    NA    NA    NA    NA             NA ...
1426 SE.TER.CUAT.DO.MA.ZS       NA    NA    NA    NA    NA             NA ...
1427 SE.SEC.TCAQ.LO.ZS          NA    NA    NA    NA    NA             NA ...
1428 SE.SEC.ENRL.UP.TC.ZS       NA    NA    NA    NA    NA             NA ...
1429 SE.SEC.CUAT.LO.FE.ZS       NA    NA    NA    NA    NA             NA ...
1430 SE.PRM.TCAQ.ZS             NA    NA    NA    NA    NA             NA ...
1431 SE.PRM.NINT.ZS             NA    NA    NA    NA    NA             NA ...
1432 SE.PRM.CUAT.ZS             NA    NA    NA    NA    NA             NA ...
1433 SE.ENR.SECO.FM.ZS          NA    NA    NA    NA    NA             NA ...
1434 per_si_allsi.cov_q1_tot    NA    NA    NA    NA    NA             NA ...
1435 per_lm_alllm.cov_q1_tot    NA    NA    NA    NA    NA             NA ...
1436 NY.TAX.NIND.KN             NA    NA    NA    NA    NA 330775717223.9 ...
1437 NY.GNP.PCAP.CD             NA    NA    NA    NA    NA             NA ...
1438 NY.GDP.PCAP.PP.KD          NA    NA    NA    NA    NA             NA ...
1439 NY.GDP.MINR.RT.ZS          NA    NA    NA    NA    NA             NA ...
1440 NY.ADJ.SVNG.GN.ZS          NA    NA    NA    NA    NA             NA ...
     2011           2012           2013           2014
1     24000.0        22000.0         24000.0       24000.0
2         2.8            0.6             0.9           1.2
3       113.9          112.4           121.2         127.7
4        13.7            9.2            11.2          11.3
5        12.0           12.0            12.0          12.0
6        11.9           11.9            11.9          11.9
7    968000.0       962000.0       1063000.0      963000.0
8        51.3           51.4            51.4          51.4
9         3.1            3.1             3.1           3.1
10        3.7            3.8             3.8           3.8
11       11.2           11.1            11.0          11.0
12       12.0             NA             8.6           8.7
13      237.4          233.0           230.1         227.3
14       10.4            9.4             8.5           7.6
15         NA             NA              NA            NA
16       48.0           47.4            46.8          46.2
17       35.6           35.7            35.8          35.9
18       39.6             NA              NA            NA
19        3.3             NA              NA            NA
20       33.9           34.9            35.9          37.1
21        1.1            1.1             1.1           1.1
22         NA             NA              NA            NA
23       68.4             NA              NA            NA
24       29.2           29.7            33.2          30.9
25         NA             NA              NA            NA
26        2.5             NA             1.9           0.8
27         NA             NA              NA            NA
28       22.7           22.7            22.7          41.8
29       32.9           31.7            32.6          32.9
30         NA             NA              NA            NA
...  ...            ...            ...            ...
1411             NA             NA             NA             NA
1412           85.6             NA             NA             NA
1413             NA             NA             NA             NA
1414           10.4             NA             NA             NA
1415           57.5           56.2           60.2           61.3
1416          130.0          129.0          127.0          125.0
1417           25.1             NA           16.9           17.1
1418          423.0          400.0          381.0          364.0
1419           93.3             NA           94.5           96.2
1420           49.9           56.9           67.9           39.5
1421         1300.0         1200.0         1100.0         1100.0
1422           67.6           64.5           61.8           59.3
1423         3241.0         3307.0         3374.0         3417.0
1424           44.5             NA           48.1           46.3
1425           87.1           88.4           78.6           87.6
1426            0.5             NA            0.7             NA
1427             NA             NA             NA             NA
1428             NA             NA             NA             NA
1429            7.2             NA            9.6             NA
1430           63.1           64.7           72.4           70.0
1431             NA           36.1           36.0           33.1
1432           21.8             NA           27.3             NA
1433            0.9            0.9            1.0            1.0
1434            0.9             NA             NA             NA
1435            3.6             NA             NA             NA
1436 940687412500.0 927803912200.0 898077784900.0 964806000000.0
1437         1310.0         1330.0         1360.0         1380.0
1438         2707.1         2767.4         2767.0         2868.3
1439            1.7            2.6            1.5            1.2
1440            5.0            7.0            7.4           10.8
     2015            2016            2017            2018
1      24000.0         24000.0         22000.0       18000.0
2          1.3             1.1             1.0           0.9
3        142.3           148.2           157.1         174.1
4         13.0            13.3            13.9          15.2
5         13.3            13.3            13.3          13.3
6         11.8            11.8            11.8          11.8
7    1006600.0       1210000.0       1365000.0            NA
8         51.4            51.3            51.3          51.3
9          3.1             3.1             3.1           3.1
10         3.8             3.9             3.9           4.0
11        11.0            10.9            10.9          10.8
12         8.5             7.9             8.4           7.8
13       224.4           221.6           218.7         216.0
14         6.8             6.7             6.6           6.5
15        16.5              NA              NA            NA
16        45.7            45.7            45.7          45.7
17        36.0            36.0            36.2          36.3
18        52.3              NA              NA            NA
19          NA              NA              NA            NA
20        38.2            38.5            38.8          39.1
21         1.1             1.1             1.1           1.1
22          NA              NA              NA            NA
23          NA              NA              NA            NA
24        27.2            27.7            29.6          32.9
25          NA              NA              NA            NA
26         1.3             0.9             1.4            NA
27         1.7             1.6              NA            NA
28        41.8            41.8            41.8            NA
29        31.0            30.8            30.6          29.0
30          NA              NA              NA            NA
...  ...             ...             ...             ...
1411              NA              NA              NA              NA
1412              NA              NA              NA              NA
1413              NA              NA              NA              NA
1414              NA              NA              NA              NA
1415            53.4            54.1            55.1            58.9
1416           123.0           122.0           120.0           118.0
1417            18.6            14.7            15.0              NA
1418           346.0           330.0           315.0              NA
1419            95.0            95.9            97.1              NA
1420            69.8            45.7            52.4            55.8
1421          1100.0          1100.0          1000.0          1100.0
1422            57.1            54.8            52.9            51.0
1423          3453.0          3461.0          3462.0          3456.0
1424            45.1            38.9            35.4              NA
1425            85.3            95.0              NA              NA
1426              NA              NA             0.1              NA
1427              NA              NA              NA              NA
1428              NA              NA              NA            19.3
1429              NA              NA            10.3              NA
1430            68.3              NA              NA              NA
1431            39.6            42.0            42.4              NA
1432              NA              NA            21.9              NA
1433              NA              NA              NA              NA
1434              NA              NA              NA              NA
1435              NA              NA              NA              NA
1436 1051028000000.0 1135715548200.0 1259856164500.0 1328760612500.0
1437          1320.0          1270.0          1280.0          1400.0
1438          2966.5          3067.7          3203.9          3314.8
1439             1.3             1.6             1.2             1.1
1440            11.1            10.9            12.3            12.5
     2019            2020
1    8400.0            NA
2        NA            NA
3        NA            NA
4        NA            NA
5        NA            NA
6        NA            NA
7        NA            NA
8      51.2            NA
9       3.1            NA
10      4.0            NA
11     10.9            NA
12       NA            NA
13       NA            NA
14      6.6           6.7
15       NA            NA
16     45.7          45.7
17     36.4          36.4
18       NA            NA
19       NA            NA
20     39.3          39.6
21      1.1           1.1
22       NA            NA
23       NA            NA
24       NA            NA
25       NA            NA
26      2.1            NA
27       NA            NA

'data.frame':	1440 obs. of  65 variables:
 $ Country Name  : chr  "Sénégal" "Sénégal" "Sénégal" "Sénégal" ...
 $ Country Code  : chr  "SEN" "SEN" "SEN" "SEN" ...
 $ Indicator Name: chr  "Internally displaced persons, total displaced by conflict and violence (number of people)" "Exportations de marchandises vers les pays en développement du Moyen-Orient et d’Afrique du Nord (% des exporta"| __truncated__ "Indice du volume des exportations (2000=100)" "Importations de marchandises des pays en développement d’Asie de l’Est et du Pacifique (% des importations tota"| __truncated__ ...
 $ Indicator Code: chr  "VC.IDP.TOCV" "TX.VAL.MRCH.R4.ZS" "TX.QTY.MRCH.XD.WD" "TM.VAL.MRCH.R1.ZS" ...
 $ 1960          : num  NA 5.2 NA 5.57 NA ...
 $ 1961          : num  NA 5.22 NA 7.38 NA ...
 $ 1962          : num  NA 2.43 NA 5.76 NA ...
 $ 1963          : num  NA 0.635 NA 8.368 NA ...
 $ 1964          : num  NA 0.578 NA 10.52 NA ...
 $ 1965          : num  NA 0.235 NA 11.538 NA ...
 $ 1966          : num  NA 0.47 NA 8.39 NA ...
 $ 1967          : num  NA 0.516 NA 13.693 NA ...
 $ 1968          : num  NA 0.399 NA 8.533 NA ...
 $ 1969          : num  NA 0.0441 NA 5.5404 NA ...
 $ 1970          : num  NA 0.281 NA 4.749 NA ...
 $ 1971          : num  NA 0.547 NA 3.984 NA ...
 $ 1972          : num  NA 0.731 NA 6.427 NA ...
 $ 1973          : num  NA 0.588 NA 8.971 NA ...
 $ 1974          : num  NA 1.55 NA 6.75 NA ...
 $ 1975          : num  NA 0.388 NA 1.488 NA ...
 $ 1976          : num  NA 0.0563 NA 2.3002 NA ...
 $ 1977          : num  NA 0.271 NA 4.238 NA ...
 $ 1978          : num  NA 0.441 NA 3.008 NA ...
 $ 1979          : num  NA 0.0211 NA 7.5482 NA ...
 $ 1980          : num  NA 0.666 32.407 8.095 NA ...
 $ 1981          : num  NA 0.532 35.301 9.069 NA ...
 $ 1982          : num  NA 0.555 46.534 10.486 NA ...
 $ 1983          : num  NA NA 57.9 11.2 NA ...
 $ 1984          : num  NA 0.311 56.035 9.781 NA ...
 $ 1985          : num  NA 0.529 48.491 5.359 NA ...
 $ 1986          : num  NA 0.125 47.546 5.931 NA ...
 $ 1987          : num  NA 0.326 40.695 3.149 NA ...
 $ 1988          : num  NA 0.681 40.169 5.005 NA ...
 $ 1989          : num  NA 0.636 45.666 5.526 NA ...
 $ 1990          : num  NA 2.32 44.52 5.94 NA ...
 $ 1991          : num  NA 1.62 42.33 6.52 NA ...
 $ 1992          : num  NA 3.46 39.32 7.14 NA ...
 $ 1993          : num  NA 4.2 45.21 8.68 NA ...
 $ 1994          : num  NA 3.76 57.71 7.15 NA ...
 $ 1995          : num  NA 1.96 61.71 7.77 NA ...
 $ 1996          : num  NA 1.7 65.49 7.51 NA ...
 $ 1997          : num  NA 0.888 81.955 8.531 NA ...
 $ 1998          : num  NA 1.74 87.67 8.82 NA ...
 $ 1999          : num  NA 0.712 96.263 10.718 NA ...
 $ 2000          : num  NA 0.762 100 11.848 NA ...
 $ 2001          : num  NA 0.751 114.54 12.883 11.78 ...
 $ 2002          : num  NA 0.76 123.23 11.99 11.78 ...
 $ 2003          : num  NA 0.667 131.686 11.695 11.79 ...
 $ 2004          : num  NA 0.905 140.757 12.108 11.83 ...
 $ 2005          : num  NA 0.999 131.973 10.714 11.82 ...
 $ 2006          : num  NA 2.23 121.76 11.29 11.82 ...
 $ 2007          : num  NA 0.812 114.643 12.62 11.98 ...
 $ 2008          : num  NA 0.464 120.976 14.107 11.97 ...
 $ 2009          : num  24000 1.83 131.33 17.46 11.98 ...
 $ 2010          : num  24000 2.57 123.67 14.59 11.98 ...
 $ 2011          : num  24000 2.78 113.86 13.67 11.97 ...
 $ 2012          : num  22000 0.56 112.39 9.16 11.97 ...
 $ 2013          : num  24000 0.903 121.154 11.201 11.98 ...
 $ 2014          : num  24000 1.19 127.69 11.34 11.98 ...
 $ 2015          : num  24000 1.34 142.33 13.04 13.28 ...
 $ 2016          : num  24000 1.1 148.2 13.3 13.3 ...
 $ 2017          : num  22000 1 157.1 13.9 13.3 ...
 $ 2018          : num  18000 0.944 174.138 15.155 13.26 ...
 $ 2019          : num  8400 NA NA NA NA ...
 $ 2020          : num  NA NA NA NA NA NA NA NA NA NA ...

In [83]:
test=donnee_bm %>% select(matches("\\d\\d\\d\\d"))
test=test %>% mutate_all(round,2)
test

     1960   1961   1962   1963   1964   1965           1966
1        NA     NA     NA     NA     NA     NA             NA
2      5.20   5.22   2.43   0.64   0.58   0.24           0.47
3        NA     NA     NA     NA     NA     NA             NA
4      5.57   7.38   5.76   8.37  10.52  11.54           8.39
5        NA     NA     NA     NA     NA     NA             NA
6        NA     NA     NA     NA     NA     NA             NA
7        NA     NA     NA     NA     NA     NA             NA
8     50.32  50.25  50.19  50.13  50.07  50.00          49.93
9      2.62   2.62   2.60   2.58   2.56   2.53           2.53
10     4.61   4.60   4.60   4.60   4.61   4.64           4.63
11     9.57   9.47   9.35   9.26   9.24   9.32           9.46
12       NA     NA     NA     NA     NA     NA             NA
13   494.96 491.53 488.11 487.83 487.56 487.29         487.02
14       NA     NA     NA     NA     NA     NA             NA
15       NA     NA     NA     NA     NA     NA             NA
16       NA     NA     NA     NA     NA     NA             NA
17       NA     NA     NA     NA     NA     NA             NA
18       NA     NA     NA     NA     NA     NA             NA
19       NA     NA     NA     NA     NA     NA             NA
20       NA     NA     NA     NA     NA     NA             NA
21       NA     NA     NA     NA     NA     NA             NA
22       NA     NA     NA     NA     NA     NA             NA
23       NA     NA     NA     NA     NA     NA             NA
24       NA     NA     NA     NA     NA     NA             NA
25       NA     NA     NA     NA     NA     NA             NA
26       NA     NA     NA     NA     NA     NA             NA
27       NA     NA     NA     NA     NA     NA             NA
28       NA     NA     NA     NA     NA     NA             NA
29       NA     NA     NA     NA     NA     NA             NA
30     1.31     NA     NA     NA     NA     NA             NA
...  ...    ...    ...    ...    ...    ...            ...
1411    NA     NA     NA     NA     NA              NA             NA
1412    NA     NA     NA     NA     NA              NA             NA
1413    NA     NA     NA     NA     NA              NA             NA
1414    NA     NA     NA     NA     NA              NA             NA
1415    NA     NA     NA     NA     NA              NA             NA
1416    NA     NA     NA     NA     NA              NA             NA
1417    NA     NA     NA     NA     NA              NA             NA
1418    NA     NA     NA     NA     NA              NA             NA
1419    NA     NA     NA     NA     NA              NA             NA
1420    NA     NA     NA     NA     NA              NA             NA
1421    NA     NA     NA     NA     NA              NA             NA
1422 301.8  301.5  301.8  302.3  302.9           303.2          302.4
1423    NA     NA     NA     NA     NA              NA             NA
1424    NA     NA     NA     NA     NA              NA             NA
1425    NA     NA     NA     NA     NA              NA             NA
1426    NA     NA     NA     NA     NA              NA             NA
1427    NA     NA     NA     NA     NA              NA             NA
1428    NA     NA     NA     NA     NA              NA             NA
1429    NA     NA     NA     NA     NA              NA             NA
1430    NA     NA     NA     NA     NA              NA             NA
1431    NA     NA     NA     NA     NA              NA             NA
1432    NA     NA     NA     NA     NA              NA             NA
1433    NA     NA     NA     NA     NA              NA             NA
1434    NA     NA     NA     NA     NA              NA             NA
1435    NA     NA     NA     NA     NA              NA             NA
1436    NA     NA     NA     NA     NA  330775717224.0 319538373110.9
1437    NA     NA     NA     NA     NA              NA             NA
1438    NA     NA     NA     NA     NA              NA             NA
1439    NA     NA     NA     NA     NA              NA             NA
1440    NA     NA     NA     NA     NA              NA             NA
     1967           1968           1969           ... 2011
1        NA             NA             NA         ...  24000.00
2      0.52           0.40           0.04         ...      2.78
3        NA             NA             NA         ...    113.86
4     13.69           8.53           5.54         ...     13.67
5        NA             NA             NA         ...     11.97
6        NA             NA             NA         ...     11.87
7        NA             NA             NA         ... 968000.00
8     49.87          49.80          49.73         ...     51.34
9      2.53           2.52           2.51         ...      3.14
10     4.63           4.65           4.67         ...      3.74
11     9.68           9.93          10.14         ...     11.19
12       NA             NA             NA         ...     12.00
13   486.75         480.43         474.10         ...    237.40
14       NA             NA             NA         ...     10.36
15       NA             NA             NA         ...        NA
16       NA             NA             NA         ...     47.96
17       NA             NA             NA         ...     35.63
18       NA             NA             NA         ...     39.60
19       NA             NA             NA         ...      3.32
20       NA             NA             NA         ...     33.87
21       NA             NA             NA         ...      1.06
22       NA             NA             NA         ...        NA
23       NA             NA             NA         ...     68.40
24       NA             NA             NA         ...     29.22
25       NA             NA             NA         ...        NA
26       NA             NA             NA         ...      2.50
27       NA             NA             NA         ...        NA
28       NA             NA             NA         ...     22.73
29       NA             NA             NA         ...     32.90
30       NA             NA             NA         ...        NA
...  ...            ...            ...                ...
1411             NA             NA             NA ...              NA
1412             NA             NA             NA ...           85.60
1413             NA             NA             NA ...              NA
1414             NA             NA             NA ...           10.40
1415             NA             NA             NA ...           57.52
1416             NA             NA             NA ...          130.00
1417             NA             NA             NA ...           25.10
1418             NA             NA             NA ...          423.00
1419             NA             NA             NA ...           93.30
1420             NA             NA             NA ...           49.91
1421             NA             NA             NA ...         1300.00
1422          301.2          299.5          296.9 ...           67.60
1423             NA             NA             NA ...         3241.00
1424             NA             NA             NA ...           44.50
1425             NA             NA             NA ...           87.08
1426             NA             NA             NA ...            0.45
1427             NA             NA             NA ...              NA
1428             NA             NA             NA ...              NA
1429             NA             NA             NA ...            7.20
1430             NA             NA             NA ...           63.10
1431             NA             NA             NA ...              NA
1432             NA             NA             NA ...           21.78
1433             NA             NA             NA ...            0.92
1434             NA             NA             NA ...            0.94
1435             NA             NA             NA ...            3.57
1436 327419453793.8 298403577858.7 273430009286.9 ... 940687412500.00
1437             NA          340.0          310.0 ...         1310.00
1438             NA             NA             NA ...         2707.06
1439             NA             NA             NA ...            1.73
1440             NA             NA             NA ...            4.96
     2012            2013            2014            2015
1     22000.00         24000.00       24000.00         24000.00
2         0.56             0.90           1.19             1.34
3       112.39           121.15         127.69           142.33
4         9.16            11.20          11.34            13.04
5        11.97            11.98          11.98            13.28
6        11.87            11.87          11.87            11.77
7    962000.00       1063000.00      963000.00       1006600.00
8        51.36            51.37          51.38            51.37
9         3.12             3.09           3.07             3.06
10        3.76             3.78           3.81             3.83
11       11.10            11.03          10.99            10.96
12          NA             8.60           8.70             8.50
13      233.00           230.14         227.29           224.43
14        9.43             8.54           7.61             6.76
15          NA               NA             NA            16.51
16       47.40            46.83          46.25            45.66
17       35.71            35.79          35.88            35.96
18          NA               NA             NA            52.29
19          NA               NA             NA               NA
20       34.94            35.93          37.07            38.20
21        1.08             1.09           1.11             1.12
22          NA               NA             NA               NA
23          NA               NA             NA               NA
24       29.68            33.25          30.93            27.18
25          NA               NA             NA               NA
26          NA             1.90           0.80             1.30
27          NA               NA             NA             1.70
28       22.73            22.73          41.83            41.83
29       31.70            32.60          32.90            31.00
30          NA               NA             NA               NA
...  ...             ...             ...             ...
1411              NA              NA              NA               NA
1412              NA              NA              NA               NA
1413              NA              NA              NA               NA
1414              NA              NA              NA               NA
1415           56.23           60.18           61.32            53.41
1416          129.00          127.00          125.00           123.00
1417              NA           16.90           17.10            18.60
1418          400.00          381.00          364.00           346.00
1419              NA           94.50           96.20            95.00
1420           56.92           67.90           39.51            69.80
1421         1200.00         1100.00         1100.00          1100.00
1422           64.50           61.80           59.30            57.10
1423         3307.00         3374.00         3417.00          3453.00
1424              NA           48.10           46.30            45.10
1425           88.45           78.59           87.65            85.27
1426              NA            0.68              NA               NA
1427              NA              NA              NA               NA
1428              NA              NA              NA               NA
1429              NA            9.57              NA               NA
1430           64.72           72.38           69.97            68.34
1431           36.09           36.03           33.13            39.63
1432              NA           27.35              NA               NA
1433            0.94            0.97            1.00               NA
1434              NA              NA              NA               NA
1435              NA              NA              NA               NA
1436 927803912200.00 898077784900.00 964806000000.00 1051028000000.00
1437         1330.00         1360.00         1380.00          1320.00
1438         2767.41         2766.97         2868.32          2966.45
1439            2.59            1.46            1.19             1.27
1440            6.98            7.41           10.80            11.08
     2016             2017             2018             2019             2020
1      24000.00         22000.00       18000.00         8400.00             NA
2          1.10             1.00           0.94              NA             NA
3        148.19           157.06         174.14              NA             NA
4         13.31            13.88          15.15              NA             NA
5         13.28            13.26          13.26              NA             NA
6         11.77            11.79          11.79              NA             NA
7    1210000.00       1365000.00             NA              NA             NA
8         51.35            51.32          51.28           51.24             NA
9          3.07             3.07           3.09            3.10             NA
10         3.87             3.91           3.96            4.02             NA
11        10.91            10.87          10.85           10.86             NA
12         7.90             8.40           7.80              NA             NA
13       221.57           218.72         216.04              NA             NA
14         6.71             6.61           6.53            6.60           6.68
15           NA               NA             NA              NA             NA
16        45.68            45.67          45.66           45.68          45.70
17        36.04            36.15          36.28           36.36          36.43
18           NA               NA             NA              NA             NA
19           NA               NA             NA              NA             NA
20        38.47            38.78          39.08           39.33          39.62
21         1.12             1.13           1.13            1.14           1.14
22           NA               NA             NA              NA             NA
23           NA               NA             NA              NA             NA
24        27.68            29.63          32.92              NA             NA
25           NA               NA             NA              NA             NA
26         0.90             1.40             NA            2.10             NA
27         1.60               NA             NA              NA             NA
28        41.83            41.83             NA              NA             NA
29        30.80            30.60          29.00           28.80          27.70
30           NA               NA             NA              NA             NA
...  ...              ...              ...              ...              ...
1411               NA               NA               NA               NA NA
1412               NA               NA               NA               NA NA
1413               NA               NA               NA               NA NA
1414               NA               NA               NA               NA NA
1415            54.07            55.10            58.90               NA NA
1416           122.00           120.00           118.00           117.00 NA
1417            14.70            15.00               NA            16.90 NA
1418           330.00           315.00               NA               NA NA
1419            95.90            97.10               NA               NA NA
1420            45.66            52.35            55.75               NA NA
1421          1100.00          1000.00          1100.00          1100.00 NA
1422            54.80            52.90            51.00            49.30 NA
1423          3461.00          3462.00          3456.00          3479.00 NA
1424            38.90            35.40               NA               NA NA
1425            95.01               NA               NA               NA NA
1426               NA             0.10               NA               NA NA
1427               NA               NA               NA               NA NA
1428               NA               NA            19.26               NA NA
1429               NA            10.26               NA               NA NA
1430               NA               NA               NA            75.34 NA
1431            42.01            42.41               NA               NA NA
1432               NA            21.92               NA               NA NA
1433               NA               NA               NA             1.13 NA
1434               NA               NA               NA               NA NA
1435               NA               NA               NA               NA NA
1436 1135715548200.00 1259856164500.00 1328760612500.00 1454358980400.00 NA
1437          1270.00          1280.00          1400.00          1460.00 NA
1438          3067.66          3203.90          3314.79          3394.87 NA
1439             1.61             1.22             1.11               NA NA
1440            10.93            12.30            12.51               NA NA

In [84]:
donnee_bm %>% mutate(across(where(is.numeric),~round(.x)))

     Country Name Country Code
1    Sénégal      SEN
2    Sénégal      SEN
3    Sénégal      SEN
4    Sénégal      SEN
5    Sénégal      SEN
6    Sénégal      SEN
7    Sénégal      SEN
8    Sénégal      SEN
9    Sénégal      SEN
10   Sénégal      SEN
11   Sénégal      SEN
12   Sénégal      SEN
13   Sénégal      SEN
14   Sénégal      SEN
15   Sénégal      SEN
16   Sénégal      SEN
17   Sénégal      SEN
18   Sénégal      SEN
19   Sénégal      SEN
20   Sénégal      SEN
21   Sénégal      SEN
22   Sénégal      SEN
23   Sénégal      SEN
24   Sénégal      SEN
25   Sénégal      SEN
26   Sénégal      SEN
27   Sénégal      SEN
28   Sénégal      SEN
29   Sénégal      SEN
30   Sénégal      SEN
...  ...          ...
1411 Sénégal      SEN
1412 Sénégal      SEN
1413 Sénégal      SEN
1414 Sénégal      SEN
1415 Sénégal      SEN
1416 Sénégal      SEN
1417 Sénégal      SEN
1418 Sénégal      SEN
1419 Sénégal      SEN
1420 Sénégal      SEN
1421 Sénégal      SEN
1422 Sénégal      SEN
1423 Sénégal      SEN
1424 Sénégal      SEN
1425 Sénégal      SEN
1426 Sénégal      SEN
1427 Sénégal      SEN
1428 Sénégal      SEN
1429 Sénégal      SEN
1430 Sénégal      SEN
1431 Sénégal      SEN
1432 Sénégal      SEN
1433 Sénégal      SEN
1434 Sénégal      SEN
1435 Sénégal      SEN
1436 Sénégal      SEN
1437 Sénégal      SEN
1438 Sénégal      SEN
1439 Sénégal      SEN
1440 Sénégal      SEN
     Indicator Name
1    Internally displaced persons, total displaced by conflict and violence (number of people)
2    Exportations de marchandises vers les pays en développement du Moyen-Orient et d’Afrique du Nord (% des exportations totales de marchandises)
3    Indice du volume des exportations (2000=100)
4    Importations de marchandises des pays en développement d’Asie de l’Est et du Pacifique (% des importations totales de marchandises)
5    Taux des droits de douane, nation la plus favorisée, moyenne simple, produits de base (%)
6    Taux des droits de douane, nation la plus favorisée, moyenne simple, produits manufacturés (%)
7    Tourisme international, nombre d’arrivées
8    Population, femmes (% du total)
9    Population âgée de 65 et plus (% du total)
10   Population âgée de 40 à 44 ans, hommes (% de la population masculine)
11   Population âgée de 15 à 19 ans, garçons (% de la population masculine)
12   Women who were first married by age 15 (% of women ages 20-24)
13   Taux de mortalité, adultes, hommes (pour 1 000 hommes adultes)
14   Chômage, total (% de la population) (estimation modélisée OIT)
15   Chômage dans la population avec un niveau d’études supérieur, hommes (% de la population active masculine dans cette catégorie)
16   Taux de participation à la population active, total (% du total de la population âgée de 15 ans et plus) (estimation modélisée OIT)
17   Taux de participation à la population active, femmes (% de la population féminine de 15 à 64 ans) (estimation modélisée OIT)
18   Enfants actifs économiquement, qui étudient et travaillent, garçons (% de tous les garçons économiquement actifs de 7 à 14 ans)
19   Emploi d’enfants dans le secteur manufacturier, garçons (% des garçons économiquement actifs de 7 à 14 ans travaillant dans ce secteur)
20   Travailleurs salariés, hommes (% de la population masculine en emploi)
21   Chefs d’entreprise, hommes (% de la population masculine en emploi)
22   Taux de croissance moyen annualisé du niveau de vie par habitant, 40 % les plus pauvres de la population (%)
23   Poverty headcount ratio at $3.20 a day (2011 PPP) (% of population)
24   Out-of-pocket expenditure per capita (current US$)
25   Number of people spending more than 25% of household consumption or income on out-of-pocket health care expenditure
26   Prévalence de l’émaciation sévère, rapport poids/taille, filles (% des enfants de moins de 5 ans)
27   Mortality rate attributed to unintentional poisoning, female (per 100,000 female population)
28   People with basic handwashing facilities including soap and water, urban (% of urban population)
29   Risque de de dépenses appauvrissantes en cas de recours nécessaire à la chirurgie (% de la pop. à risque)
30   Lits d’hôpital (pour 1 000 personnes)
...  ...
1411 Proportion de femmes à des postes d’encadrement intermédiaire et supérieur (%)
1412 Emploi des enfants dans l’agriculture (% d’enfants économiquement actifs de 7 à 14 ans travaillant dans ce secteur)
1413 Multidimensional poverty headcount ratio, female (% of female population)
1414 Part des revenus détenus par le deuxième quartile de 20 %
1415 Current health expenditure per capita (current US$)
1416 Incidence de la tuberculose (pour 100 000 personnes)
1417 Prévalence de la malnutrition, taille selon l’âge, filles (% des enfants de mois de 5 ans)
1418 Ratio de décès maternel (estimation par modèle, pour 100 000 naissances vivantes)
1419 Femmes enceintes recevant des soins prénataux (%)
1420 Incidence du paludisme (pour 1 000 personnes à risque)
1421 Nouveaux cas d’infection par le VIH chez les adultes (15 ans et plus)
1422 Taux de mortalité infantile, moins de 5 ans, garçons (pour 1 000)
1423 Number of deaths ages 15-19 years
1424 Part des femmes qui estiment qu’un homme a le droit de frapper son épouse si celle-ci se dispute avec lui (%)
1425 Dépenses courantes consacrées à l’éducation, total (% du total des dépenses dans l’enseignement public)
1426 Niveau d éducation, doctorat ou diplôme équivalent, hommes de 25 ans et plus (%)
1427 Enseignants qualifiés dans le 1er cycle du secondaire (% de la population enseignante totale)
1428 Ratio élèves/enseignant, deuxième cycle du secondaire
1429 Niveau d éducation, achèvement du premier cycle des études secondaires au minimum, femmes de 25 ans et plus (%)
1430 Enseignants formés dans l’éducation primaire (% du total des enseignants)
1431 Taux d’inscription net en CP (% de la population officielle en âge d’aller à l’école)
1432 Niveau d’éducation, achèvement du cycle primaire au minimum, population de 25 ans et plus (%)
1433 Ratio filles/garçons des inscriptions au secondaire (%)
1434 Couverture des programmes d’assurance sociale dans le quintile le plus pauvre (% de la population)
1435 Couverture des allocations chômage et des programmes actifs du marché du travail dans le quintile le plus pauvre (% de la population)
1436 Taxes nettes sur les produits (unités de devises locales constantes)
1437 RNB par habitant, méthode Atlas ($ US courants)
1438 PIB par habitant, ($ PPA internationaux constants de 2011)
1439 Bénéfices tirés des minéraux (% du PIB)
1440 Épargne nette rajustée, en incluant les dommages causés par les émissions de particules (% du RNB)
     Indicator Code          1960 1961 1962 1963 1964 1965         ...
1    VC.IDP.TOCV              NA   NA   NA   NA   NA   NA          ...
2    TX.VAL.MRCH.R4.ZS         5    5    2    1    1    0          ...
3    TX.QTY.MRCH.XD.WD        NA   NA   NA   NA   NA   NA          ...
4    TM.VAL.MRCH.R1.ZS         6    7    6    8   11   12          ...
5    TM.TAX.TCOM.SM.FN.ZS     NA   NA   NA   NA   NA   NA          ...
6    TM.TAX.MANF.SM.FN.ZS     NA   NA   NA   NA   NA   NA          ...
7    ST.INT.ARVL              NA   NA   NA   NA   NA   NA          ...
8    SP.POP.TOTL.FE.ZS        50   50   50   50   50   50          ...
9    SP.POP.65UP.TO.ZS         3    3    3    3    3    3          ...
10   SP.POP.4044.MA.5Y         5    5    5    5    5    5          ...
11   SP.POP.1519.MA.5Y        10    9    9    9    9    9          ...
12   SP.M15.2024.FE.ZS        NA   NA   NA   NA   NA   NA          ...
13   SP.DYN.AMRT.MA          495  492  488  488  488  487          ...
14   SL.UEM.TOTL.ZS           NA   NA   NA   NA   NA   NA          ...
15   SL.UEM.ADVN.MA.ZS        NA   NA   NA   NA   NA   NA          ...
16   SL.TLF.CACT.ZS           NA   NA   NA   NA   NA   NA          ...
17   SL.TLF.ACTI.FE.ZS        NA   NA   NA   NA   NA   NA          ...
18   SL.TLF.0714.SW.MA.ZS     NA   NA   NA   NA   NA   NA          ...
19   SL.MNF.0714.MA.ZS        NA   NA   NA   NA   NA   NA          ...
20   SL.EMP.WORK.MA.ZS        NA   NA   NA   NA   NA   NA          ...
21   SL.EMP.MPYR.MA.ZS        NA   NA   NA   NA   NA   NA          ...
22   SI.SPR.PC40.ZG           NA   NA   NA   NA   NA   NA          ...
23   SI.POV.LMIC              NA   NA   NA   NA   NA   NA          ...
24   SH.XPD.OOPC.PC.CD        NA   NA   NA   NA   NA   NA          ...
25   SH.UHC.OOPC.25.TO        NA   NA   NA   NA   NA   NA          ...
26   SH.SVR.WAST.FE.ZS        NA   NA   NA   NA   NA   NA          ...
27   SH.STA.POIS.P5.FE        NA   NA   NA   NA   NA   NA          ...
28   SH.STA.HYGN.UR.ZS        NA   NA   NA   NA   NA   NA          ...
29   SH.SGR.IRSK.ZS           NA   NA   NA   NA   NA   NA          ...
30   SH.MED.BEDS.ZS            1   NA   NA   NA   NA   NA          ...
...  ...                     ...  ...  ...  ...  ...  ...
1411 SL.EMP.SMGT.FE.ZS        NA   NA   NA   NA   NA            NA ...
1412 SL.AGR.0714.ZS           NA   NA   NA   NA   NA            NA ...
1413 SI.POV.MDIM.FE           NA   NA   NA   NA   NA            NA ...
1414 SI.DST.02ND.20           NA   NA   NA   NA   NA            NA ...
1415 SH.XPD.CHEX.PC.CD        NA   NA   NA   NA   NA            NA ...
1416 SH.TBS.INCD              NA   NA   NA   NA   NA            NA ...
1417 SH.STA.STNT.FE.ZS        NA   NA   NA   NA   NA            NA ...
1418 SH.STA.MMRT              NA   NA   NA   NA   NA            NA ...
1419 SH.STA.ANVC.ZS           NA   NA   NA   NA   NA            NA ...
1420 SH.MLR.INCD.P3           NA   NA   NA   NA   NA            NA ...
1421 SH.HIV.INCD              NA   NA   NA   NA   NA            NA ...
1422 SH.DYN.MORT.MA          302  302  302  302  303           303 ...
1423 SH.DTH.1519              NA   NA   NA   NA   NA            NA ...
1424 SG.VAW.ARGU.ZS           NA   NA   NA   NA   NA            NA ...
1425 SE.XPD.CTOT.ZS           NA   NA   NA   NA   NA            NA ...
1426 SE.TER.CUAT.DO.MA.ZS     NA   NA   NA   NA   NA            NA ...
1427 SE.SEC.TCAQ.LO.ZS        NA   NA   NA   NA   NA            NA ...
1428 SE.SEC.ENRL.UP.TC.ZS     NA   NA   NA   NA   NA            NA ...
1429 SE.SEC.CUAT.LO.FE.ZS     NA   NA   NA   NA   NA            NA ...
1430 SE.PRM.TCAQ.ZS           NA   NA   NA   NA   NA            NA ...
1431 SE.PRM.NINT.ZS           NA   NA   NA   NA   NA            NA ...
1432 SE.PRM.CUAT.ZS           NA   NA   NA   NA   NA            NA ...
1433 SE.ENR.SECO.FM.ZS        NA   NA   NA   NA   NA            NA ...
1434 per_si_allsi.cov_q1_tot  NA   NA   NA   NA   NA            NA ...
1435 per_lm_alllm.cov_q1_tot  NA   NA   NA   NA   NA            NA ...
1436 NY.TAX.NIND.KN           NA   NA   NA   NA   NA  330775717224 ...
1437 NY.GNP.PCAP.CD           NA   NA   NA   NA   NA            NA ...
1438 NY.GDP.PCAP.PP.KD        NA   NA   NA   NA   NA            NA ...
1439 NY.GDP.MINR.RT.ZS        NA   NA   NA   NA   NA            NA ...
1440 NY.ADJ.SVNG.GN.ZS        NA   NA   NA   NA   NA            NA ...
     2011         2012         2013         2014         2015
1     24000        22000         24000       24000         24000
2         3            1             1           1             1
3       114          112           121         128           142
4        14            9            11          11            13
5        12           12            12          12            13
6        12           12            12          12            12
7    968000       962000       1063000      963000       1006600
8        51           51            51          51            51
9         3            3             3           3             3
10        4            4             4           4             4
11       11           11            11          11            11
12       12           NA             9           9             8
13      237          233           230         227           224
14       10            9             9           8             7
15       NA           NA            NA          NA            17
16       48           47            47          46            46
17       36           36            36          36            36
18       40           NA            NA          NA            52
19        3           NA            NA          NA            NA
20       34           35            36          37            38
21        1            1             1           1             1
22       NA           NA            NA          NA            NA
23       68           NA            NA          NA            NA
24       29           30            33          31            27
25       NA           NA            NA          NA            NA
26        2           NA             2           1             1
27       NA           NA            NA          NA             2
28       23           23            23          42            42
29       33           32            33          33            31
30       NA           NA            NA          NA            NA
...  ...          ...          ...          ...          ...
1411           NA           NA           NA           NA            NA
1412           86           NA           NA           NA            NA
1413           NA           NA           NA           NA            NA
1414           10           NA           NA           NA            NA
1415           58           56           60           61            53
1416          130          129          127          125           123
1417           25           NA           17           17            19
1418          423          400          381          364           346
1419           93           NA           94           96            95
1420           50           57           68           40            70
1421         1300         1200         1100         1100          1100
1422           68           64           62           59            57
1423         3241         3307         3374         3417          3453
1424           44           NA           48           46            45
1425           87           88           79           88            85
1426            0           NA            1           NA            NA
1427           NA           NA           NA           NA            NA
1428           NA           NA           NA           NA            NA
1429            7           NA           10           NA            NA
1430           63           65           72           70            68
1431           NA           36           36           33            40
1432           22           NA           27           NA            NA
1433            1            1            1            1            NA
1434            1           NA           NA           NA            NA
1435            4           NA           NA           NA            NA
1436 940687412500 927803912200 898077784900 964806000000 1051028000000
1437         1310         1330         1360         1380          1320
1438         2707         2767         2767         2868          2966
1439            2            3            1            1             1
1440            5            7            7           11            11
     2016          2017          2018          2019          2020
1      24000         22000       18000         8400          NA
2          1             1           1           NA          NA
3        148           157         174           NA          NA
4         13            14          15           NA          NA
5         13            13          13           NA          NA
6         12            12          12           NA          NA
7    1210000       1365000          NA           NA          NA
8         51            51          51           51          NA
9          3             3           3            3          NA
10         4             4           4            4          NA
11        11            11          11           11          NA
12         8             8           8           NA          NA
13       222           219         216           NA          NA
14         7             7           7            7           7
15        NA            NA          NA           NA          NA
16        46            46          46           46          46
17        36            36          36           36          36
18        NA            NA          NA           NA          NA
19        NA            NA          NA           NA          NA
20        38            39          39           39          40
21         1             1           1            1           1
22        NA            NA          NA           NA          NA
23        NA            NA          NA           NA          NA
24        28            30          33           NA          NA
25        NA            NA          NA           NA          NA
26         1             1          NA            2          NA
27         2            NA          NA           NA          NA
28        42            42          NA           NA          NA
29        31            31          29           29          28
30        NA            NA          NA           NA          NA
...  ...           ...           ...           ...           ...
1411            NA            NA            NA            NA NA
1412            NA            NA            NA            NA NA
1413            NA            NA            NA            NA NA
1414            NA            NA            NA            NA NA
1415            54            55            59            NA NA
1416           122           120           118           117 NA
1417            15            15            NA            17 NA
1418           330           315            NA            NA NA
1419            96            97            NA            NA NA
1420            46            52            56            NA NA
1421          1100          1000          1100          1100 NA
1422            55            53            51            49 NA
1423          3461          3462          3456          3479 NA
1424            39            35            NA            NA NA
1425            95            NA            NA            NA NA
1426            NA             0            NA            NA NA
1427            NA            NA            NA            NA NA
1428            NA            NA            19            NA NA
1429            NA            10            NA            NA NA
1430            NA            NA            NA            75 NA
1431            42            42            NA            NA NA
1432            NA            22            NA            NA NA
1433            NA            NA            NA             1 NA
1434            NA            NA            NA            NA NA
1435            NA            NA            NA            NA NA
1436 1135715548200 1259856164500 1328760612500 1454358980400 NA
1437          1270          1280          1400          1460 NA
1438          3068          3204          3315          3395 NA
1439             2             1             1            NA NA
1440            11            12            13            NA NA

In [86]:
head(donnee_fmi)
str(donnee_fmi)

  Indicator
1 National Accounts, Current Prices, Non-Seasonally Adjusted
2 Gross Domestic Product, Nominal, Domestic Currency
3 Household Consumption Expenditure, incl. NPISHs, Nominal, Domestic Currency
4 Government Consumption Expenditure, Nominal, Domestic Currency
5 Gross Fixed Capital Formation, Nominal, Domestic Currency
6 Change in Inventories, Nominal, Domestic Currency
  ...2     Base Year Scale    2004                2005
1 NA       NA        NA       ...                 ...
2 NGDP_XDC NA        Millions 5371304.9866449004  5814186.7828154294
3 NCP_XDC  NA        Millions 4296873.47909535    4655870.8980412995
4 NCGG_XDC NA        Millions 700281.035233467    748841.04489883804
5 NFI_XDC  NA        Millions 955809.39618684398  1086931.4170581501
6 NINV_XDC NA        Millions -45988.329670753701 30079.027875780401
  2006               2007               2008               2009
1 ...                ...                ...                ...
2 6195122.5431449804 6846791.1675585397 7590205.5561305303 7672183.5083290003
3 5056156.2170517305 5577325.6226699203 6346712.1025944808 6220093.37878762
4 819324.04056452203 940701.82          926099.47882518102 988796.95377736806
5 1291907.0623588301 1426925.4088176899 1713922.2067138401 1527203.3157945802
6 -117307.816830104  112602.89530358299 180091.76799702601 -45416.140030571099
  2010               2011                2012               2013
1 ...                ...                 ...                ...
2 8030950.8556799805 8436390.2785922997  9100358.9320069104 9367088.498763321
3 6395224.2118312502 6766064.0747498795  7081869.4851756599 7268246.3849652503
4 1088039.12540696   1208729.8396906399  1275312.45350631   1314685.3116335301
5 1494587.8675903999 1783351.8737647601  1886387.6884058202 2092144.7136075401
6 38272.650851368897 -79719.314991865598 385502.98387311702 225501.28744322501
  2014             2015     2016             2017     2018
1 ...              ...      ...              ...      ...
2 9775039          10508650 11283396         12191796 12907359
3 7259973          7631735  8078178          8582484  8920535
4 1440315          1502661  1583205          1662226  1774264
5 2316171          2440321  2722111          3172840  3385323
6 218602.978293422 276911   137466.312647999 462644   767873
  2019
1 ...
2 13814658.804999199
3 9464066.4151200801
4 1883282.9159144
5 3989720.4407436801
6 386895.04192137404

'data.frame':	24 obs. of  20 variables:
 $ Indicator: chr  "National Accounts, Current Prices, Non-Seasonally Adjusted" "Gross Domestic Product, Nominal, Domestic Currency" "Household Consumption Expenditure, incl. NPISHs, Nominal, Domestic Currency" "Government Consumption Expenditure, Nominal, Domestic Currency" ...
 $ ...2     : chr  NA "NGDP_XDC" "NCP_XDC" "NCGG_XDC" ...
 $ Base Year: chr  NA NA NA NA ...
 $ Scale    : chr  NA "Millions" "Millions" "Millions" ...
 $ 2004     : chr  "..." "5371304.9866449004" "4296873.47909535" "700281.035233467" ...
 $ 2005     : chr  "..." "5814186.7828154294" "4655870.8980412995" "748841.04489883804" ...
 $ 2006     : chr  "..." "6195122.5431449804" "5056156.2170517305" "819324.04056452203" ...
 $ 2007     : chr  "..." "6846791.1675585397" "5577325.6226699203" "940701.82" ...
 $ 2008     : chr  "..." "7590205.5561305303" "6346712.1025944808" "926099.47882518102" ...
 $ 2009     : chr  "..." "7672183.5083290003" "6220093.37878762" "988796.95377736806" ...
 $ 2010     : chr  "..." "8030950.8556799805" "6395224.2118312502" "1088039.12540696" ...
 $ 2011     : chr  "..." "8436390.2785922997" "6766064.0747498795" "1208729.8396906399" ...
 $ 2012     : chr  "..." "9100358.9320069104" "7081869.4851756599" "1275312.45350631" ...
 $ 2013     : chr  "..." "9367088.498763321" "7268246.3849652503" "1314685.3116335301" ...
 $ 2014     : chr  "..." "9775039" "7259973" "1440315" ...
 $ 2015     : chr  "..." "10508650" "7631735" "1502661" ...
 $ 2016     : chr  "..." "11283396" "8078178" "1583205" ...
 $ 2017     : chr  "..." "12191796" "8582484" "1662226" ...
 $ 2018     : chr  "..." "12907359" "8920535" "1774264" ...
 $ 2019     : chr  "..." "13814658.804999199" "9464066.4151200801" "1883282.9159144" ...

In [91]:
#mutate les variables dont le nom contient un nombre (ici les années)
t=donnee_fmi %>% mutate_at(vars(matches("\\d")),as.numeric)
str(t)

t=donnee_fmi=donnee_fmi %>% mutate_at(vars(matches("\\d\\d\\d\\d")),as.numeric)

str(t)

Warning message in mask$eval_all_mutate(quo):
"NAs introduits lors de la conversion automatique"Warning message in mask$eval_all_mutate(quo):
"NAs introduits lors de la conversion automatique"Warning message in mask$eval_all_mutate(quo):
"NAs introduits lors de la conversion automatique"Warning message in mask$eval_all_mutate(quo):
"NAs introduits lors de la conversion automatique"Warning message in mask$eval_all_mutate(quo):
"NAs introduits lors de la conversion automatique"Warning message in mask$eval_all_mutate(quo):
"NAs introduits lors de la conversion automatique"Warning message in mask$eval_all_mutate(quo):
"NAs introduits lors de la conversion automatique"Warning message in mask$eval_all_mutate(quo):
"NAs introduits lors de la conversion automatique"Warning message in mask$eval_all_mutate(quo):
"NAs introduits lors de la conversion automatique"Warning message in mask$eval_all_mutate(quo):
"NAs introduits lors de la conversion automatique"Warning message in mask$eval_all_mutate(quo):
"NAs introduits lors de la conversion automatique"Warning message in mask$eval_all_mutate(quo):
"NAs introduits lors de la conversion automatique"Warning message in mask$eval_all_mutate(quo):
"NAs introduits lors de la conversion automatique"Warning message in mask$eval_all_mutate(quo):
"NAs introduits lors de la conversion automatique"Warning message in mask$eval_all_mutate(quo):
"NAs introduits lors de la conversion automatique"Warning message in mask$eval_all_mutate(quo):
"NAs introduits lors de la conversion automatique"Warning message in mask$eval_all_mutate(quo):
"NAs introduits lors de la conversion automatique"

'data.frame':	24 obs. of  20 variables:
 $ Indicator: chr  "National Accounts, Current Prices, Non-Seasonally Adjusted" "Gross Domestic Product, Nominal, Domestic Currency" "Household Consumption Expenditure, incl. NPISHs, Nominal, Domestic Currency" "Government Consumption Expenditure, Nominal, Domestic Currency" ...
 $ ...2     : num  NA NA NA NA NA NA NA NA NA NA ...
 $ Base Year: chr  NA NA NA NA ...
 $ Scale    : chr  NA "Millions" "Millions" "Millions" ...
 $ 2004     : num  NA 5371305 4296873 700281 955809 ...
 $ 2005     : num  NA 5814187 4655871 748841 1086931 ...
 $ 2006     : num  NA 6195123 5056156 819324 1291907 ...
 $ 2007     : num  NA 6846791 5577326 940702 1426925 ...
 $ 2008     : num  NA 7590206 6346712 926099 1713922 ...
 $ 2009     : num  NA 7672184 6220093 988797 1527203 ...
 $ 2010     : num  NA 8030951 6395224 1088039 1494588 ...
 $ 2011     : num  NA 8436390 6766064 1208730 1783352 ...
 $ 2012     : num  NA 9100359 7081869 1275312 1886388 ...
 $ 2013     : num  NA 9367088 7268246 1314685 2092145 ...
 $ 2014     : num  NA 9775039 7259973 1440315 2316171 ...
 $ 2015     : num  NA 10508650 7631735 1502661 2440321 ...
 $ 2016     : num  NA 11283396 8078178 1583205 2722111 ...
 $ 2017     : num  NA 12191796 8582484 1662226 3172840 ...
 $ 2018     : num  NA 12907359 8920535 1774264 3385323 ...
 $ 2019     : num  NA 13814659 9464066 1883283 3989720 ...

Warning message in mask$eval_all_mutate(quo):
"NAs introduits lors de la conversion automatique"Warning message in mask$eval_all_mutate(quo):
"NAs introduits lors de la conversion automatique"Warning message in mask$eval_all_mutate(quo):
"NAs introduits lors de la conversion automatique"Warning message in mask$eval_all_mutate(quo):
"NAs introduits lors de la conversion automatique"Warning message in mask$eval_all_mutate(quo):
"NAs introduits lors de la conversion automatique"Warning message in mask$eval_all_mutate(quo):
"NAs introduits lors de la conversion automatique"Warning message in mask$eval_all_mutate(quo):
"NAs introduits lors de la conversion automatique"Warning message in mask$eval_all_mutate(quo):
"NAs introduits lors de la conversion automatique"Warning message in mask$eval_all_mutate(quo):
"NAs introduits lors de la conversion automatique"Warning message in mask$eval_all_mutate(quo):
"NAs introduits lors de la conversion automatique"Warning message in mask$eval_all_mutate(quo):
"NAs introduits lors de la conversion automatique"Warning message in mask$eval_all_mutate(quo):
"NAs introduits lors de la conversion automatique"Warning message in mask$eval_all_mutate(quo):
"NAs introduits lors de la conversion automatique"Warning message in mask$eval_all_mutate(quo):
"NAs introduits lors de la conversion automatique"Warning message in mask$eval_all_mutate(quo):
"NAs introduits lors de la conversion automatique"Warning message in mask$eval_all_mutate(quo):
"NAs introduits lors de la conversion automatique"

'data.frame':	24 obs. of  20 variables:
 $ Indicator: chr  "National Accounts, Current Prices, Non-Seasonally Adjusted" "Gross Domestic Product, Nominal, Domestic Currency" "Household Consumption Expenditure, incl. NPISHs, Nominal, Domestic Currency" "Government Consumption Expenditure, Nominal, Domestic Currency" ...
 $ ...2     : chr  NA "NGDP_XDC" "NCP_XDC" "NCGG_XDC" ...
 $ Base Year: chr  NA NA NA NA ...
 $ Scale    : chr  NA "Millions" "Millions" "Millions" ...
 $ 2004     : num  NA 5371305 4296873 700281 955809 ...
 $ 2005     : num  NA 5814187 4655871 748841 1086931 ...
 $ 2006     : num  NA 6195123 5056156 819324 1291907 ...
 $ 2007     : num  NA 6846791 5577326 940702 1426925 ...
 $ 2008     : num  NA 7590206 6346712 926099 1713922 ...
 $ 2009     : num  NA 7672184 6220093 988797 1527203 ...
 $ 2010     : num  NA 8030951 6395224 1088039 1494588 ...
 $ 2011     : num  NA 8436390 6766064 1208730 1783352 ...
 $ 2012     : num  NA 9100359 7081869 1275312 1886388 ...
 $ 2013     : num  NA 9367088 7268246 1314685 2092145 ...
 $ 2014     : num  NA 9775039 7259973 1440315 2316171 ...
 $ 2015     : num  NA 10508650 7631735 1502661 2440321 ...
 $ 2016     : num  NA 11283396 8078178 1583205 2722111 ...
 $ 2017     : num  NA 12191796 8582484 1662226 3172840 ...
 $ 2018     : num  NA 12907359 8920535 1774264 3385323 ...
 $ 2019     : num  NA 13814659 9464066 1883283 3989720 ...

## dplyr::group_by & summarise

![](http://ohi-science.org/data-science-training/img/rstudio-cheatsheet-group_by.png)
La plupart des opérations sur les données sont effectuées sur des groupes définis par des variables. group by () prend un data.frame existant et le convertit en un data.frame groupé où les opérations sont effectuées "par groupe".

ungroup () supprime le regroupement

In [112]:
fao_cdu %>% select(!contains(c("Code","Flag"))) %>% group_by(Item) %>% head()

fao_cdu %>% select(!contains(c("Code","Flag"))) %>% group_by(Item,Element) %>% 
mutate(moyenne=mean(Value,na.rm=TRUE)) %>% head(.,20)

  Domain Area    Element         Item                Year Unit   Value
1 Crops  Senegal Import Quantity Almonds, with shell 2014 tonnes 7
2 Crops  Senegal Import Quantity Almonds, with shell 2015 tonnes 2
3 Crops  Senegal Import Quantity Almonds, with shell 2016 tonnes 5
4 Crops  Senegal Import Quantity Almonds, with shell 2017 tonnes 6
5 Crops  Senegal Import Quantity Almonds, with shell 2018 tonnes 7
6 Crops  Senegal Stock Variation Almonds, with shell 2014 tonnes 6

   Domain Area    Element                       Item                Year Unit
1  Crops  Senegal Import Quantity               Almonds, with shell 2014 tonnes
2  Crops  Senegal Import Quantity               Almonds, with shell 2015 tonnes
3  Crops  Senegal Import Quantity               Almonds, with shell 2016 tonnes
4  Crops  Senegal Import Quantity               Almonds, with shell 2017 tonnes
5  Crops  Senegal Import Quantity               Almonds, with shell 2018 tonnes
6  Crops  Senegal Stock Variation               Almonds, with shell 2014 tonnes
7  Crops  Senegal Stock Variation               Almonds, with shell 2015 tonnes
8  Crops  Senegal Stock Variation               Almonds, with shell 2016 tonnes
9  Crops  Senegal Stock Variation               Almonds, with shell 2017 tonnes
10 Crops  Senegal Stock Variation               Almonds, with shell 2018 tonnes
11 Crops  Senegal Residuals                     Almonds, with shell 2014 tonnes
12 Crops  Senegal Residuals                     Almonds, with shell 2015 tonnes
13 Crops  Senegal Residuals                     Almonds, with shell 2016 tonnes
14 Crops  Senegal Residuals                     Almonds, with shell 2017 tonnes
15 Crops  Senegal Residuals                     Almonds, with shell 2018 tonnes
16 Crops  Senegal Food supply quantity (tonnes) Almonds, with shell 2014 tonnes
17 Crops  Senegal Food supply quantity (tonnes) Almonds, with shell 2015 tonnes
18 Crops  Senegal Food supply quantity (tonnes) Almonds, with shell 2016 tonnes
19 Crops  Senegal Food supply quantity (tonnes) Almonds, with shell 2017 tonnes
20 Crops  Senegal Food supply quantity (tonnes) Almonds, with shell 2018 tonnes
   Value moyenne
1  7     5.4
2  2     5.4
3  5     5.4
4  6     5.4
5  7     5.4
6  6     2.6
7  0     2.6
8  3     2.6
9  3     2.6
10 1     2.6
11 0     0.0
12 0     0.0
13 0     0.0
14 0     0.0
15 0     0.0
16 1     2.8
17 2     2.8
18 2     2.8
19 3     2.8
20 6     2.8

In [114]:
fao_cdu %>% select(!contains(c("Code","Flag"))) %>% group_by(Item,Element) %>% 
summarise(moyenne=mean(Value,na.rm=TRUE)) %>% head()

`summarise()` has grouped output by 'Item'. You can override using the `.groups` argument.

  Item                             Element                       moyenne
1 Almonds, with shell              Food supply quantity (tonnes) 2.8
2 Almonds, with shell              Import Quantity               5.4
3 Almonds, with shell              Residuals                     0.0
4 Almonds, with shell              Stock Variation               2.6
5 Anise, badian, fennel, coriander Food supply quantity (tonnes) 6.4
6 Anise, badian, fennel, coriander Import Quantity               6.4

In [98]:
fao_cdu %>% select(!contains(c("Code","Flag"))) %>% group_by(Item,Element) %>%
mutate(moyenne=mean(Value,na.rm=TRUE)) %>% 
ungroup() %>% mutate(moyenne1=mean(Value,na.rm=TRUE)) %>% head()

  Domain Area    Element         Item                Year Unit   Value moyenne
1 Crops  Senegal Import Quantity Almonds, with shell 2014 tonnes 7     5.4
2 Crops  Senegal Import Quantity Almonds, with shell 2015 tonnes 2     5.4
3 Crops  Senegal Import Quantity Almonds, with shell 2016 tonnes 5     5.4
4 Crops  Senegal Import Quantity Almonds, with shell 2017 tonnes 6     5.4
5 Crops  Senegal Import Quantity Almonds, with shell 2018 tonnes 7     5.4
6 Crops  Senegal Stock Variation Almonds, with shell 2014 tonnes 6     2.6
  moyenne1
1 24847.69
2 24847.69
3 24847.69
4 24847.69
5 24847.69
6 24847.69

summarise () crée un nouveau data.frame. Il aura une (ou plusieurs) lignes pour chaque combinaison
des variables de regroupement (group_by); s'il n'y a pas de variables de regroupement, la sortie aura une seule ligne résumant toutes les observations dans l'entrée. Il contiendra une colonne pour chaque regroupement
variable et une colonne pour chacune des statistiques récapitulatives que vous avez spécifiées.
summary () et summary () sont des synonymes.

![](http://ohi-science.org/data-science-training/img/rstudio-cheatsheet-summarise.png)

In [106]:
fao_cdu %>% select(!contains(c("Code","Flag"))) %>% group_by(Item,Element) %>%
  summarise(moyenne=mean(Value,na.rm=TRUE),
            n_obs=n())

`summarise()` has grouped output by 'Item'. You can override using the `.groups` argument.

    Item                             Element                       moyenne
1   Almonds, with shell              Food supply quantity (tonnes)     2.80
2   Almonds, with shell              Import Quantity                   5.40
3   Almonds, with shell              Residuals                         0.00
4   Almonds, with shell              Stock Variation                   2.60
5   Anise, badian, fennel, coriander Food supply quantity (tonnes)     6.40
6   Anise, badian, fennel, coriander Import Quantity                   6.40
7   Anise, badian, fennel, coriander Residuals                         0.00
8   Anise, badian, fennel, coriander Stock Variation                   0.00
9   Apples                           Export Quantity                   3.25
10  Apples                           Food supply quantity (tonnes) 10156.00
11  Apples                           Import Quantity               12833.00
12  Apples                           Loss                            384.80
13  Apples                           Residuals                         0.00
14  Apples                           Stock Variation                2289.40
15  Apricots                         Food supply quantity (tonnes)    10.20
16  Apricots                         Import Quantity                  10.20
17  Apricots                         Residuals                         0.00
18  Areca nuts                       Export Quantity                   0.00
19  Areca nuts                       Food supply quantity (tonnes)     0.00
20  Areca nuts                       Residuals                         0.00
21  Areca nuts                       Stock Variation                   0.00
22  Artichokes                       Food supply quantity (tonnes)     0.80
23  Artichokes                       Import Quantity                   2.00
24  Artichokes                       Residuals                         0.00
25  Asparagus                        Export Quantity                  13.00
26  Asparagus                        Food supply quantity (tonnes)     8.40
27  Asparagus                        Import Quantity                   8.60
28  Asparagus                        Loss                              0.00
29  Asparagus                        Production                        5.20
30  Asparagus                        Residuals                         0.00
... ...                              ...                           ...
564 Vegetables, fresh nes            Food supply quantity (tonnes)  11799.2
565 Vegetables, fresh nes            Import Quantity                  380.2
566 Vegetables, fresh nes            Loss                            2769.6
567 Vegetables, fresh nes            Processed                        738.6
568 Vegetables, fresh nes            Production                     33069.8
569 Vegetables, fresh nes            Residuals                          0.0
570 Walnuts, with shell              Export Quantity                  104.0
571 Walnuts, with shell              Food supply quantity (tonnes)      0.6
572 Walnuts, with shell              Import Quantity                    0.6
573 Walnuts, with shell              Residuals                        -20.6
574 Walnuts, with shell              Stock Variation                    0.0
575 Watermelons                      Export Quantity                13256.6
576 Watermelons                      Food supply quantity (tonnes) 214303.2
577 Watermelons                      Import Quantity                   25.0
578 Watermelons                      Loss                           20799.0
579 Watermelons                      Production                    248348.6
580 Watermelons                      Residuals                          0.0
581 Wheat                            Export Quantity                  542.6
582 Wheat                            Feed                              99.4
583 Wheat                            Import Quantity               595267.8
584 Wheat                            Loss                            5952.8
585 Wheat                            Processed                     590673.2
586 Wheat                            Residuals                          0.0
587 Wheat                            Stock Variation                -2000.0
588 Yams                             Export Quantity                   99.0
589 Yams                             Food supply quantity (tonnes)  55000.0
590 Yams                             Import Quantity                  101.4
591 Yams                             Production                     55070.0
592 Yams                             Residuals                          0.0
593 Yams                             Stock Variation                   92.4
    n_obs
1   5
2   5
3   5
4   5
5   5
6   5
7   5
8   5
9   4
10  5
11  5
12  5
13  5
14  5
15  5
16  5
17  5
18  1
19  5
20  5
21  5
22  5
23  2
24  5
25  2
26  5
27  5
28  5
29  5
30  5
... ...
564 5
565 5
566 5
567 5
568 5
569 5
570 1
571 5
572 5
573 5
574 5
575 5
576 5
577 2
578 5
579 5
580 5
581 5
582 5
583 5
584 5
585 5
586 5
587 5
588 4
589 5
590 5
591 5
592 5
593 5

## Les jointures (mutate-join & filter-join)

Les jointures de type mutate-join ajoutent des colonnes de y à x, correspondant aux lignes en fonction des clés:

* `inner_join(x,y)`: inclut toutes les lignes de x et y.

* `left_join(x,y)` : inclut toutes les lignes de x.

* `right_join(x,y)`:inclut toutes les lignes de y.

* `full_join (x,y)` : inclut toutes les lignes de x ou y.

Si une ligne de x correspond à plusieurs lignes de y, toutes les lignes de y seront renvoyées une fois pour chaque
ligne correspondante dans x.

![](https://data-lessons.github.io/gapminder-R/fig/dplyr-joins.png)

In [124]:
unique(fao_cdu$Element.Code)
cdu_1=fao_cdu %>%filter(Element.Code==5510) %>% select(Item,Element,Year,Prod=Value) %>% select(-Element)
head(cdu_1)

cdu_2=fao_cdu %>%filter(Element.Code==5610) %>% select(Item,Element,Year,Imp=Value) %>% select(-Element)
head(cdu_2)

 [1] 5610 5071 5166 5141 5910 5016 5510 5023 5520 5525 5165

  Item      Year Prod
1 Asparagus 2014 26
2 Asparagus 2015  0
3 Asparagus 2016  0
4 Asparagus 2017  0
5 Asparagus 2018  0
6 Avocados  2014  0

  Item                             Year Imp
1 Almonds, with shell              2014 7
2 Almonds, with shell              2015 2
3 Almonds, with shell              2016 5
4 Almonds, with shell              2017 6
5 Almonds, with shell              2018 7
6 Anise, badian, fennel, coriander 2014 4

In [128]:
cdu_3=cdu_1 %>% left_join(cdu_2,by=c("Item","Year"))
head(cdu_3)
nrow(cdu_1)
nrow(cdu_2)
nrow(cdu_3)

  Item      Year Prod Imp
1 Asparagus 2014 26    0
2 Asparagus 2015  0   10
3 Asparagus 2016  0   16
4 Asparagus 2017  0    1
5 Asparagus 2018  0   16
6 Avocados  2014  0    0

[1] 254

[1] 440

[1] 254

In [129]:
cdu_3=cdu_1 %>% right_join(cdu_2,by=c("Item","Year"))
head(cdu_3)
nrow(cdu_1)
nrow(cdu_2)
nrow(cdu_3)

  Item      Year Prod Imp
1 Asparagus 2014 26    0
2 Asparagus 2015  0   10
3 Asparagus 2016  0   16
4 Asparagus 2017  0    1
5 Asparagus 2018  0   16
6 Avocados  2014  0    0

[1] 254

[1] 440

[1] 440

In [130]:
cdu_3=cdu_1 %>% inner_join(cdu_2,by=c("Item","Year"))
head(cdu_3)
nrow(cdu_1)
nrow(cdu_2)
nrow(cdu_3)

  Item      Year Prod Imp
1 Asparagus 2014 26    0
2 Asparagus 2015  0   10
3 Asparagus 2016  0   16
4 Asparagus 2017  0    1
5 Asparagus 2018  0   16
6 Avocados  2014  0    0

[1] 254

[1] 440

[1] 187

In [131]:
cdu_3=cdu_1 %>% full_join(cdu_2,by=c("Item","Year"))
nrow(cdu_1)
nrow(cdu_2)
nrow(cdu_3)
cdu_3

[1] 254

[1] 440

[1] 507

    Item                                         Year Prod  Imp
1   Asparagus                                    2014    26     0
2   Asparagus                                    2015     0    10
3   Asparagus                                    2016     0    16
4   Asparagus                                    2017     0     1
5   Asparagus                                    2018     0    16
6   Avocados                                     2014     0     0
7   Avocados                                     2015     0     0
8   Avocados                                     2016     0    NA
9   Avocados                                     2017     0    NA
10  Avocados                                     2018     0     0
11  Bambara beans                                2014     0    NA
12  Bambara beans                                2015     0     0
13  Bambara beans                                2016     0    NA
14  Bambara beans                                2017     0     7
15  Bambara beans                                2018     0     8
16  Bananas                                      2014 35575 15567
17  Bananas                                      2015 36500  1440
18  Bananas                                      2016 37000     0
19  Bananas                                      2017 30000    NA
20  Bananas                                      2018 30541    20
21  Beans, green                                 2014 10500    33
22  Beans, green                                 2015 15500    42
23  Beans, green                                 2016 15000   135
24  Beans, green                                 2017 18700   595
25  Beans, green                                 2018 16400    22
26  Berries nes                                  2014     0    NA
27  Berries nes                                  2015     0    NA
28  Berries nes                                  2016     0    NA
29  Berries nes                                  2017     0     0
30  Berries nes                                  2018     0     0
... ...                                          ...  ...   ...
478 Sweet corn prep or preserved                 2014 NA       307
479 Sweet corn prep or preserved                 2015 NA       417
480 Sweet corn prep or preserved                 2016 NA       399
481 Sweet corn prep or preserved                 2017 NA       312
482 Sweet corn prep or preserved                 2018 NA       457
483 Tangerines, mandarins, clementines, satsumas 2014 NA       684
484 Tangerines, mandarins, clementines, satsumas 2015 NA       993
485 Tangerines, mandarins, clementines, satsumas 2016 NA       685
486 Tangerines, mandarins, clementines, satsumas 2017 NA       776
487 Tangerines, mandarins, clementines, satsumas 2018 NA      1651
488 Tea                                          2014 NA      5085
489 Tea                                          2015 NA      6952
490 Tea                                          2016 NA      7683
491 Tea                                          2017 NA      7234
492 Tea                                          2018 NA     11118
493 Vanilla                                      2014 NA         0
494 Vanilla                                      2015 NA        11
495 Vanilla                                      2016 NA         2
496 Vanilla                                      2017 NA        21
497 Vanilla                                      2018 NA         3
498 Walnuts, with shell                          2014 NA         1
499 Walnuts, with shell                          2015 NA         1
500 Walnuts, with shell                          2016 NA         0
501 Walnuts, with shell                          2017 NA         1
502 Walnuts, with shell                          2018 NA         0
503 Wheat                                        2014 NA    545226
504 Wheat                                        2015 NA    584362
505 Wheat                                        2016 NA    592159
506 Wheat                                        2017 NA    646073
507 Wheat                                        2018 NA    608519

In [133]:
cdu_3=cdu_2 %>% anti_join(cdu_1,by=c("Item","Year"))
nrow(cdu_1)
nrow(cdu_2)
nrow(cdu_3)
cdu_3

[1] 254

[1] 440

[1] 253

    Item                                         Year Imp
1   Almonds, with shell                          2014     7
2   Almonds, with shell                          2015     2
3   Almonds, with shell                          2016     5
4   Almonds, with shell                          2017     6
5   Almonds, with shell                          2018     7
6   Anise, badian, fennel, coriander             2014     4
7   Anise, badian, fennel, coriander             2015     2
8   Anise, badian, fennel, coriander             2016     9
9   Anise, badian, fennel, coriander             2017     2
10  Anise, badian, fennel, coriander             2018    15
11  Apples                                       2014  9078
12  Apples                                       2015 11342
13  Apples                                       2016 12374
14  Apples                                       2017 15567
15  Apples                                       2018 15804
16  Apricots                                     2014     4
17  Apricots                                     2015     4
18  Apricots                                     2016    10
19  Apricots                                     2017    14
20  Apricots                                     2018    19
21  Artichokes                                   2015     1
22  Artichokes                                   2018     3
23  Barley                                       2015     3
24  Barley                                       2017     8
25  Barley                                       2018    25
26  Beans, dry                                   2014    83
27  Beans, dry                                   2015   679
28  Beans, dry                                   2016   654
29  Beans, dry                                   2017   304
30  Beans, dry                                   2018   272
... ...                                          ...  ...
224 Sweet corn prep or preserved                 2014    307
225 Sweet corn prep or preserved                 2015    417
226 Sweet corn prep or preserved                 2016    399
227 Sweet corn prep or preserved                 2017    312
228 Sweet corn prep or preserved                 2018    457
229 Tangerines, mandarins, clementines, satsumas 2014    684
230 Tangerines, mandarins, clementines, satsumas 2015    993
231 Tangerines, mandarins, clementines, satsumas 2016    685
232 Tangerines, mandarins, clementines, satsumas 2017    776
233 Tangerines, mandarins, clementines, satsumas 2018   1651
234 Tea                                          2014   5085
235 Tea                                          2015   6952
236 Tea                                          2016   7683
237 Tea                                          2017   7234
238 Tea                                          2018  11118
239 Vanilla                                      2014      0
240 Vanilla                                      2015     11
241 Vanilla                                      2016      2
242 Vanilla                                      2017     21
243 Vanilla                                      2018      3
244 Walnuts, with shell                          2014      1
245 Walnuts, with shell                          2015      1
246 Walnuts, with shell                          2016      0
247 Walnuts, with shell                          2017      1
248 Walnuts, with shell                          2018      0
249 Wheat                                        2014 545226
250 Wheat                                        2015 584362
251 Wheat                                        2016 592159
252 Wheat                                        2017 646073
253 Wheat                                        2018 608519


## tidyr::gather & spread

![](https://www.codeproject.com/KB/recipes/5269229/rstudio-cheatsheet-reshaping-data-gather.png)

In [134]:
head(donnee_bm)

  Country Name Country Code
1 Sénégal      SEN
2 Sénégal      SEN
3 Sénégal      SEN
4 Sénégal      SEN
5 Sénégal      SEN
6 Sénégal      SEN
  Indicator Name
1 Internally displaced persons, total displaced by conflict and violence (number of people)
2 Exportations de marchandises vers les pays en développement du Moyen-Orient et d’Afrique du Nord (% des exportations totales de marchandises)
3 Indice du volume des exportations (2000=100)
4 Importations de marchandises des pays en développement d’Asie de l’Est et du Pacifique (% des importations totales de marchandises)
5 Taux des droits de douane, nation la plus favorisée, moyenne simple, produits de base (%)
6 Taux des droits de douane, nation la plus favorisée, moyenne simple, produits manufacturés (%)
  Indicator Code       1960     1961     1962     1963      1964
1 VC.IDP.TOCV                NA       NA       NA        NA         NA
2 TX.VAL.MRCH.R4.ZS    5.197133 5.220884 2.429150 0.6352087  0.5775578
3 TX.QTY.MRCH.XD.WD          NA       NA       NA        NA         NA
4 TM.VAL.MRCH.R1.ZS    5.568445 7.377049 5.764249 8.3679525 10.5201636
5 TM.TAX.TCOM.SM.FN.ZS       NA       NA       NA        NA         NA
6 TM.TAX.MANF.SM.FN.ZS       NA       NA       NA        NA         NA
  1965       ... 2011        2012          2013         2014
1         NA ... 24000.00000 22000.0000000 24000.000000 24000.000000
2  0.2354788 ...     2.77710     0.5600395     0.903348     1.187657
3         NA ...   113.86423   112.3854860   121.153762   127.691437
4 11.5384615 ...    13.67211     9.1627080    11.201373    11.339275
5         NA ...    11.97000    11.9700000    11.980000    11.980000
6         NA ...    11.87000    11.8700000    11.870000    11.870000
  2015         2016         2017         2018          2019 2020
1 24000.000000 24000.000000 22000.000000 18000.0000000 8400 NA
2     1.337134     1.098842     1.003992     0.9438729   NA NA
3   142.326747   148.185242   157.055589   174.1382185   NA NA
4    13.036677    13.309373    13.883524    15.1549097   NA NA
5    13.280000    13.280000    13.260000    13.2600000   NA NA
6    11.770000    11.770000    11.790000    11.7900000   NA NA

In [144]:

donnee_bm2=donnee_bm %>% gather(key = Annee, value = "Valeur",matches("\\d\\d"))

donnee_bm2

      Country Name Country Code
1     Sénégal      SEN
2     Sénégal      SEN
3     Sénégal      SEN
4     Sénégal      SEN
5     Sénégal      SEN
6     Sénégal      SEN
7     Sénégal      SEN
8     Sénégal      SEN
9     Sénégal      SEN
10    Sénégal      SEN
11    Sénégal      SEN
12    Sénégal      SEN
13    Sénégal      SEN
14    Sénégal      SEN
15    Sénégal      SEN
16    Sénégal      SEN
17    Sénégal      SEN
18    Sénégal      SEN
19    Sénégal      SEN
20    Sénégal      SEN
21    Sénégal      SEN
22    Sénégal      SEN
23    Sénégal      SEN
24    Sénégal      SEN
25    Sénégal      SEN
26    Sénégal      SEN
27    Sénégal      SEN
28    Sénégal      SEN
29    Sénégal      SEN
30    Sénégal      SEN
...   ...          ...
87811 Sénégal      SEN
87812 Sénégal      SEN
87813 Sénégal      SEN
87814 Sénégal      SEN
87815 Sénégal      SEN
87816 Sénégal      SEN
87817 Sénégal      SEN
87818 Sénégal      SEN
87819 Sénégal      SEN
87820 Sénégal      SEN
87821 Sénégal      SEN
87822 Sénégal      SEN
87823 Sénégal      SEN
87824 Sénégal      SEN
87825 Sénégal      SEN
87826 Sénégal      SEN
87827 Sénégal      SEN
87828 Sénégal      SEN
87829 Sénégal      SEN
87830 Sénégal      SEN
87831 Sénégal      SEN
87832 Sénégal      SEN
87833 Sénégal      SEN
87834 Sénégal      SEN
87835 Sénégal      SEN
87836 Sénégal      SEN
87837 Sénégal      SEN
87838 Sénégal      SEN
87839 Sénégal      SEN
87840 Sénégal      SEN
      Indicator Name
1     Internally displaced persons, total displaced by conflict and violence (number of people)
2     Exportations de marchandises vers les pays en développement du Moyen-Orient et d’Afrique du Nord (% des exportations totales de marchandises)
3     Indice du volume des exportations (2000=100)
4     Importations de marchandises des pays en développement d’Asie de l’Est et du Pacifique (% des importations totales de marchandises)
5     Taux des droits de douane, nation la plus favorisée, moyenne simple, produits de base (%)
6     Taux des droits de douane, nation la plus favorisée, moyenne simple, produits manufacturés (%)
7     Tourisme international, nombre d’arrivées
8     Population, femmes (% du total)
9     Population âgée de 65 et plus (% du total)
10    Population âgée de 40 à 44 ans, hommes (% de la population masculine)
11    Population âgée de 15 à 19 ans, garçons (% de la population masculine)
12    Women who were first married by age 15 (% of women ages 20-24)
13    Taux de mortalité, adultes, hommes (pour 1 000 hommes adultes)
14    Chômage, total (% de la population) (estimation modélisée OIT)
15    Chômage dans la population avec un niveau d’études supérieur, hommes (% de la population active masculine dans cette catégorie)
16    Taux de participation à la population active, total (% du total de la population âgée de 15 ans et plus) (estimation modélisée OIT)
17    Taux de participation à la population active, femmes (% de la population féminine de 15 à 64 ans) (estimation modélisée OIT)
18    Enfants actifs économiquement, qui étudient et travaillent, garçons (% de tous les garçons économiquement actifs de 7 à 14 ans)
19    Emploi d’enfants dans le secteur manufacturier, garçons (% des garçons économiquement actifs de 7 à 14 ans travaillant dans ce secteur)
20    Travailleurs salariés, hommes (% de la population masculine en emploi)
21    Chefs d’entreprise, hommes (% de la population masculine en emploi)
22    Taux de croissance moyen annualisé du niveau de vie par habitant, 40 % les plus pauvres de la population (%)
23    Poverty headcount ratio at $3.20 a day (2011 PPP) (% of population)
24    Out-of-pocket expenditure per capita (current US$)
25    Number of people spending more than 25% of household consumption or income on out-of-pocket health care expenditure
26    Prévalence de l’émaciation sévère, rapport poids/taille, filles (% des enfants de moins de 5 ans)
27    Mortality rate attributed to unintentional poisoning, female (per 100,000 female population)
28    People with basic handwashing facilities including soap and water, urban (% of urban population)
29    Risque de de dépenses appauvrissantes en cas de recours nécessaire à la chirurgie (% de la pop. à risque)
30    Lits d’hôpital (pour 1 000 personnes)
...   ...
87811 Proportion de femmes à des postes d’encadrement intermédiaire et supérieur (%)
87812 Emploi des enfants dans l’agriculture (% d’enfants économiquement actifs de 7 à 14 ans travaillant dans ce secteur)
87813 Multidimensional poverty headcount ratio, female (% of female population)
87814 Part des revenus détenus par le deuxième quartile de 20 %
87815 Current health expenditure per capita (current US$)
87816 Incidence de la tuberculose (pour 100 000 personnes)
87817 Prévalence de la malnutrition, taille selon l’âge, filles (% des enfants de mois de 5 ans)
87818 Ratio de décès maternel (estimation par modèle, pour 100 000 naissances vivantes)
87819 Femmes enceintes recevant des soins prénataux (%)
87820 Incidence du paludisme (pour 1 000 personnes à risque)
87821 Nouveaux cas d’infection par le VIH chez les adultes (15 ans et plus)
87822 Taux de mortalité infantile, moins de 5 ans, garçons (pour 1 000)
87823 Number of deaths ages 15-19 years
87824 Part des femmes qui estiment qu’un homme a le droit de frapper son épouse si celle-ci se dispute avec lui (%)
87825 Dépenses courantes consacrées à l’éducation, total (% du total des dépenses dans l’enseignement public)
87826 Niveau d éducation, doctorat ou diplôme équivalent, hommes de 25 ans et plus (%)
87827 Enseignants qualifiés dans le 1er cycle du secondaire (% de la population enseignante totale)
87828 Ratio élèves/enseignant, deuxième cycle du secondaire
87829 Niveau d éducation, achèvement du premier cycle des études secondaires au minimum, femmes de 25 ans et plus (%)
87830 Enseignants formés dans l’éducation primaire (% du total des enseignants)
87831 Taux d’inscription net en CP (% de la population officielle en âge d’aller à l’école)
87832 Niveau d’éducation, achèvement du cycle primaire au minimum, population de 25 ans et plus (%)
87833 Ratio filles/garçons des inscriptions au secondaire (%)
87834 Couverture des programmes d’assurance sociale dans le quintile le plus pauvre (% de la population)
87835 Couverture des allocations chômage et des programmes actifs du marché du travail dans le quintile le plus pauvre (% de la population)
87836 Taxes nettes sur les produits (unités de devises locales constantes)
87837 RNB par habitant, méthode Atlas ($ US courants)
87838 PIB par habitant, ($ PPA internationaux constants de 2011)
87839 Bénéfices tirés des minéraux (% du PIB)
87840 Épargne nette rajustée, en incluant les dommages causés par les émissions de particules (% du RNB)
      Indicator Code          Annee Valeur
1     VC.IDP.TOCV             1960          NA
2     TX.VAL.MRCH.R4.ZS       1960    5.197133
3     TX.QTY.MRCH.XD.WD       1960          NA
4     TM.VAL.MRCH.R1.ZS       1960    5.568445
5     TM.TAX.TCOM.SM.FN.ZS    1960          NA
6     TM.TAX.MANF.SM.FN.ZS    1960          NA
7     ST.INT.ARVL             1960          NA
8     SP.POP.TOTL.FE.ZS       1960   50.316036
9     SP.POP.65UP.TO.ZS       1960    2.622874
10    SP.POP.4044.MA.5Y       1960    4.612664
11    SP.POP.1519.MA.5Y       1960    9.572106
12    SP.M15.2024.FE.ZS       1960          NA
13    SP.DYN.AMRT.MA          1960  494.958000
14    SL.UEM.TOTL.ZS          1960          NA
15    SL.UEM.ADVN.MA.ZS       1960          NA
16    SL.TLF.CACT.ZS          1960          NA
17    SL.TLF.ACTI.FE.ZS       1960          NA
18    SL.TLF.0714.SW.MA.ZS    1960          NA
19    SL.MNF.0714.MA.ZS       1960          NA
20    SL.EMP.WORK.MA.ZS       1960          NA
21    SL.EMP.MPYR.MA.ZS       1960          NA
22    SI.SPR.PC40.ZG          1960          NA
23    SI.POV.LMIC             1960          NA
24    SH.XPD.OOPC.PC.CD       1960          NA
25    SH.UHC.OOPC.25.TO       1960          NA
26    SH.SVR.WAST.FE.ZS       1960          NA
27    SH.STA.POIS.P5.FE       1960          NA
28    SH.STA.HYGN.UR.ZS       1960          NA
29    SH.SGR.IRSK.ZS          1960          NA
30    SH.MED.BEDS.ZS          1960    1.313147
...   ...                     ...   ...
87811 SL.EMP.SMGT.FE.ZS       2020  NA
87812 SL.AGR.0714.ZS          2020  NA
87813 SI.POV.MDIM.FE          2020  NA
87814 SI.DST.02ND.20          2020  NA
87815 SH.XPD.CHEX.PC.CD       2020  NA
87816 SH.TBS.INCD             2020  NA
87817 SH.STA.STNT.FE.ZS       2020  NA
87818 SH.STA.MMRT             2020  NA
87819 SH.STA.ANVC.ZS          2020  NA
87820 SH.MLR.INCD.P3          2020  NA
87821 SH.HIV.INCD             2020  NA
87822 SH.DYN.MORT.MA          2020  NA
87823 SH.DTH.1519             2020  NA
87824 SG.VAW.ARGU.ZS          2020  NA
87825 SE.XPD.CTOT.ZS          2020  NA
87826 SE.TER.CUAT.DO.MA.ZS    2020  NA
87827 SE.SEC.TCAQ.LO.ZS       2020  NA
87828 SE.SEC.ENRL.UP.TC.ZS    2020  NA
87829 SE.SEC.CUAT.LO.FE.ZS    2020  NA
87830 SE.PRM.TCAQ.ZS          2020  NA
87831 SE.PRM.NINT.ZS          2020  NA
87832 SE.PRM.CUAT.ZS          2020  NA
87833 SE.ENR.SECO.FM.ZS       2020  NA
87834 per_si_allsi.cov_q1_tot 2020  NA
87835 per_lm_alllm.cov_q1_tot 2020  NA
87836 NY.TAX.NIND.KN          2020  NA
87837 NY.GNP.PCAP.CD          2020  NA
87838 NY.GDP.PCAP.PP.KD       2020  NA
87839 NY.GDP.MINR.RT.ZS       2020  NA
87840 NY.ADJ.SVNG.GN.ZS       2020  NA

In [145]:
donnee_bm2 %>% spread(key="Annee",value="Valeur")

     Country Name Country Code
1    Sénégal      SEN
2    Sénégal      SEN
3    Sénégal      SEN
4    Sénégal      SEN
5    Sénégal      SEN
6    Sénégal      SEN
7    Sénégal      SEN
8    Sénégal      SEN
9    Sénégal      SEN
10   Sénégal      SEN
11   Sénégal      SEN
12   Sénégal      SEN
13   Sénégal      SEN
14   Sénégal      SEN
15   Sénégal      SEN
16   Sénégal      SEN
17   Sénégal      SEN
18   Sénégal      SEN
19   Sénégal      SEN
20   Sénégal      SEN
21   Sénégal      SEN
22   Sénégal      SEN
23   Sénégal      SEN
24   Sénégal      SEN
25   Sénégal      SEN
26   Sénégal      SEN
27   Sénégal      SEN
28   Sénégal      SEN
29   Sénégal      SEN
30   Sénégal      SEN
...  ...          ...
1411 Sénégal      SEN
1412 Sénégal      SEN
1413 Sénégal      SEN
1414 Sénégal      SEN
1415 Sénégal      SEN
1416 Sénégal      SEN
1417 Sénégal      SEN
1418 Sénégal      SEN
1419 Sénégal      SEN
1420 Sénégal      SEN
1421 Sénégal      SEN
1422 Sénégal      SEN
1423 Sénégal      SEN
1424 Sénégal      SEN
1425 Sénégal      SEN
1426 Sénégal      SEN
1427 Sénégal      SEN
1428 Sénégal      SEN
1429 Sénégal      SEN
1430 Sénégal      SEN
1431 Sénégal      SEN
1432 Sénégal      SEN
1433 Sénégal      SEN
1434 Sénégal      SEN
1435 Sénégal      SEN
1436 Sénégal      SEN
1437 Sénégal      SEN
1438 Sénégal      SEN
1439 Sénégal      SEN
1440 Sénégal      SEN
     Indicator Name
1    Abonnements à la téléphonie fixe
2    Abonnements à la téléphonie fixe (pour 100 habitants)
3    Abonnements à la téléphonie mobile
4    Abonnements à la téléphonie mobile (pour 100 habitants)
5    Abonnements aux services d’accès haut débit sur ligne fixe
6    Abonnements aux services d’accès haut débit sur ligne fixe (pour 100 habitants)
7    Accès à des combustibles et techniques de cuisson propres (% de la population)
8    Accès à des méthodes de planification familiale modernes (% des femmes mariées qui souhaitent y recourir)
9    Accès à l’électricité (% de la population)
10   Accès à l’électricité, zones rurales (% de la population rurale)
11   Accès à l’électricité, zones urbaines (% de la population urbaine)
12   Accession à l’enseignement secondaire (%)
13   Accession à l’enseignement secondaire, filles (%)
14   Accession à l’enseignement secondaire, garçons (%)
15   Account ownership at a financial institution or with a mobile-money-service provider (% of population ages 15+)
16   Account ownership at a financial institution or with a mobile-money-service provider, female (% of population ages 15+)
17   Account ownership at a financial institution or with a mobile-money-service provider, male (% of population ages 15+)
18   Account ownership at a financial institution or with a mobile-money-service provider, older adults (% of population ages 25+)
19   Account ownership at a financial institution or with a mobile-money-service provider, poorest 40% (% of population ages 15+)
20   Account ownership at a financial institution or with a mobile-money-service provider, primary education or less (% of population ages 15+)
21   Account ownership at a financial institution or with a mobile-money-service provider, richest 60% (% of population ages 15+)
22   Account ownership at a financial institution or with a mobile-money-service provider, secondary education or more (% of population ages 15+)
23   Account ownership at a financial institution or with a mobile-money-service provider, young adults (% of population ages 15-24)
24   Accumulation nette de passifs (% du PIB)
25   Accumulation nette de passifs (monnaie locale courante)
26   Acquisition nette d’actifs financiers (% du PIB)
27   Acquisition nette d’actifs financiers (monnaie locale courante)
28   Actes de décès mentionnant la cause du décès (%)
29   Actions transigées, valeur totale ($ US courants)
30   Actions transigées, valeur totale (% du PIB)
...  ...
1411 Utilisation d’énergie (en kg d’équivalent pétrole) pour 1 000 $ de PIB (PPA constants de 2011)
1412 Utilisation d’énergie (kg d’équivalent pétrole par habitant)
1413 Utilisation de moustiquaires de lits avec insecticide (% de la population de moins de 5 ans)
1414 Utilisation des crédits du FMI (Dette en cours et décaissée, $ US courants)
1415 Utilisation du préservatif, population de 15 à 24 ans, femmes (% des femmes de 15 à 24 ans)
1416 Utilisation du préservatif, population de 15 à 24 ans, hommes (% des hommes de 15 à 24 ans)
1417 Vaccination, hépatite B (% des enfants âgés d’un an)
1418 Valeur actuelle de la dette extérieure ($ US courants)
1419 Valeur actuelle de la dette extérieure (% des exportations de biens, de services et de revenus)
1420 Valeur actuelle de la dette extérieure (% du RNB)
1421 Valeur ajoutée à l’agriculture par travailleur ($ US constants de 2010)
1422 Valeur ajoutée brute au coût des facteurs ($ US constants de 2010)
1423 Valeur ajoutée brute au coût des facteurs ($ US courants)
1424 Valeur ajoutée brute au coût des facteurs (unités de devises locales constantes)
1425 Valeur ajoutée brute au coût des facteurs (unités de devises locales courantes)
1426 Variations des inventaires ($ US courants)
1427 Variations des inventaires (unités de devises locales constantes)
1428 Variations des inventaires (unités de devises locales courantes)
1429 Variations des réserves nettes (BDP, $ US courants)
1430 Women Business and the Law Index Score (scale 1-100)
1431 Women making their own informed decisions regarding sexual relations, contraceptive use and reproductive health care  (% of women age 15-49)
1432 Women who were first married by age 15 (% of women ages 20-24)
1433 Young people (ages 15-24) newly infected with HIV
1434 Zones marines protégées (% des eaux du territoire)
1435 Zones protégées à l'échelle nationale (% du territoire total)
1436 Zones rurales dont l’altitude est < à 5 m (% de la superficie totale)
1437 Zones rurales dont l’altitude est < à 5 m (km2)
1438 Zones terrestres et marines protégées (% du territoire total)
1439 Zones urbaines dont l’altitude est < à 5 m (% de la superficie totale)
1440 Zones urbaines dont l’altitude est < à 5 m (km2)
     Indicator Code       1960        1961        1962        1963
1    IT.MLT.MAIN          9494.000000 9494.000000 9494.000000 9494.000000
2    IT.MLT.MAIN.P2          0.296063    0.296063    0.296063    0.296063
3    IT.CEL.SETS             0.000000          NA          NA          NA
4    IT.CEL.SETS.P2          0.000000          NA          NA          NA
5    IT.NET.BBND                   NA          NA          NA          NA
6    IT.NET.BBND.P2                NA          NA          NA          NA
7    EG.CFT.ACCS.ZS                NA          NA          NA          NA
8    SH.FPL.SATM.ZS                NA          NA          NA          NA
9    EG.ELC.ACCS.ZS                NA          NA          NA          NA
10   EG.ELC.ACCS.RU.ZS             NA          NA          NA          NA
11   EG.ELC.ACCS.UR.ZS             NA          NA          NA          NA
12   SE.SEC.PROG.ZS                NA          NA          NA          NA
13   SE.SEC.PROG.FE.ZS             NA          NA          NA          NA
14   SE.SEC.PROG.MA.ZS             NA          NA          NA          NA
15   FX.OWN.TOTL.ZS                NA          NA          NA          NA
16   FX.OWN.TOTL.FE.ZS             NA          NA          NA          NA
17   FX.OWN.TOTL.MA.ZS             NA          NA          NA          NA
18   FX.OWN.TOTL.OL.ZS             NA          NA          NA          NA
19   FX.OWN.TOTL.40.ZS             NA          NA          NA          NA
20   FX.OWN.TOTL.PL.ZS             NA          NA          NA          NA
21   FX.OWN.TOTL.60.ZS             NA          NA          NA          NA
22   FX.OWN.TOTL.SO.ZS             NA          NA          NA          NA
23   FX.OWN.TOTL.YG.ZS             NA          NA          NA          NA
24   GC.LBL.TOTL.GD.ZS             NA          NA          NA          NA
25   GC.LBL.TOTL.CN                NA          NA          NA          NA
26   GC.AST.TOTL.GD.ZS             NA          NA          NA          NA
27   GC.AST.TOTL.CN                NA          NA          NA          NA
28   SP.REG.DTHS.ZS                NA          NA          NA          NA
29   CM.MKT.TRAD.CD                NA          NA          NA          NA
30   CM.MKT.TRAD.GD.ZS             NA          NA          NA          NA
...  ...                  ...         ...         ...         ...
1411 EG.USE.COMM.GD.PP.KD        NA          NA          NA           NA
1412 EG.USE.PCAP.KG.OE           NA          NA          NA           NA
1413 SH.MLR.NETS.ZS              NA          NA          NA           NA
1414 DT.DOD.DIMF.CD              NA          NA          NA           NA
1415 SH.CON.1524.FE.ZS           NA          NA          NA           NA
1416 SH.CON.1524.MA.ZS           NA          NA          NA           NA
1417 SH.IMM.HEPB                 NA          NA          NA           NA
1418 DT.DOD.PVLX.CD              NA          NA          NA           NA
1419 DT.DOD.PVLX.EX.ZS           NA          NA          NA           NA
1420 DT.DOD.PVLX.GN.ZS           NA          NA          NA           NA
1421 NV.AGR.TOTL.KD       977382474   837434673   932707410   1029908766
1422 NY.GDP.FCST.KD              NA          NA          NA           NA
1423 NY.GDP.FCST.CD              NA          NA          NA           NA
1424 NY.GDP.FCST.KN              NA          NA          NA           NA
1425 NY.GDP.FCST.CN              NA          NA          NA           NA
1426 NE.GDI.STKB.CD              NA          NA          NA           NA
1427 NE.GDI.STKB.KN              NA          NA          NA           NA
1428 NE.GDI.STKB.CN              NA          NA          NA           NA
1429 BN.RES.INCL.CD              NA          NA          NA           NA
1430 SG.LAW.INDX                 NA          NA          NA           NA
1431 SG.DMK.SRCR.FN.ZS           NA          NA          NA           NA
1432 SP.M15.2024.FE.ZS           NA          NA          NA           NA
1433 SH.HIV.INCD.YG              NA          NA          NA           NA
1434 ER.MRN.PTMR.ZS              NA          NA          NA           NA
1435 ER.LND.PTLD.ZS              NA          NA          NA           NA
1436 AG.LND.EL5M.RU.ZS           NA          NA          NA           NA
1437 AG.LND.EL5M.RU.K2           NA          NA          NA           NA
1438 ER.PTD.TOTL.ZS              NA          NA          NA           NA
1439 AG.LND.EL5M.UR.ZS           NA          NA          NA           NA
1440 AG.LND.EL5M.UR.K2           NA          NA          NA           NA
     1964        1965         ... 2011               2012
1    9494.000000 10000.000000 ...  346406.0000000      340019.000000
2       0.296063     0.271527 ...       2.6577500           2.537080
3             NA     0.000000 ... 9352870.0000000    11470600.000000
4             NA     0.000000 ...      71.7585000          85.589100
5             NA           NA ...   92713.0000000       95561.000000
6             NA           NA ...       0.7113270           0.713036
7             NA           NA ...      32.0100000          31.650000
8             NA           NA ...      28.0000000                 NA
9             NA           NA ...      56.5000000          56.500000
10            NA           NA ...      31.7188668          31.921116
11            NA           NA ...      87.8000000          87.027016
12            NA           NA ...      92.8709800          91.961310
13            NA           NA ...      91.8315300          90.910230
14            NA           NA ...      93.9470000          93.083520
15            NA           NA ...       5.8211412                 NA
16            NA           NA ...       5.4504418                 NA
17            NA           NA ...       6.2365360                 NA
18            NA           NA ...       8.7367516                 NA
19            NA           NA ...       2.8096883                 NA
20            NA           NA ...       4.5985041                 NA
21            NA           NA ...       7.8242278                 NA
22            NA           NA ...      14.1594667                 NA
23            NA           NA ...       0.4295527                 NA
24            NA           NA ...              NA                 NA
25            NA           NA ...              NA                 NA
26            NA           NA ...              NA                 NA
27            NA           NA ...              NA                 NA
28            NA           NA ...              NA                 NA
29            NA           NA ...              NA                 NA
30            NA           NA ...              NA                 NA
...  ...         ...              ...                ...
1411         NA           NA  ...           114.9821           108.5216
1412         NA           NA  ...           311.2630           300.3243
1413         NA           NA  ...            34.5000                 NA
1414         NA           NA  ...     446845551.9000     441998825.2000
1415         NA           NA  ...             6.1000                 NA
1416         NA           NA  ...            56.6000                 NA
1417         NA           NA  ...            92.0000            91.0000
1418         NA           NA  ...                 NA                 NA
1419         NA           NA  ...                 NA                 NA
1420         NA           NA  ...                 NA                 NA
1421 1053583977   1129857877  ...    2160512524.5394    2380123643.4295
1422         NA           NA  ...   14762692413.4801   15637598622.2721
1423         NA           NA  ...   16117079081.1898   16115985191.4471
1424         NA           NA  ... 7542229582200.0000 7989217388000.0000
1425         NA           NA  ... 7595150953100.0000 8228117770200.0000
1426         NA     -7232317  ...    -168746219.2991     745524665.7421
1427         NA  36854981034  ...   16317445100.0000  101920510700.0000
1428         NA  -1772358141  ...  -79521419600.0000  380632314900.0000
1429         NA           NA  ...     -47441944.8794      99873439.2853
1430         NA           NA  ...            63.8000            63.8000
1431         NA           NA  ...            13.2000                 NA
1432         NA           NA  ...            12.0000                 NA
1433         NA           NA  ...           500.0000           500.0000
1434         NA           NA  ...                 NA                 NA
1435         NA           NA  ...                 NA                 NA
1436         NA           NA  ...                 NA                 NA
1437         NA           NA  ...                 NA                 NA
1438         NA           NA  ...                 NA                 NA
1439         NA           NA  ...                 NA                 NA
1440         NA           NA  ...                 NA                 NA
     2013               2014                2015
1      343718.000000      311945.000000           300219.0000000
2           2.493890           2.200710                2.0593300
3    13133800.000000    14379700.000000         14959500.0000000
4          95.293600         101.446000              102.6140000
5      106733.000000      103362.000000           100611.0000000
6           0.774414           0.729199                0.6901350
7          31.640000          31.680000               31.8200000
8          34.200000          42.600000               43.6000000
9          57.000000          61.000000               60.5000000
10         31.780645          41.014954               38.1357301
11         87.800000          85.000000               86.9000000
12         90.883600          89.995620               76.5084600
13         89.153600          89.037450               74.7239400
14         92.788180          91.056480               78.4721000
15                NA          15.424572                       NA
16                NA          11.399550                       NA
17                NA          19.926502                       NA
18                NA          19.940147                       NA
19                NA           4.392000                       NA
20                NA          11.221681                       NA
21                NA          22.721033                       NA
22                NA          27.275562                       NA
23                NA           6.750812                       NA
24                NA                 NA                3.0904067
25                NA                 NA     324760024468.9660034
26                NA                 NA               -0.7879217
27                NA                 NA     -82799931642.0000000
28                NA                 NA                       NA
29                NA                 NA                       NA
30                NA                 NA                       NA
...  ...                ...                 ...
1411            97.3305            97.34298              NA
1412           269.3105           279.21059              NA
1413            45.8000            43.20000            55.4
1414     437546954.5000     394893541.80000     344232104.4
1415                 NA                  NA              NA
1416                 NA                  NA              NA
1417            92.0000            89.00000            89.0
1418                 NA                  NA              NA
1419                 NA                  NA              NA
1420                 NA                  NA              NA
1421    2425059800.0877    2464302309.25092    2726536636.6
1422   16188342422.1225   17244603661.63423   18294048035.5
1423   17206214812.6866   17843246064.41262   15873953441.7
1424 8270591277200.0000 8810233000000.00000 9346392000000.0
1425 8498142613500.0010 8810233000000.00000 9384867000000.0
1426     355165678.0042     432775373.65017     464150151.3
1427   94381709300.0000  213686000000.00000  374763000000.0
1428  175416186300.0000  213686000000.00000  274411000000.0
1429      88150053.4199      64713366.21692     209235666.4
1430            63.8000            63.80000            63.8
1431                 NA                  NA             7.1
1432             8.6000             8.70000             8.5
1433           500.0000           500.00000           500.0
1434                 NA                  NA              NA
1435                 NA                  NA              NA
1436                 NA                  NA              NA
1437                 NA                  NA              NA
1438                 NA                  NA              NA
1439                 NA                  NA              NA
1440                 NA                  NA              NA
     2016                 2017                  2018
1          285933.000000        290636.000000         302243.000000
2               1.907040             1.884880              1.906380
3        15186500.000000      15758400.000000       16559900.000000
4             101.287000           102.199000            104.451000
5           98353.000000        111795.000000         129820.000000
6               0.655970             0.725030              0.818830
7              31.650000                   NA                    NA
8              47.300000            53.000000                    NA
9              64.500000            61.700000             66.959450
10             44.500237            35.372548             44.216976
11             87.700000            91.700000             92.408348
12             72.975420                   NA                    NA
13             71.016260                   NA                    NA
14             75.280230                   NA                    NA
15                    NA            42.344017                    NA
16                    NA            38.449608                    NA

In [156]:
names(donnee_bm2)=gsub(" ","_",names(donnee_bm2))
head(donnee_bm2)

  Country_Name Country_Code
1 Sénégal      SEN
2 Sénégal      SEN
3 Sénégal      SEN
4 Sénégal      SEN
5 Sénégal      SEN
6 Sénégal      SEN
  Indicator_Name
1 Internally displaced persons, total displaced by conflict and violence (number of people)
2 Exportations de marchandises vers les pays en développement du Moyen-Orient et d’Afrique du Nord (% des exportations totales de marchandises)
3 Indice du volume des exportations (2000=100)
4 Importations de marchandises des pays en développement d’Asie de l’Est et du Pacifique (% des importations totales de marchandises)
5 Taux des droits de douane, nation la plus favorisée, moyenne simple, produits de base (%)
6 Taux des droits de douane, nation la plus favorisée, moyenne simple, produits manufacturés (%)
  Indicator_Code       Annee Valeur
1 VC.IDP.TOCV          1960        NA
2 TX.VAL.MRCH.R4.ZS    1960  5.197133
3 TX.QTY.MRCH.XD.WD    1960        NA
4 TM.VAL.MRCH.R1.ZS    1960  5.568445
5 TM.TAX.TCOM.SM.FN.ZS 1960        NA
6 TM.TAX.MANF.SM.FN.ZS 1960        NA

In [157]:
donnee_bm2 %>% select(-Indicator_Name) %>% spread(key="Indicator_Code",value="Valeur")

    Country_Name Country_Code Annee AG.AGR.TRAC.NO AG.CON.FERT.PT.ZS
1   Sénégal      SEN          1960   NA            NA
2   Sénégal      SEN          1961  190            NA
3   Sénégal      SEN          1962  170            NA
4   Sénégal      SEN          1963  180            NA
5   Sénégal      SEN          1964  210            NA
6   Sénégal      SEN          1965  250            NA
7   Sénégal      SEN          1966  250            NA
8   Sénégal      SEN          1967  250            NA
9   Sénégal      SEN          1968  270            NA
10  Sénégal      SEN          1969  280            NA
11  Sénégal      SEN          1970  300            NA
12  Sénégal      SEN          1971  310            NA
13  Sénégal      SEN          1972  330            NA
14  Sénégal      SEN          1973  340            NA
15  Sénégal      SEN          1974  360            NA
16  Sénégal      SEN          1975  370            NA
17  Sénégal      SEN          1976  380            NA
18  Sénégal      SEN          1977  400            NA
19  Sénégal      SEN          1978  420            NA
20  Sénégal      SEN          1979  440            NA
21  Sénégal      SEN          1980  460            NA
22  Sénégal      SEN          1981  460            NA
23  Sénégal      SEN          1982  460            NA
24  Sénégal      SEN          1983  460            NA
25  Sénégal      SEN          1984  460            NA
26  Sénégal      SEN          1985  460            NA
27  Sénégal      SEN          1986  470            NA
28  Sénégal      SEN          1987  470            NA
29  Sénégal      SEN          1988  480            NA
30  Sénégal      SEN          1989  480            NA
... ...          ...          ...   ...            ...
32  Sénégal      SEN          1991  500                   NA
33  Sénégal      SEN          1992  550                   NA
34  Sénégal      SEN          1993  550                   NA
35  Sénégal      SEN          1994  550                   NA
36  Sénégal      SEN          1995  550                   NA
37  Sénégal      SEN          1996  560                   NA
38  Sénégal      SEN          1997  570                   NA
39  Sénégal      SEN          1998  580                   NA
40  Sénégal      SEN          1999  600                   NA
41  Sénégal      SEN          2000  609                   NA
42  Sénégal      SEN          2001  618                   NA
43  Sénégal      SEN          2002  627             7.736129
44  Sénégal      SEN          2003  636             6.780148
45  Sénégal      SEN          2004  645             7.520405
46  Sénégal      SEN          2005   NA             6.536316
47  Sénégal      SEN          2006   NA             3.586000
48  Sénégal      SEN          2007   NA             3.289888
49  Sénégal      SEN          2008   NA             3.881068
50  Sénégal      SEN          2009   NA            12.421235
51  Sénégal      SEN          2010   NA            10.879232
52  Sénégal      SEN          2011   NA             7.637627
53  Sénégal      SEN          2012   NA             8.368675
54  Sénégal      SEN          2013   NA            16.508333
55  Sénégal      SEN          2014   NA            13.914815
56  Sénégal      SEN          2015   NA            14.034946
57  Sénégal      SEN          2016   NA             7.956061
58  Sénégal      SEN          2017   NA                   NA
59  Sénégal      SEN          2018   NA                   NA
60  Sénégal      SEN          2019   NA                   NA
61  Sénégal      SEN          2020   NA                   NA
    AG.CON.FERT.ZS AG.LND.AGRI.K2 AG.LND.AGRI.ZS AG.LND.ARBL.HA
1   NA                NA                NA            NA
2   NA             86470          44.91248       2933000
3   NA             86470          44.91248       2933000
4   NA             87470          45.43188       3033000
5   NA             87470          45.43188       3033000
6   NA             88470          45.95128       3132000
7   NA             88470          45.95128       3132000
8   NA             89470          46.47068       3232000
9   NA             91170          47.35366       3401000
10  NA             89030          46.24214       3187000
11  NA             88640          46.03958       3148000
12  NA             89460          46.46549       3229000
13  NA             89460          46.46549       3229000
14  NA             89960          46.72519       3279000
15  NA             90460          46.98489       3329000
16  NA             90460          46.98489       3328000
17  NA             90450          46.97969       3326000
18  NA             88440          45.93570       3124000
19  NA             88430          45.93050       3123000
20  NA             88420          45.92531       3122000
21  NA             88410          45.92012       3121000
22  NA             88400          45.91492       3120000
23  NA             88390          45.90973       3118000
24  NA             88380          45.90453       3116000
25  NA             88370          45.89934       3114000
26  NA             88360          45.89415       3110000
27  NA             88340          45.88376       3107000
28  NA             88320          45.87337       3104000
29  NA             88300          45.86298       3098000
30  NA             88270          45.84740       3094000
... ...            ...            ...            ...
32         NA      87090          45.23451       2973000
33         NA      87800          45.60328       3044000
34         NA      88180          45.80065       3082000
35         NA      89150          46.30447       3178000
36         NA      88150          45.78507       3077000
37         NA      89070          46.26292       3217000
38         NA      86280          44.81380       2938000
39         NA      83900          43.57762       2685000
40         NA      91120          47.32769       3407000
41         NA      90270          46.88620       3322000
42         NA      87990          45.70197       3099000
43  11.794426      87500          45.44746       3050000
44  10.938608      86320          44.83457       2932000
45  12.711751      86870          45.12024       2987000
46   9.866283      87760          45.58251       3126000
47   2.308886      84880          44.08664       2836000
48   2.145965      85030          44.16455       2850000
49   2.303039      92750          48.17431       3620000
50   6.371802      94880          49.28063       3830000
51   8.202368      94580          49.12481       3800000
52   6.827576      89650          46.56417       3300000
53  10.524242      89650          46.56417       3300000
54  12.381250      88680          46.06035       3200000
55  11.740625      88680          46.06035       3200000
56  16.315625      88680          46.06035       3200000
57  16.409375      88680          46.06035       3200000
58         NA         NA                NA            NA
59         NA         NA                NA            NA
60         NA         NA                NA            NA
61         NA         NA                NA            NA
    AG.LND.ARBL.HA.PC ... TX.VAL.TRAN.ZS.WT TX.VAL.TRVL.ZS.WT VC.BTL.DETH
1          NA         ...       NA                NA          NA
2   0.8900615         ...       NA                NA          NA
3   0.8660077         ...       NA                NA          NA
4   0.8711377         ...       NA                NA          NA
5   0.8471501         ...       NA                NA          NA
6   0.8504223         ...       NA                NA          NA
7   0.8265198         ...       NA                NA          NA
8   0.8287936         ...       NA                NA          NA
9   0.8472628         ...       NA                NA          NA
10  0.7710505         ...       NA                NA          NA
11  0.7394002         ...       NA                NA          NA
12  0.7359477         ...       NA                NA          NA
13  0.7139236         ...       NA                NA          NA
14  0.7035386         ...       NA                NA          NA
15  0.6939483         ... 18.53428          43.14421          NA
16  0.6750718         ... 32.16057          43.56553          NA
17  0.6576530         ... 29.42524          49.25909          NA
18  0.6029126         ... 27.11075          50.92295          NA
19  0.5885034         ... 30.14455          49.08016          NA
20  0.5739956         ... 32.10368          55.60579          NA
21  0.5590019         ... 33.60198          51.59456          NA
22  0.5435120         ... 23.60663          35.31529          NA
23  0.5276037         ... 25.69077          37.52205          NA
24  0.5116944         ... 21.64806          40.30204          NA
25  0.4960634         ... 21.09043          42.78116          NA
26  0.4805815         ... 17.86793          41.00129          NA
27  0.4657708         ... 20.52280          48.41337          NA
28  0.4514414         ... 23.26728          50.81689          NA
29  0.4371614         ... 19.84982          53.17912          NA
30  0.4236315         ... 19.77440          52.58978          NA
... ...                   ...               ...               ...
32  0.3833411         ... 19.155805         57.45546           NA
33  0.3809716         ... 17.872005         54.98819           76
34  0.3746311         ... 18.660161         48.06805          233
35  0.3756027         ... 13.515716         41.89756           NA
36  0.3540785         ... 15.448542         46.11447          299
37  0.3609391         ... 23.203144         49.59925           NA
38  0.3217654         ... 16.770753         49.46652          319
39  0.2872342         ... 13.973902         46.85438          242
40  0.3560559         ... 11.083922         49.44305           NA
41  0.3390580         ...  9.729116         43.88317           47
42  0.3087852         ...  8.474469         50.60176           33
43  0.2965859         ...  9.692261         49.02528           NA
44  0.2781397         ... 15.740066         42.91545           39
45  0.2763161         ... 16.336605         35.88400           NA
46  0.2818726         ... 18.788816         35.93087           NA
47  0.2491595         ... 15.919137         35.27763           NA
48  0.2438590         ... 12.430473         48.83962           NA
49  0.3015485         ... 12.262564         46.48003           NA
50  0.3104965         ...  5.283116         51.12942           NA
51  0.2997283         ...  4.933799         48.35684           NA
52  0.2531877         ...  9.690348         45.49694           25
53  0.2462321         ... 11.670995         37.68579           NA
54  0.2321798         ... 12.324684         37.28724           NA
55  0.2257538         ... 12.905443         36.33489           NA
56  0.2195019         ... 12.104934         35.58202           NA
57  0.2134254         ... 12.253391         36.90141           NA
58         NA         ... 12.204782         37.07637           NA
59         NA         ... 13.303700         40.83143           NA
60         NA         ...        NA               NA           NA
61         NA         ...        NA               NA           NA
    VC.IDP.NWCV VC.IDP.NWDS VC.IDP.TOCV VC.IHR.PSRC.FE.P5 VC.IHR.PSRC.MA.P5
1   NA          NA          NA          NA                NA
2   NA          NA          NA          NA                NA
3   NA          NA          NA          NA                NA
4   NA          NA          NA          NA                NA
5   NA          NA          NA          NA                NA
6   NA          NA          NA          NA                NA
7   NA          NA          NA          NA                NA
8   NA          NA          NA          NA                NA
9   NA          NA          NA          NA                NA
10  NA          NA          NA          NA                NA
11  NA          NA          NA          NA                NA
12  NA          NA          NA          NA                NA
13  NA          NA          NA          NA                NA
14  NA          NA          NA          NA                NA
15  NA          NA          NA          NA                NA
16  NA          NA          NA          NA                NA
17  NA          NA          NA          NA                NA
18  NA          NA          NA          NA                NA
19  NA          NA          NA          NA                NA
20  NA          NA          NA          NA                NA
21  NA          NA          NA          NA                NA
22  NA          NA          NA          NA                NA
23  NA          NA          NA          NA                NA
24  NA          NA          NA          NA                NA
25  NA          NA          NA          NA                NA
26  NA          NA          NA          NA                NA
27  NA          NA          NA          NA                NA
28  NA          NA          NA          NA                NA
29  NA          NA          NA          NA                NA
30  NA          NA          NA          NA                NA
... ...         ...         ...         ...               ...
32    NA            NA         NA       NA                NA
33    NA            NA         NA       NA                NA
34    NA            NA         NA       NA                NA
35    NA            NA         NA       NA                NA
36    NA            NA         NA       NA                NA
37    NA            NA         NA       NA                NA
38    NA            NA         NA       NA                NA
39    NA            NA         NA       NA                NA
40    NA            NA         NA       NA                NA
41    NA            NA         NA       NA                NA
42    NA            NA         NA       NA                NA
43    NA            NA         NA       NA                NA
44    NA            NA         NA       NA                NA
45    NA            NA         NA       NA                NA
46    NA            NA         NA       NA                NA
47    NA            NA         NA       NA                NA
48    NA            NA         NA       NA                NA
49    NA            NA         NA       NA                NA
50  1000        264000      24000       NA                NA
51  4000          7800      24000       NA                NA
52    NA          1600      24000       NA                NA
53   170         20000      22000       NA                NA
54    NA         13000      24000       NA                NA
55    NA            NA      24000       NA                NA
56    NA            NA      24000       NA                NA
57    NA         24000      24000       NA                NA
58    NA           630      22000       NA                NA
59    NA             2      18000       NA                NA
60    NA          4400       8400       NA                NA
61    NA            NA         NA       NA                NA
    VC.IHR.PSRC.P5 VC.PKP.TOTL.UN
1   NA             NA
2   NA             NA
3   NA             NA
4   NA             NA
5   NA             NA
6   NA             NA
7   NA             NA
8   NA             NA
9   NA             NA
10  NA             NA
11  NA             NA
12  NA             NA
13  NA             NA
14  NA             NA
15  NA             NA
16  NA             NA
17  NA             NA
18  NA             NA
19  NA             NA
20  NA             NA
21  NA             NA
22  NA             NA
23  NA             NA
24  NA             NA
25  NA             NA
26  NA             NA
27  NA             NA
28  NA             NA
29  NA             NA
30  NA             NA
... ...            ...
32         NA      NA
33         NA      NA
34         NA      NA
35         NA      NA
36         NA      NA
37         NA      NA
38         NA      NA
39         NA      NA
40         NA      NA
41         NA      NA
42         NA      NA
43         NA      NA
44         NA      NA
45         NA      NA
46         NA      NA
47         NA      NA
48         NA      NA
49         NA      NA
50         NA      NA
51         NA      NA
52         NA      NA
53         NA      NA
54         NA      NA
55         NA      NA
56  0.2675182      NA
57         NA      NA
58         NA      NA
59         NA      NA
60         NA      NA
61         NA      NA

## Exercice

1. calculter le taux de dépendance au importantion de chaque produits alimentaires (base fao_cdu)(Importation/(Product+Import-Export)
2. calculer le taux d'auto-suffisance alimentaire de chaque produit alimentaire (Production/(Production+import-export)
3. calculer les depense public en % du PIB
4. Calculer la consommation des menage en % du PIB (donnee_fmi)
5. Extraire les indicateur n'ayant jamais de données de manquantes depuis 1960 dans la base donnee_bm